<script setup lang="ts">
const { logout } = useAdminAuth()
const api = useAdminApi()
const { data, error, refresh } = await useAsyncData('admin-overview', () => api<any>('/admin/overview'))
const counts = computed(() => data.value?.counts || {})
const recent = computed(() => data.value?.recent || [])
const resourceCards = [{ key:'products', label:'产品' },{ key:'reviews', label:'评测' },{ key:'comparisons', label:'比较' },{ key:'best-picks', label:'最佳选择' },{ key:'guides', label:'指南' },{ key:'troubleshooting', label:'故障指南' }]
useSeoMeta({ title: 'Dashboard — PetMetricus Admin' })
</script>
<template><div class="admin-shell"><AdminSidebar active="overview" /><main class="admin-main"><header class="topbar"><div><p class="kicker">CONTENT OPERATIONS</p><h1>工作台</h1></div><div class="top-actions"><span class="status-dot">数据库已连接</span><button class="ghost-button" @click="refresh">刷新数据</button><button class="ghost-button" @click="logout">退出</button></div></header><div v-if="error" class="alert">无法读取后台数据，请确认 Node 服务和 Token 设置。</div><section class="metric-grid"><NuxtLink v-for="item in resourceCards" :key="item.key" class="metric-card" :to="`/content/${item.key}`"><span>{{ item.label }}</span><strong>{{ counts[item.key] ?? '—' }}</strong><small>管理内容 →</small></NuxtLink></section><section class="dashboard-grid"><div class="panel"><div class="panel-heading"><div><p class="kicker">RECENT CHANGES</p><h2>最近更新</h2></div><NuxtLink to="/content/products">查看全部</NuxtLink></div><div v-if="!recent.length" class="empty-state">暂无更新记录</div><div v-for="item in recent" :key="`${item.type}-${item.id}`" class="recent-row"><span class="type-badge">{{ item.type }}</span><strong>{{ item.title }}</strong><time>{{ item.updated_at ? new Date(item.updated_at).toLocaleDateString('zh-CN') : '—' }}</time></div></div><div class="panel checklist"><p class="kicker">PUBLISHING HEALTH</p><h2>发布检查</h2><div><span>公开内容</span><strong>{{ Object.values(counts).reduce((sum: number, value: any) => sum + Number(value || 0), 0) }}</strong></div><div><span>图片存储</span><b>R2</b></div><div><span>数据源</span><b>MySQL</b></div><p class="muted">列表查询和编辑均通过受保护的管理 API 完成。</p></div></section></main></div></template>
