SET NAMES utf8mb4;

INSERT INTO categories
  (slug, title, eyebrow, description, subtitle, product_count, comparison_count, price_range, top_pick, top_score, image_url, image_key, alt_text, updated_label, sort_order)
VALUES
  ('automatic-litter-boxes','Automatic Litter Boxes','Products / Automatic Litter Boxes','Self-cleaning systems for single and multi-cat households, ranked by reliability and long-term cost.','Self-cleaning units for single and multi-cat households. We document reliability, app quality, noise levels, and the full cost of ownership — upfront and ongoing.',34,'3','$179–$699','Litter-Robot 4',4.3,'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=400&fit=crop&auto=format','categories/automatic-litter-boxes.webp','Cat next to a modern automatic litter box','Aug 2026',1),
  ('smart-pet-feeders','Smart Pet Feeders','Products / Smart Pet Feeders','Portion-controlled and camera-enabled feeders for dogs and cats, tested for dispensing accuracy.','Portion-controlled and camera-enabled feeders for dogs and cats. We test dispensing accuracy, scheduling flexibility, and long-term reliability.',28,'3+','$50–$130','PETLIBRO Granary',4.2,'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop&auto=format','categories/smart-pet-feeders.webp','Dog eating from an automatic feeder','Sep 2026',2),
  ('gps-pet-trackers','GPS Pet Trackers','Products / GPS Pet Trackers','Real-time location devices compared on coverage, battery life, subscription cost, and app reliability.','Real-time location devices compared on coverage area, battery life, subscription cost, and app reliability. We flag US-only limitations clearly.',19,'3+','$50–$150','Fi Series 3',4.1,'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop&auto=format','categories/gps-pet-trackers.webp','Dog wearing a GPS tracker collar outdoors','Aug 2026',3),
  ('pet-cameras','Pet Cameras','Products / Pet Cameras','Two-way audio, treat dispensing, and night vision — evaluated for video quality and app stability.','Two-way audio, treat dispensing, and night vision — evaluated for video quality, app stability, and real-world performance for managing pet anxiety.',22,'3+','$35–$169','Furbo 360°',4.0,'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&h=400&fit=crop&auto=format','categories/pet-cameras.webp','Cat being monitored by a home pet camera','Jul 2026',4)
ON DUPLICATE KEY UPDATE title=VALUES(title), eyebrow=VALUES(eyebrow), description=VALUES(description), subtitle=VALUES(subtitle), product_count=VALUES(product_count), comparison_count=VALUES(comparison_count), price_range=VALUES(price_range), top_pick=VALUES(top_pick), top_score=VALUES(top_score), image_url=VALUES(image_url), image_key=VALUES(image_key), alt_text=VALUES(alt_text), updated_label=VALUES(updated_label), sort_order=VALUES(sort_order);

DELETE FROM category_criteria;
INSERT INTO category_criteria (category_id, title, description, icon, sort_order) VALUES
((SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Number of cats','Single-cat households can use any unit. Two or more cats need a larger waste drawer and faster cycle recovery.','🐱',1),
((SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter type','Most automatic boxes require clumping litter. Crystal-tray units are the main exception.','🪣',2),
((SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Total cost of ownership','Compare the unit price with ongoing litter, tray, filter, bag, and subscription costs.','💰',3),
((SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'App and connectivity','App-connected units can expose usage trends, but app reliability varies significantly.','📱',4),
((SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Noise level','Prioritize models below 50 dB for bedrooms and open living spaces.','🔊',5),
((SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Dispensing accuracy','Variance at small portions matters most for diet-prescribed pets.','⚖️',1),
((SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Scheduling flexibility','Some units cap meals per day; others support per-meal intervals.','📅',2),
((SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Camera quality','1080p with night vision is standard; some cameras are add-on accessories.','📷',3),
((SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Power backup','Dual power prevents missed meals during outages.','🔌',4),
((SELECT id FROM categories WHERE slug='smart-pet-feeders'),'App reliability','A missed schedule is more serious than a missed notification.','📱',5),
((SELECT id FROM categories WHERE slug='gps-pet-trackers'),'Coverage area','US-only LTE-M and global cellular coverage suit different owners.','🌍',1),
((SELECT id FROM categories WHERE slug='gps-pet-trackers'),'Battery life','Battery life ranges from two days to three months.','🔋',2),
((SELECT id FROM categories WHERE slug='gps-pet-trackers'),'Monthly cost','Most GPS trackers require a subscription; compare annual cost.','💰',3),
((SELECT id FROM categories WHERE slug='gps-pet-trackers'),'Update frequency','Live tracking intervals materially affect recovery speed and battery life.','📍',4),
((SELECT id FROM categories WHERE slug='gps-pet-trackers'),'Health metrics','Some trackers include activity, sleep, and calorie data.','❤️',5),
((SELECT id FROM categories WHERE slug='pet-cameras'),'Field of view','Fixed lenses miss room corners; pan-and-tilt models cover more space.','📐',1),
((SELECT id FROM categories WHERE slug='pet-cameras'),'Night vision','Color night vision gives more usable detail than basic infrared.','🌙',2),
((SELECT id FROM categories WHERE slug='pet-cameras'),'Two-way audio','Speaker quality and latency determine whether pets respond.','🔊',3),
((SELECT id FROM categories WHERE slug='pet-cameras'),'Treat tossing','Treat range, capacity, and supported treat size vary.','🍬',4),
((SELECT id FROM categories WHERE slug='pet-cameras'),'Subscription cost','Check which alerts and recordings are locked behind a plan.','💰',5);

INSERT INTO products
  (external_id, category_id, slug, name, brand, price, price_display, subscription, score, verdict, best_for, image_url, image_key, alt_text, merchant_name, merchant_url, updated_label, rank_order, is_featured)
VALUES
('lr4',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'litter-robot-4','Litter-Robot 4','Whisker',699.00,'$699','Optional $12.49/mo',4.3,'The most reliable automatic litter box we''ve researched, with the best app-based health monitoring.','Multi-cat households (2–4 cats)','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=440&fit=crop&auto=format','products/litter-robot-4.webp','Litter-Robot 4','Litter-Robot','https://www.litter-robot.com/litter-robot-4.html','Aug 2026',1,TRUE),
('pura-x',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'petkit-pura-x','PETKIT PURA X','PETKIT',549.00,'$549','None',4.0,'Enclosed globe with quieter motor than the PURA MAX; good app with multi-cat weight identification.','Owners with 2 cats who want app health tracking','https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=440&fit=crop&auto=format','products/petkit-pura-x.webp','PETKIT PURA X','Amazon','https://www.amazon.com/s?k=PETKIT+PURA+X','Sep 2026',2,FALSE),
('pura-max',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'petkit-pura-max','PETKIT PURA MAX','PETKIT',399.00,'$399','None required',3.9,'Solid mid-range option with a competitive feature set at nearly half the Litter-Robot price.','Budget-conscious single-cat owners','https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=440&fit=crop&auto=format','products/petkit-pura-max.webp','PETKIT PURA MAX','Amazon','https://www.amazon.com/s?k=PETKIT+PURA+MAX','Aug 2026',3,FALSE),
('lr3',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'litter-robot-3-connect','Litter-Robot 3 Connect','Whisker',499.00,'$499','Optional $12.49/mo',3.9,'Previous-gen Litter-Robot — still reliable and available refurbished from Whisker.','Litter-Robot buyers on a tighter budget','https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=440&fit=crop&auto=format','products/litter-robot-3-connect.webp','Litter-Robot 3 Connect','Litter-Robot','https://www.litter-robot.com/litter-robot-iii-open-air-with-connect.html','May 2026',4,FALSE),
('catlink',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'catlink-luxury-pro-x','CATLINK Luxury Pro X','CATLINK',499.00,'$499','None',3.8,'Globe-style unit similar to Litter-Robot with more color options; app is less refined.','Owners wanting Litter-Robot style at lower cost','https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=600&h=440&fit=crop&auto=format','products/catlink-luxury-pro-x.webp','CATLINK Luxury Pro X','CATLINK','https://www.catlinkus.com/','Jun 2026',5,FALSE),
('scoopfree',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'petsafe-scoopfree-ultra','PetSafe ScoopFree Ultra','PetSafe',179.00,'$179','$28–35/mo (crystal trays)',3.6,'Best entry price; crystal litter trays mean excellent odor control but higher monthly costs.','Single-cat owners preferring crystal litter','https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=440&fit=crop&auto=format','products/petsafe-scoopfree-ultra.webp','PetSafe ScoopFree Ultra','PetSafe','https://www.petsafe.com/shop/cat/litter-boxes-and-litter/','Jul 2026',6,FALSE),
('fi-s3',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'fi-series-3','Fi Series 3','Fi',149.00,'$149','$8.25/mo',4.1,'Best battery life in the category with reliable US LTE-M coverage.','US-based owners with active or escape-prone dogs','https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=440&fit=crop&auto=format','products/fi-series-3.webp','Fi Series 3','Fi','https://tryfi.com/','Aug 2026',1,TRUE),
('tractive',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'tractive-gps-dog-4','Tractive GPS DOG 4','Tractive',49.99,'$49.99','$12.99/mo',3.9,'Affordable hardware with coverage in 175+ countries.','International travelers and cost-sensitive buyers','https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=440&fit=crop&auto=format','products/tractive-gps-dog-4.webp','Tractive GPS DOG 4','Tractive','https://tractive.com/en/pd/gps-tracker-dog','Aug 2026',2,FALSE),
('whistle',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'whistle-go-explore','Whistle GO Explore','Whistle',79.95,'$79.95','$9.95/mo',3.8,'GPS plus health tracking in one device for the US and Canada.','Health-conscious owners in North America','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=440&fit=crop&auto=format','products/whistle-go-explore.webp','Whistle GO Explore','Amazon','https://www.amazon.com/s?k=Whistle+GO+Explore+GPS','Jul 2026',3,FALSE),
('jiobit',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'jiobit-smart-tag','Jiobit Smart Tag','Jiobit',99.99,'$99.99','$8.99/mo',3.6,'Ultra-compact and lightweight for small dogs and cats.','Small dogs and cats under 10 lb','https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=440&fit=crop&auto=format','products/jiobit-smart-tag.webp','Jiobit Smart Tag','Jiobit','https://www.jiobit.com/','Jun 2026',4,FALSE),
('petlibro',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'petlibro-granary','PETLIBRO Granary','PETLIBRO',89.99,'$89.99',NULL,4.2,'Best dispensing accuracy we''ve tested (±2%), a 1080p camera, and flexible scheduling.','Pets on medically prescribed portion-control diets','https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=440&fit=crop&auto=format','products/petlibro-granary.webp','PETLIBRO Granary','PETLIBRO','https://petlibro.com/collections/automatic-pet-feeder','Sep 2026',1,TRUE),
('petkit',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'petkit-fresh-element-infinity','PETKIT Fresh Element Infinity','PETKIT',129.99,'$129.99',NULL,3.9,'A desiccant drying system keeps dry food fresh longer.','Owners in humid climates or with food-storage concerns','https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=440&fit=crop&auto=format','products/petkit-fresh-element-infinity.webp','PETKIT Fresh Element Infinity','PETKIT','https://www.petkit.com/collections/automatic-pet-feeder','Sep 2026',2,FALSE),
('petsafe',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'petsafe-healthy-pet-simply-feed','PetSafe Healthy Pet Simply Feed','PetSafe',99.99,'$99.99',NULL,3.8,'Slow-feed mode and reliable scheduling without an app.','Owners who want a reliable no-app feeder','https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=440&fit=crop&auto=format','products/petsafe-healthy-pet-simply-feed.webp','PetSafe Healthy Pet Simply Feed','PetSafe','https://www.petsafe.com/shop/','Jul 2026',3,FALSE),
('arf',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'arf-pets-feeder','Arf Pets Automatic Feeder','Arf Pets',54.99,'$54.99',NULL,3.7,'Reliable for standard schedules, with more variance at small portions.','Owners needing a basic schedule feeder without a camera','https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=600&h=440&fit=crop&auto=format','products/arf-pets-feeder.webp','Arf Pets Automatic Feeder','Amazon','https://www.amazon.com/s?k=Arf+Pets+Automatic+Pet+Feeder','Aug 2026',4,FALSE),
('furbo',(SELECT id FROM categories WHERE slug='pet-cameras'),'furbo-360','Furbo 360°','Furbo',169.00,'$169','$8.99/mo',4.0,'The best all-round pet camera with 360° pan, color night vision, and clear audio.','Dog owners managing separation anxiety','https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&h=440&fit=crop&auto=format','products/furbo-360.webp','Furbo 360°','Furbo','https://furbo.com/us/products/furbo-360-dog-camera','Jul 2026',1,TRUE),
('petcube',(SELECT id FROM categories WHERE slug='pet-cameras'),'petcube-bites-2','Petcube Bites 2','Petcube',89.99,'$89.99','$4.99/mo',3.8,'Lower price and subscription with adequate treat tossing.','Cat owners and budget-conscious buyers','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=440&fit=crop&auto=format','products/petcube-bites-2.webp','Petcube Bites 2','Petcube','https://petcube.com/bites-2-lite/','Jul 2026',2,FALSE),
('eufy',(SELECT id FROM categories WHERE slug='pet-cameras'),'eufy-pet-camera-e220','eufy Pet Camera E220','eufy',79.99,'$79.99',NULL,3.7,'Pan-and-tilt with local storage and no mandatory subscription.','Owners who prefer local storage over cloud subscriptions','https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=600&h=440&fit=crop&auto=format','products/eufy-pet-camera-e220.webp','eufy Pet Camera E220','eufy','https://www.eufy.com/products/t8410121','Jun 2026',3,FALSE),
('wyze',(SELECT id FROM categories WHERE slug='pet-cameras'),'wyze-cam-v3','Wyze Cam v3','Wyze',35.99,'$35.99',NULL,3.5,'The best budget option for basic live video and cloud storage.','Owners who just want live video without a subscription','https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=440&fit=crop&auto=format','products/wyze-cam-v3.webp','Wyze Cam v3','Wyze','https://www.wyze.com/products/wyze-cam-v3','Jun 2026',4,FALSE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), brand=VALUES(brand), price=VALUES(price), price_display=VALUES(price_display), subscription=VALUES(subscription), score=VALUES(score), verdict=VALUES(verdict), best_for=VALUES(best_for), image_url=VALUES(image_url), image_key=VALUES(image_key), alt_text=VALUES(alt_text), merchant_name=VALUES(merchant_name), merchant_url=VALUES(merchant_url), updated_label=VALUES(updated_label), rank_order=VALUES(rank_order), is_featured=VALUES(is_featured);

DELETE FROM product_tags;
INSERT INTO product_tags (product_id, tag, sort_order) VALUES
((SELECT id FROM products WHERE slug='litter-robot-4'),'Editor''s pick',1),((SELECT id FROM products WHERE slug='litter-robot-4'),'Multi-cat',2),
((SELECT id FROM products WHERE slug='petkit-pura-x'),'New',1),((SELECT id FROM products WHERE slug='petkit-pura-max'),'Budget pick',1),
((SELECT id FROM products WHERE slug='litter-robot-3-connect'),'Refurb available',1),((SELECT id FROM products WHERE slug='petsafe-scoopfree-ultra'),'Lowest upfront',1),
((SELECT id FROM products WHERE slug='fi-series-3'),'Editor''s pick',1),((SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'Best hardware price',1),
((SELECT id FROM products WHERE slug='jiobit-smart-tag'),'Lightest',1),((SELECT id FROM products WHERE slug='petlibro-granary'),'Editor''s pick',1),
((SELECT id FROM products WHERE slug='petlibro-granary'),'Best accuracy',2),((SELECT id FROM products WHERE slug='arf-pets-feeder'),'Budget pick',1),
((SELECT id FROM products WHERE slug='petsafe-healthy-pet-simply-feed'),'No app needed',1),((SELECT id FROM products WHERE slug='petkit-fresh-element-infinity'),'Best freshness',1),
((SELECT id FROM products WHERE slug='furbo-360'),'Editor''s pick',1),((SELECT id FROM products WHERE slug='petcube-bites-2'),'Best value',1),
((SELECT id FROM products WHERE slug='wyze-cam-v3'),'Lowest price',1),((SELECT id FROM products WHERE slug='eufy-pet-camera-e220'),'No subscription',1);

DELETE FROM product_specs;
INSERT INTO product_specs (product_id, spec_key, label, value, sort_order) VALUES
((SELECT id FROM products WHERE slug='litter-robot-4'),'cat_count','Cats','2–4 cats',1),((SELECT id FROM products WHERE slug='litter-robot-4'),'litter_type','Litter','Clumping',2),((SELECT id FROM products WHERE slug='litter-robot-4'),'app','Connectivity','App',3),
((SELECT id FROM products WHERE slug='petkit-pura-x'),'cat_count','Cats','1–2 cats',1),((SELECT id FROM products WHERE slug='petkit-pura-x'),'litter_type','Litter','Clumping',2),((SELECT id FROM products WHERE slug='petkit-pura-x'),'app','Connectivity','App',3),
((SELECT id FROM products WHERE slug='petkit-pura-max'),'cat_count','Cats','1–2 cats',1),((SELECT id FROM products WHERE slug='petkit-pura-max'),'litter_type','Litter','Clumping',2),((SELECT id FROM products WHERE slug='petkit-pura-max'),'app','Connectivity','App',3),
((SELECT id FROM products WHERE slug='litter-robot-3-connect'),'cat_count','Cats','1–2 cats',1),((SELECT id FROM products WHERE slug='litter-robot-3-connect'),'litter_type','Litter','Clumping',2),((SELECT id FROM products WHERE slug='litter-robot-3-connect'),'app','Connectivity','App',3),
((SELECT id FROM products WHERE slug='catlink-luxury-pro-x'),'cat_count','Cats','1–2 cats',1),((SELECT id FROM products WHERE slug='catlink-luxury-pro-x'),'litter_type','Litter','Clumping',2),((SELECT id FROM products WHERE slug='catlink-luxury-pro-x'),'app','Connectivity','App',3),
((SELECT id FROM products WHERE slug='petsafe-scoopfree-ultra'),'cat_count','Cats','1 cat',1),((SELECT id FROM products WHERE slug='petsafe-scoopfree-ultra'),'litter_type','Litter','Crystal',2),((SELECT id FROM products WHERE slug='petsafe-scoopfree-ultra'),'app','Connectivity','No app',3),
((SELECT id FROM products WHERE slug='fi-series-3'),'coverage','Coverage','US only',1),((SELECT id FROM products WHERE slug='fi-series-3'),'battery','Battery','3-month battery',2),((SELECT id FROM products WHERE slug='fi-series-3'),'network','Network','LTE-M + Wi-Fi',3),((SELECT id FROM products WHERE slug='fi-series-3'),'waterproof','Water resistance','IP68',4),
((SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'coverage','Coverage','175+ countries',1),((SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'battery','Battery','2–5 day battery',2),((SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'tracking','Tracking','Live: 2–3 sec',3),((SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'waterproof','Water resistance','IP67',4),
((SELECT id FROM products WHERE slug='whistle-go-explore'),'coverage','Coverage','US + Canada',1),((SELECT id FROM products WHERE slug='whistle-go-explore'),'battery','Battery','10-day battery',2),((SELECT id FROM products WHERE slug='whistle-go-explore'),'health','Health','Health tracking',3),((SELECT id FROM products WHERE slug='whistle-go-explore'),'weight','Form','Lightweight',4),
((SELECT id FROM products WHERE slug='jiobit-smart-tag'),'coverage','Coverage','US only',1),((SELECT id FROM products WHERE slug='jiobit-smart-tag'),'battery','Battery','7-day battery',2),((SELECT id FROM products WHERE slug='jiobit-smart-tag'),'weight','Weight','0.5 oz',3),((SELECT id FROM products WHERE slug='jiobit-smart-tag'),'waterproof','Water resistance','IP67',4),
((SELECT id FROM products WHERE slug='petlibro-granary'),'accuracy','Accuracy','±2% accuracy',1),((SELECT id FROM products WHERE slug='petlibro-granary'),'capacity','Capacity','6L hopper',2),((SELECT id FROM products WHERE slug='petlibro-granary'),'camera','Camera','1080p camera',3),((SELECT id FROM products WHERE slug='petlibro-granary'),'power','Power','Dual-power',4),
((SELECT id FROM products WHERE slug='arf-pets-feeder'),'accuracy','Accuracy','±8% accuracy',1),((SELECT id FROM products WHERE slug='arf-pets-feeder'),'capacity','Capacity','6L hopper',2),((SELECT id FROM products WHERE slug='arf-pets-feeder'),'camera','Camera','No camera',3),((SELECT id FROM products WHERE slug='arf-pets-feeder'),'power','Power','Dual-power',4),
((SELECT id FROM products WHERE slug='petsafe-healthy-pet-simply-feed'),'mode','Mode','Slow-feed mode',1),((SELECT id FROM products WHERE slug='petsafe-healthy-pet-simply-feed'),'schedule','Schedule','Up to 12 meals/day',2),((SELECT id FROM products WHERE slug='petsafe-healthy-pet-simply-feed'),'camera','Camera','No camera',3),((SELECT id FROM products WHERE slug='petsafe-healthy-pet-simply-feed'),'power','Power','Dual-power',4),
((SELECT id FROM products WHERE slug='petkit-fresh-element-infinity'),'freshness','Freshness','Desiccant system',1),((SELECT id FROM products WHERE slug='petkit-fresh-element-infinity'),'capacity','Capacity','3L hopper',2),((SELECT id FROM products WHERE slug='petkit-fresh-element-infinity'),'camera','Camera','1080p camera',3),((SELECT id FROM products WHERE slug='petkit-fresh-element-infinity'),'control','Control','App + manual',4),
((SELECT id FROM products WHERE slug='furbo-360'),'field_of_view','View','360° pan',1),((SELECT id FROM products WHERE slug='furbo-360'),'night_vision','Night vision','Color night vision',2),((SELECT id FROM products WHERE slug='furbo-360'),'alerts','Alerts','Dog Alert AI',3),((SELECT id FROM products WHERE slug='furbo-360'),'treat_range','Treat range','6 ft treat range',4),
((SELECT id FROM products WHERE slug='petcube-bites-2'),'field_of_view','View','138° fixed',1),((SELECT id FROM products WHERE slug='petcube-bites-2'),'night_vision','Night vision','IR night vision',2),((SELECT id FROM products WHERE slug='petcube-bites-2'),'treat_range','Treat range','5 ft treat range',3),((SELECT id FROM products WHERE slug='petcube-bites-2'),'resolution','Resolution','1080p HD',4),
((SELECT id FROM products WHERE slug='wyze-cam-v3'),'field_of_view','View','120° fixed',1),((SELECT id FROM products WHERE slug='wyze-cam-v3'),'night_vision','Night vision','Color night vision',2),((SELECT id FROM products WHERE slug='wyze-cam-v3'),'treats','Treats','No treats',3),((SELECT id FROM products WHERE slug='wyze-cam-v3'),'storage','Storage','Free cloud (12 sec)',4),
((SELECT id FROM products WHERE slug='eufy-pet-camera-e220'),'field_of_view','View','340° pan',1),((SELECT id FROM products WHERE slug='eufy-pet-camera-e220'),'night_vision','Night vision','IR night vision',2),((SELECT id FROM products WHERE slug='eufy-pet-camera-e220'),'treats','Treats','No treats',3),((SELECT id FROM products WHERE slug='eufy-pet-camera-e220'),'storage','Storage','Local SD storage',4);

INSERT INTO product_reviews (product_id, summary, gallery_json, quick_specs_json, strengths_json, limitations_json, sections_json, research_date, price_checked_date, next_review_label, source_count)
SELECT id, verdict, JSON_ARRAY(image_url), JSON_ARRAY(), JSON_ARRAY(), JSON_ARRAY(),
  JSON_ARRAY(JSON_OBJECT('title','What it is','body',verdict),JSON_OBJECT('title','Best for','body',best_for)),
  STR_TO_DATE(CONCAT('01 ', updated_label), '%d %b %Y'), STR_TO_DATE(CONCAT('01 ', updated_label), '%d %b %Y'), 'Quarterly review', NULL
FROM products
ON DUPLICATE KEY UPDATE summary=VALUES(summary), gallery_json=VALUES(gallery_json), sections_json=VALUES(sections_json);

UPDATE product_reviews SET
  summary='Whisker''s fourth-generation self-cleaning litter box with app-based usage and health monitoring.',
  quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Litter type','value','Clumping only'),JSON_OBJECT('label','Noise','value','~47 dB'),JSON_OBJECT('label','Warranty','value','18 months'),JSON_OBJECT('label','Subscription','value','Optional')),
  strengths_json=JSON_ARRAY('Globe design fully separates waste','App health tracking identifies usage changes','Large waste drawer','Quiet enough for bedroom placement','No proprietary litter required'),
  limitations_json=JSON_ARRAY('$699 entry price','Clumping litter only','Opening can be tight for very large cats','Optional odor consumables add cost','Pinch-detect false positives can interrupt cycles'),
  sections_json=JSON_ARRAY(
    JSON_OBJECT('title','What it is','body','The Litter-Robot 4 uses a rotating globe to separate clumps and deposits waste into a sealed drawer.'),
    JSON_OBJECT('title','Reliability','score',4.6,'body','Most reported interruptions are pinch-detect false positives and are commonly resolved by re-leveling or cleaning.'),
    JSON_OBJECT('title','App & connectivity','score',4.0,'body','The Whisker app tracks cycles and usage patterns. Historical health data beyond the base window requires the optional plan.'),
    JSON_OBJECT('title','Noise and placement','score',4.2,'body','Cycling noise is approximately 47 dB at one meter.'),
    JSON_OBJECT('title','Long-term cost','score',4.1,'body','The high entry price is partly offset by lower litter waste; odor pods remain optional.')
  ),
  research_date='2026-08-14', price_checked_date='2026-09-01', next_review_label='November 2026', source_count=11
WHERE product_id=(SELECT id FROM products WHERE slug='litter-robot-4');

INSERT INTO comparisons
  (slug, category_id, product_a_id, product_b_id, product_a_name, product_b_name, verdict, home_verdict, views_count, read_time, updated_label, content_json, sort_order, is_featured)
VALUES
('litter-robot-4-vs-petkit-pura-max',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='litter-robot-4'),(SELECT id FROM products WHERE slug='petkit-pura-max'),'Litter-Robot 4','PETKIT PURA MAX','Litter-Robot 4 is the more reliable long-term choice; PETKIT PURA MAX offers a lower entry price with competitive features.','Litter-Robot 4 for reliability; PETKIT for budget.',41200,'9 min read','Aug 2026',JSON_OBJECT('method','Identical criteria and current ownership costs'),1,TRUE),
('tractive-gps-vs-fi-series-3',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='tractive-gps-dog-4'),(SELECT id FROM products WHERE slug='fi-series-3'),'Tractive GPS','Fi Series 3','Tractive works globally and suits travelers; Fi Series 3 has superior US network coverage and a longer battery life.','Tractive for international travel; Fi for US coverage.',28500,'8 min read','Aug 2026',JSON_OBJECT('method','Coverage, battery, tracking, and annual cost'),2,TRUE),
('petlibro-granary-vs-arf-pets-feeder',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petlibro-granary'),(SELECT id FROM products WHERE slug='arf-pets-feeder'),'PETLIBRO Granary','Arf Pets Feeder','PETLIBRO edges ahead on dispensing consistency across all portion sizes; Arf Pets is adequate for standard schedules at a lower price.','PETLIBRO wins on dispensing accuracy at all portion sizes.',19300,'7 min read','Sep 2026',JSON_OBJECT('method','Portion consistency, scheduling, power, and camera'),3,TRUE),
('furbo-360-vs-petcube-bites-2',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='furbo-360'),(SELECT id FROM products WHERE slug='petcube-bites-2'),'Furbo 360°','Petcube Bites 2','Furbo 360° leads on video quality and dog alerts; Petcube Bites 2 offers a lower subscription cost with treat tossing.',NULL,14800,'8 min read','Jul 2026',JSON_OBJECT('method','Video, alerts, audio, treats, and recurring cost'),4,FALSE),
('litter-robot-4-vs-petsafe-scoopfree',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='litter-robot-4'),(SELECT id FROM products WHERE slug='petsafe-scoopfree-ultra'),'Litter-Robot 4','PetSafe ScoopFree','Litter-Robot 4 wins on long-term value; PetSafe ScoopFree suits owners who prefer crystal litter with minimal setup.',NULL,11400,'8 min read','Aug 2026',JSON_OBJECT('method','Setup, litter type, odor, app, and annual cost'),5,FALSE),
('whistle-go-explore-vs-tractive-gps',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='whistle-go-explore'),(SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'Whistle GO Explore','Tractive GPS','Whistle GO Explore adds health monitoring; Tractive is the better pure-GPS option for international use.',NULL,9600,'7 min read','Jul 2026',JSON_OBJECT('method','Coverage, health tracking, battery, and live intervals'),6,FALSE)
ON DUPLICATE KEY UPDATE verdict=VALUES(verdict), home_verdict=VALUES(home_verdict), views_count=VALUES(views_count), read_time=VALUES(read_time), updated_label=VALUES(updated_label), content_json=VALUES(content_json), sort_order=VALUES(sort_order), is_featured=VALUES(is_featured);

DELETE FROM comparison_best_for;
INSERT INTO comparison_best_for (comparison_id,pick_name,audience,sort_order) VALUES
((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Litter-Robot 4','Multi-cat households (2–4 cats)',1),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'PETKIT PURA MAX','Budget-conscious single-cat owners',2),
((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Tractive GPS','Owners who travel internationally with pets',1),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Fi Series 3','US-based owners with escape-prone dogs',2),
((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'PETLIBRO Granary','Cats or dogs on precise portion-control diets',1),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Arf Pets Feeder','Pet owners needing a reliable basic schedule feeder',2),
((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Furbo 360°','Dog owners with separation anxiety concerns',1),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Petcube Bites 2','Cat or small-dog owners who want treat interaction',2),
((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Litter-Robot 4','Owners wanting zero-waste-bag maintenance',1),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'PetSafe ScoopFree','Single-cat owners who prefer crystal litter',2),
((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Whistle GO Explore','Owners who want GPS and health insights',1),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Tractive GPS','Frequent travelers needing global coverage',2);

DELETE FROM comparison_criteria;
INSERT INTO comparison_criteria (comparison_id,label,product_a_value,product_b_value,winner,sort_order) VALUES
((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Price (unit)','$699','$399','b',1),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Monthly subscription','$0 (optional $12/mo)','$0','tie',2),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Waste drawer capacity','Large (13 lb)','Medium (9 lb)','a',3),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'App reliability','4.4 / 5 (12k reviews)','3.9 / 5 (4k reviews)','a',4),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Noise level','Quiet (47 dB)','Moderate (52 dB)','a',5),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petkit-pura-max'),'Self-cleaning cycle time','~3 min','~2 min','b',6),
((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Price (hardware)','$49.99','$149','a',1),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Monthly subscription','$12.99/mo','$8.25/mo','b',2),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'GPS coverage','175+ countries','US only','a',3),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Battery life','2–5 days','Up to 3 months','b',4),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Live tracking interval','2–3 sec','~10 sec','a',5),((SELECT id FROM comparisons WHERE slug='tractive-gps-vs-fi-series-3'),'Water resistance','IP67','IP68','b',6),
((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Price','$89.99','$54.99','b',1),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Portion accuracy','±2% variance','±8% variance','a',2),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Food capacity','6 L','6 L','tie',3),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Camera included','Yes (1080p)','No','a',4),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Dual power','Yes','Yes','tie',5),((SELECT id FROM comparisons WHERE slug='petlibro-granary-vs-arf-pets-feeder'),'Scheduling','1-meal intervals','4 meals/day max','a',6),
((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Price (unit)','$169','$89.99','b',1),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Monthly subscription','$8.99/mo','$4.99/mo','b',2),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Video resolution','1080p HD','1080p HD','tie',3),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Field of view','360° pan','138° fixed','a',4),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Night vision','Color','Infrared','a',5),((SELECT id FROM comparisons WHERE slug='furbo-360-vs-petcube-bites-2'),'Treat range','Up to 6 ft','Up to 5 ft','a',6),
((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Price (unit)','$699','$179','b',1),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Litter type','Clumping only','Crystal trays','tie',2),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Ongoing litter cost','~$18/mo','~$30/mo','a',3),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'App connectivity','Full app','No app','a',4),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Odor control','Excellent','Good','a',5),((SELECT id FROM comparisons WHERE slug='litter-robot-4-vs-petsafe-scoopfree'),'Setup time','~20 min','~5 min','b',6),
((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Price (hardware)','$79.95','$49.99','b',1),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Monthly subscription','$9.95/mo','$12.99/mo','a',2),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Health tracking','Calories, sleep, activity','Activity only','a',3),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'International coverage','US + Canada','175+ countries','b',4),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Battery life','Up to 10 days','2–5 days','a',5),((SELECT id FROM comparisons WHERE slug='whistle-go-explore-vs-tractive-gps'),'Live tracking interval','~10 sec','2–3 sec','b',6);

INSERT INTO best_picks
  (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,image_url,image_key,content_json,sort_order)
VALUES
('best-automatic-litter-box-multiple-cats',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Best automatic litter box for multiple cats',(SELECT id FROM products WHERE slug='litter-robot-4'),'Litter-Robot 4','$699 + ~$18/mo litter','High upfront cost for the most reliable multi-cat operation.',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'best-picks/multiple-cats.webp',JSON_OBJECT('why','Large drawer, reliable cycles, and per-cat usage monitoring','notFor','Single-cat homes on a tight budget'),1),
('best-gps-tracker-escape-prone-dogs',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Trackers','Best GPS tracker for escape-prone dogs',(SELECT id FROM products WHERE slug='fi-series-3'),'Fi Series 3','$149 + $8.25/mo','Excellent battery life, but coverage is US-only.',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'best-picks/escape-prone-dogs.webp',JSON_OBJECT('why','Long battery life and dependable US LTE-M coverage','notFor','International travelers'),2),
('best-pet-feeder-portion-control',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Feeders','Best pet feeder for portion control',(SELECT id FROM products WHERE slug='petlibro-granary'),'PETLIBRO Granary','$89.99','Best dispensing accuracy; camera version costs more.',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'best-picks/portion-control.webp',JSON_OBJECT('why','Low measured portion variance and flexible schedules','notFor','Owners who do not want app setup'),3),
('best-pet-camera-separation-anxiety',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Best pet camera for separation anxiety',(SELECT id FROM products WHERE slug='furbo-360'),'Furbo 360°','$169 + $8.99/mo','Strongest alerts and audio, with a recurring cloud fee.',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'best-picks/separation-anxiety.webp',JSON_OBJECT('why','Clear audio, wide coverage, and useful dog alerts','notFor','Owners avoiding subscriptions'),4),
('best-automatic-litter-box-small-spaces',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Best automatic litter box for small spaces',(SELECT id FROM products WHERE slug='petkit-pura-x'),'PETKIT PURA X','$499','A smaller footprint, with less waste-drawer capacity.',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'best-picks/small-spaces.webp',JSON_OBJECT('why','More compact enclosed body','notFor','Large multi-cat households'),5),
('best-gps-tracker-international-travel',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Trackers','Best GPS tracker for international travel',(SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'Tractive GPS','$49.99 + $12.99/mo','Broad international coverage, but shorter battery life.',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'best-picks/international-travel.webp',JSON_OBJECT('why','Coverage in more than 175 countries','notFor','Owners prioritizing multi-month battery life'),6),
('best-smart-feeder-simple-schedules',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Feeders','Best smart feeder for simple schedules',(SELECT id FROM products WHERE slug='arf-pets-feeder'),'Arf Pets Feeder','$54.99','Reliable basic scheduling without advanced app features.',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'best-picks/simple-schedules.webp',JSON_OBJECT('why','Low price and straightforward daily schedules','notFor','Medical-grade portion control'),7),
('best-pet-camera-treat-interaction',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Best pet camera for treat interaction',(SELECT id FROM products WHERE slug='petcube-bites-2'),'Petcube Bites 2','$89.99 + optional plan','Good treat interaction at a lower cost, without 360° pan.',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'best-picks/treat-interaction.webp',JSON_OBJECT('why','Reliable treat tossing at a lower price','notFor','Whole-room 360-degree monitoring'),8)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),image_url=VALUES(image_url),image_key=VALUES(image_key),content_json=VALUES(content_json),sort_order=VALUES(sort_order);

INSERT INTO guides
  (slug,category_id,category_label,title,description,read_time,updated_label,image_url,image_key,content_json,sort_order)
VALUES
('how-to-choose-automatic-litter-box',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','How to choose an automatic litter box','The five questions to answer before spending $200–$700 on a self-cleaning unit. Covers cat count, litter type, noise tolerance, and total cost of ownership.','8 min read','Aug 2026',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'guides/how-to-choose-automatic-litter-box.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Start with your cats','body','Match the entrance, weight range, cycle recovery, and drawer capacity to the number and size of your cats.'),JSON_OBJECT('title','Check litter compatibility','body','Most rotating systems require clumping litter.'),JSON_OBJECT('title','Calculate twelve-month cost','body','Include litter, bags, filters, trays, and optional subscriptions.'))),1),
('gps-tracker-subscription-costs-explained',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Trackers','GPS tracker subscription costs, explained','Why every GPS tracker requires a subscription, what is typically locked behind the paywall, and how to calculate the real annual cost before buying.','6 min read','Aug 2026',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'guides/gps-tracker-subscription-costs-explained.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Why a plan is required','body','Cellular location reporting uses a carrier connection.'),JSON_OBJECT('title','Compare annual cost','body','Add hardware, activation, and the minimum usable plan.'))),2),
('clumping-vs-crystal-litter',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Clumping vs. crystal litter: which is cheaper long-term?','Crystal trays have a lower upfront cost per tray but higher monthly cost than clumping brands. We run the numbers for 1, 2, and 3-cat households.','5 min read','Jul 2026','https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=380&fit=crop&auto=format','guides/clumping-vs-crystal-litter.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Monthly cost','body','Crystal trays prioritize convenience; clumping litter generally costs less over time.'),JSON_OBJECT('title','Compatibility','body','Use only the litter types supported by the device manufacturer.'))),3),
('pet-feeder-dispensing-accuracy',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Feeders','Why dispensing accuracy matters (and how to test it)','A 10% variance on a 5g portion is clinically significant for a diet-controlled pet. Here is how to measure it.','7 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'guides/pet-feeder-dispensing-accuracy.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Run repeated trials','body','Weigh at least ten identical portions and calculate the range and average.'),JSON_OBJECT('title','Test your actual kibble','body','Shape and size affect every dispensing mechanism.'))),4),
('pet-camera-separation-anxiety-guide',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Pet cameras and separation anxiety: what actually helps','Two-way audio can comfort some dogs and stress others. We explain which features reduce anxiety and which mainly reassure owners.','9 min read','Jul 2026',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'guides/pet-camera-separation-anxiety-guide.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Observe the response','body','Stop remote audio if hearing a disembodied voice increases pacing or barking.'),JSON_OBJECT('title','Use alerts as evidence','body','Track patterns and discuss persistent distress with a qualified professional.'))),5),
('wifi-vs-cellular-pet-tracker',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Trackers','Wi-Fi triangulation vs. cellular GPS: what is the difference?','Fi Series 3 uses both; Tractive uses cellular. We explain where each technology works and fails.','6 min read','Aug 2026',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'guides/wifi-vs-cellular-pet-tracker.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Wi-Fi zones save battery','body','Known Wi-Fi can indicate that a pet remains at home without continuous GPS.'),JSON_OBJECT('title','Cellular moves locations','body','A cellular link sends GPS positions when a pet leaves known coverage.'))),6)
ON DUPLICATE KEY UPDATE title=VALUES(title),description=VALUES(description),read_time=VALUES(read_time),updated_label=VALUES(updated_label),image_url=VALUES(image_url),image_key=VALUES(image_key),content_json=VALUES(content_json),sort_order=VALUES(sort_order);

INSERT INTO troubleshooting_guides
  (slug,category_id,product_id,product_name,problem,title,description,difficulty,estimated_time,views_count,updated_label,content_json,sort_order)
VALUES
('litter-robot-4-not-cycling',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='litter-robot-4'),'Litter-Robot 4','Not cycling after waste deposit','Litter-Robot 4 not cycling','A safe sequence for deposits that do not trigger an automatic clean cycle.','Easy fix','5 min',18400,'Aug 2026',JSON_OBJECT('safety','Unplug the device if it is hot, smells burnt, or exposes a moving mechanism.'),1),
('litter-robot-4-pinch-detect',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='litter-robot-4'),'Litter-Robot 4','Pinch detect fault — cycle stops mid-run','Litter-Robot 4 pinch detect fault','Clear a cycle that stops mid-run without forcing the mechanism.','Easy fix','8 min',9200,'Jul 2026',JSON_OBJECT('safety','Keep pets away while inspecting the globe and seal.'),2),
('tractive-gps-location-not-updating',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'Tractive GPS','Location not updating in real time','Tractive GPS location not updating','What to check when live location goes stale or the tracker appears offline.','Moderate','10 min',14100,'Aug 2026',JSON_OBJECT('safety','Search the last known area while diagnostics run; do not rely on the app alone.'),3),
('tractive-battery-draining',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='tractive-gps-dog-4'),'Tractive GPS','Battery draining faster than expected','Tractive battery draining faster than expected','Check tracking mode, coverage, and the settings that consume the most power.','Moderate','10 min',5900,'Aug 2026',JSON_OBJECT('safety','Stop charging if the battery swells or becomes unusually hot.'),4),
('petlibro-granary-not-dispensing',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petlibro-granary'),'PETLIBRO Granary','Not dispensing food on schedule','PETLIBRO Granary not dispensing','A checklist for jammed food paths, schedules, and backup power.','Easy fix','7 min',7600,'Sep 2026',JSON_OBJECT('safety','Disconnect power before clearing the food path.'),5),
('petlibro-feeder-offline',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petlibro-granary'),'PETLIBRO Granary','Offline or app cannot connect','PETLIBRO feeder offline or app cannot connect','Reconnect the feeder without losing its saved schedule.','Easy fix','8 min',4800,'Sep 2026',JSON_OBJECT('safety','Confirm a backup feeding plan before network troubleshooting.'),6),
('furbo-camera-offline',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='furbo-360'),'Furbo Dog Camera','Offline or not connecting to app','Furbo camera offline or not connecting','Restore the connection without resetting more than necessary.','Easy fix','8 min',6800,'Jul 2026',JSON_OBJECT('safety','Inspect the cable before reconnecting power.'),7),
('furbo-treat-toss-jammed',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='furbo-360'),'Furbo Dog Camera','Treat toss not working or jammed','Furbo treat toss not working or jammed','Clear the treat path safely and check treat size.','Easy fix','8 min',3600,'Jul 2026',JSON_OBJECT('safety','Unplug the camera before clearing the mechanism.'),8),
('litter-robot-4-globe-not-rotating',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='litter-robot-4'),'Litter-Robot 4','Globe not rotating — motor noise but no movement','Litter-Robot 4 globe not rotating','What to inspect when the motor runs but the globe does not move.','Moderate','12 min',5100,'Jun 2026',JSON_OBJECT('safety','Do not force or hand-rotate a powered globe.'),9),
('fi-series-3-dog-not-on-map',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='fi-series-3'),'Fi Series 3','Dog not showing on map after escaping','Fi Series 3 dog not showing on the map','Recover the latest known location and force a fresh LTE-M location check.','Moderate','10 min',4300,'Aug 2026',JSON_OBJECT('safety','Begin physical search and contact local resources immediately.'),10),
('petkit-pura-max-cat-not-using',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='petkit-pura-max'),'PETKIT PURA MAX','Cat not using the litter box after setup','Cat not using the PETKIT PURA MAX','A low-stress 48-hour transition sequence for a cat avoiding a new box.','Easy fix','48 hr',3900,'Jul 2026',JSON_OBJECT('safety','Contact a veterinarian if the cat is unable to urinate or defecate.'),11)
ON DUPLICATE KEY UPDATE product_id=VALUES(product_id),product_name=VALUES(product_name),problem=VALUES(problem),title=VALUES(title),description=VALUES(description),difficulty=VALUES(difficulty),estimated_time=VALUES(estimated_time),views_count=VALUES(views_count),updated_label=VALUES(updated_label),content_json=VALUES(content_json),sort_order=VALUES(sort_order);

DELETE FROM troubleshooting_steps;
INSERT INTO troubleshooting_steps (guide_id,instruction,sort_order) VALUES
((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-not-cycling'),'Re-level the unit on a flat, hard surface',1),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-not-cycling'),'Check that the globe is fully seated on the base',2),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-not-cycling'),'Clean the DFI lens with a dry cloth',3),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-not-cycling'),'Reset via the app: Settings → Reset Cycle',4),
((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-pinch-detect'),'Remove litter and check for foreign objects',1),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-pinch-detect'),'Inspect the bonnet seal for tears',2),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-pinch-detect'),'Clean the pinch-detect strips',3),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-pinch-detect'),'Perform the documented reset if the fault persists',4),
((SELECT id FROM troubleshooting_guides WHERE slug='tractive-gps-location-not-updating'),'Confirm the tracker has at least 20% battery',1),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-gps-location-not-updating'),'Verify the device is registered in the app',2),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-gps-location-not-updating'),'Switch to live tracking',3),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-gps-location-not-updating'),'Move outdoors and allow up to two minutes for GPS lock',4),
((SELECT id FROM troubleshooting_guides WHERE slug='tractive-battery-draining'),'Check the selected live-tracking interval',1),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-battery-draining'),'Move out of persistently weak coverage',2),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-battery-draining'),'Disable unnecessary activity alerts',3),((SELECT id FROM troubleshooting_guides WHERE slug='tractive-battery-draining'),'Update firmware and run one full charge cycle',4),
((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-granary-not-dispensing'),'Confirm the schedule was saved',1),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-granary-not-dispensing'),'Confirm connection to 2.4 GHz Wi-Fi',2),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-granary-not-dispensing'),'Check the hopper for bridging',3),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-granary-not-dispensing'),'Trigger one supervised manual meal',4),
((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-feeder-offline'),'Confirm mains or battery power',1),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-feeder-offline'),'Verify the router broadcasts 2.4 GHz Wi-Fi',2),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-feeder-offline'),'Restart the feeder and router once',3),((SELECT id FROM troubleshooting_guides WHERE slug='petlibro-feeder-offline'),'Re-pair without deleting the saved schedule',4),
((SELECT id FROM troubleshooting_guides WHERE slug='furbo-camera-offline'),'Power-cycle the camera for 30 seconds',1),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-camera-offline'),'Confirm phone and camera use the intended Wi-Fi',2),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-camera-offline'),'Re-pair only if the device no longer appears',3),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-camera-offline'),'Use the LED state to identify the connection stage',4),
((SELECT id FROM troubleshooting_guides WHERE slug='furbo-treat-toss-jammed'),'Unplug the camera',1),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-treat-toss-jammed'),'Remove treats and inspect the path',2),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-treat-toss-jammed'),'Use treats within the supported size',3),((SELECT id FROM troubleshooting_guides WHERE slug='furbo-treat-toss-jammed'),'Run one supervised test toss',4),
((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-globe-not-rotating'),'Remove the globe and inspect gear teeth',1),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-globe-not-rotating'),'Inspect globe pins and motor coupler',2),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-globe-not-rotating'),'Reseat the globe without forcing it',3),((SELECT id FROM troubleshooting_guides WHERE slug='litter-robot-4-globe-not-rotating'),'Contact Whisker if the motor sounds strained',4),
((SELECT id FROM troubleshooting_guides WHERE slug='fi-series-3-dog-not-on-map'),'Open the dog profile and note the last known location',1),((SELECT id FROM troubleshooting_guides WHERE slug='fi-series-3-dog-not-on-map'),'Switch to LTE-M mode',2),((SELECT id FROM troubleshooting_guides WHERE slug='fi-series-3-dog-not-on-map'),'Contact Fi support for a location poll',3),((SELECT id FROM troubleshooting_guides WHERE slug='fi-series-3-dog-not-on-map'),'Activate local lost-dog search resources',4),
((SELECT id FROM troubleshooting_guides WHERE slug='petkit-pura-max-cat-not-using'),'Disable automatic cleaning for 48 hours',1),((SELECT id FROM troubleshooting_guides WHERE slug='petkit-pura-max-cat-not-using'),'Keep the old litter box beside the new unit',2),((SELECT id FROM troubleshooting_guides WHERE slug='petkit-pura-max-cat-not-using'),'Use the cat''s familiar litter brand',3),((SELECT id FROM troubleshooting_guides WHERE slug='petkit-pura-max-cat-not-using'),'Allow a gradual, low-pressure transition',4);

INSERT INTO site_settings (setting_key,setting_value) VALUES
('home',JSON_OBJECT('eyebrow','Independent research','title','Pet tech research you can actually verify.','description','We research automatic litter boxes, GPS trackers, smart feeders, and pet cameras with documented methods, dated sources, and clear commercial disclosures.')),
('methodology',JSON_ARRAY(JSON_OBJECT('icon','🔬','title','Documented methods','body','Every research decision records the criteria, sources, and date.'),JSON_OBJECT('icon','📅','title','Dated and updated','body','Pages show a last-checked date and review schedule.'),JSON_OBJECT('icon','💬','title','Error correction','body','Readers can submit corrections for verification.'),JSON_OBJECT('icon','🔗','title','Commercial disclosure','body','Affiliate and sponsored relationships are labeled.')))
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

INSERT INTO content_pages (slug,title,description,content_json) VALUES
('about','About PetMetricus','How PetMetricus researches and explains pet technology.',JSON_OBJECT('eyebrow','About PetMetricus','sections',JSON_ARRAY(JSON_OBJECT('title','Our purpose','body','PetMetricus helps owners make evidence-led pet technology decisions.'),JSON_OBJECT('title','How we work','body','We use consistent criteria, dated sources, and transparent corrections.')))),
('editorial-standards','Editorial Standards','PetMetricus research, scoring, sourcing, and correction standards.',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Research independence','body','Commercial relationships do not change scores or verdicts.'),JSON_OBJECT('title','Sources','body','Manufacturer documentation is checked against independent reports where available.'),JSON_OBJECT('title','Corrections','body','Verified corrections are applied and dated.')))),
('disclosure','Commercial Disclosure','How PetMetricus handles affiliate links and commercial relationships.',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Affiliate links','body','PetMetricus may earn a commission from qualifying purchases at no additional cost to the reader.'),JSON_OBJECT('title','Editorial separation','body','Revenue relationships do not determine inclusion, rank, score, or verdict.')))),
('privacy','Privacy Policy','How PetMetricus handles site and contact data.',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Information collected','body','The site may process basic request logs and information voluntarily submitted through contact forms.'),JSON_OBJECT('title','Retention','body','Data is retained only as needed for operations, security, and legal obligations.')))),
('contact','Contact PetMetricus','Submit a correction, question, or product issue.',JSON_OBJECT('intro','Send a source URL and enough context for the research team to verify the issue.'))
ON DUPLICATE KEY UPDATE title=VALUES(title),description=VALUES(description),content_json=VALUES(content_json);
