/* Expand the catalog with additional products that are linked to existing categories. */
INSERT INTO products (external_id,category_id,slug,name,brand,price,price_display,subscription,score,verdict,best_for,image_url,image_key,alt_text,merchant_name,merchant_url,updated_label,rank_order,is_featured)
VALUES
('water-pioneer',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'petkit-eversweet-3','PETKIT Eversweet 3','PETKIT',69.99,'$69.99','Replacement filters',3.8,'A quiet stainless-steel fountain with simple maintenance and no required app.','Owners prioritizing quiet operation','https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=440&fit=crop&auto=format','products/petkit-eversweet-3.webp','PETKIT Eversweet 3 smart water fountain','PETKIT','https://www.petkit.com/','Sep 2026',3,FALSE),
('water-catit',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'catit-pixi-smart-fountain','Catit PIXI Smart Fountain','Catit',89.99,'$89.99','Replacement filters',3.7,'App alerts and a compact footprint make this useful for owners who want refill reminders.','Small homes and single cats','https://images.unsplash.com/photo-1589924691106-073b0f4d7f0a?w=600&h=440&fit=crop&auto=format','products/catit-pixi-smart-fountain.webp','Catit PIXI Smart Fountain','Catit','https://www.catit.com/','Sep 2026',4,FALSE),
('camera-ring',(SELECT id FROM categories WHERE slug='pet-cameras'),'ring-indoor-cam-2nd-gen','Ring Indoor Cam (2nd Gen)','Ring',59.99,'$59.99','Optional Ring Protect',3.6,'A general indoor camera with privacy shutter and reliable basic live view.','Owners prioritizing privacy controls','https://images.unsplash.com/photo-1558008258-3256797b43f3?w=600&h=440&fit=crop&auto=format','products/ring-indoor-cam-2nd-gen.webp','Ring Indoor Cam 2nd Gen','Ring','https://ring.com/','Sep 2026',5,FALSE),
('feeder-wopet',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'wopet-automatic-feeder','WOPET Automatic Pet Feeder with Camera','WOPET',79.99,'$79.99','None required',3.6,'A lower-cost connected feeder with camera monitoring and standard portion scheduling.','Budget-conscious connected-feeder buyers','https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=440&fit=crop&auto=format','products/wopet-automatic-feeder.webp','WOPET Automatic Pet Feeder with Camera','WOPET','https://wopet.com/','Sep 2026',5,FALSE),
('tracker-pawfit',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'pawfit-3s','Pawfit 3s GPS Tracker','Pawfit',79.99,'$79.99','$5.95/mo',3.7,'A compact tracker with activity and voice features, balanced against a recurring plan.','Owners wanting activity and voice features','https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=440&fit=crop&auto=format','products/pawfit-3s.webp','Pawfit 3s GPS Tracker','Pawfit','https://www.pawfit.com/','Sep 2026',5,FALSE)
ON DUPLICATE KEY UPDATE name=VALUES(name),price=VALUES(price),price_display=VALUES(price_display),subscription=VALUES(subscription),score=VALUES(score),verdict=VALUES(verdict),best_for=VALUES(best_for),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),updated_label=VALUES(updated_label),rank_order=VALUES(rank_order),is_featured=VALUES(is_featured);

INSERT INTO best_picks (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,image_url,image_key,content_json,sort_order)
VALUES
('best-smart-water-fountain-low-maintenance',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'Water Fountains','Best smart water fountain for low maintenance',(SELECT id FROM products WHERE slug='petlibro-dockstream-2'),'PETLIBRO Dockstream 2 Smart Water Fountain','$79.99 + replacement filters','App monitoring helps, but filter costs continue over time.',(SELECT image_url FROM categories WHERE slug='smart-water-fountains'),'best-picks/water-low-maintenance.webp',JSON_OBJECT('why','Accessible water area and app refill reminders reduce daily oversight','notFor','Owners who want no consumable filters'),9),
('best-pet-camera-privacy',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Best pet camera for privacy controls',(SELECT id FROM products WHERE slug='ring-indoor-cam-2nd-gen'),'Ring Indoor Cam (2nd Gen)','$59.99 + optional plan','General security-camera features; no treat interaction.',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'best-picks/camera-privacy.webp',JSON_OBJECT('why','Physical privacy shutter and straightforward live view','notFor','Owners who need treat tossing or pet-specific alerts'),10)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),content_json=VALUES(content_json),sort_order=VALUES(sort_order);

INSERT INTO comparisons (slug,category_id,product_a_id,product_b_id,product_a_name,product_b_name,verdict,views_count,read_time,updated_label,content_json,sort_order,is_featured,is_published)
VALUES ('petkit-eversweet-vs-catit-pixi',(SELECT id FROM categories WHERE slug='smart-water-fountains'),(SELECT id FROM products WHERE slug='petkit-eversweet-3'),(SELECT id FROM products WHERE slug='catit-pixi-smart-fountain'),'PETKIT Eversweet 3','Catit PIXI Smart Fountain','A quiet stainless-steel fountain is compared with a compact app-connected fountain; cleaning access and recurring filter cost matter more than tank size alone.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','direct-alternatives','matchLabel','Direct alternatives','whyCompare','Both target owners who want fresher water with less daily attention.','decisionQuestion','Do you value quiet stainless-steel construction or app refill reminders?'),16,FALSE,TRUE)
ON DUPLICATE KEY UPDATE product_a_id=VALUES(product_a_id),product_b_id=VALUES(product_b_id),product_a_name=VALUES(product_a_name),product_b_name=VALUES(product_b_name),verdict=VALUES(verdict),updated_label=VALUES(updated_label),content_json=VALUES(content_json),is_published=TRUE;
