SET NAMES utf8mb4;

INSERT INTO products
  (external_id,category_id,slug,name,brand,price,price_display,subscription,score,verdict,best_for,image_url,image_key,alt_text,merchant_name,merchant_url,updated_label,rank_order,is_featured,is_published)
VALUES
('litter-neakasa',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'neakasa-m1-plus','Neakasa M1 Plus','Neakasa',549.00,'$549','Optional app features',4.0,'An open-top design with a generous entry and useful waste handling, balanced against a larger footprint.','Cats that dislike enclosed globes','https://images.unsplash.com/photo-1513245543132-31f507417b26?w=700&h=520&fit=crop&auto=format','products/neakasa-m1-plus.webp','Neakasa M1 Plus automatic litter box','Neakasa','https://neakasa.com/','Sep 2026',7,FALSE,TRUE),
('litter-leos',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'litterbox-leos-loo-too','Leo''s Loo Too','Smarty Pear',699.00,'$699','Optional app features',3.9,'A premium globe unit with odor control and app monitoring, but replacement parts and service coverage need checking.','Owners wanting premium odor control','https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=700&h=520&fit=crop&auto=format','products/leos-loo-too.webp','Leo''s Loo Too automatic litter box','Smarty Pear','https://smartypear.com/','Sep 2026',8,FALSE,TRUE),
('feeder-air',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'petlibro-air-feeder','PETLIBRO Air Automatic Feeder','PETLIBRO',59.99,'$59.99','None required',3.8,'A compact feeder for straightforward portions and schedules, without a camera or recurring plan.','Small spaces and basic schedules','https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=700&h=520&fit=crop&auto=format','products/petlibro-air-feeder.webp','PETLIBRO Air automatic pet feeder','PETLIBRO','https://petlibro.com/','Sep 2026',6,FALSE,TRUE),
('feeder-honey',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'honeyguardian-a36','HoneyGuaridan A36 Automatic Feeder','HoneyGuaridan',69.99,'$69.99','None required',3.6,'A budget schedule feeder with dual-bowl dispensing and more portion variance at very small meals.','Two-pet households sharing a schedule','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=700&h=520&fit=crop&auto=format','products/honeyguardian-a36.webp','HoneyGuaridan A36 automatic feeder','HoneyGuaridan','https://honeyguardian.com/','Sep 2026',7,FALSE,TRUE),
('tracker-catmini',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'tractive-gps-cat-mini','Tractive GPS CAT Mini','Tractive',49.99,'$49.99','$9.99/mo',3.8,'A lightweight cat tracker with live location and activity trends, limited by cellular coverage and subscription cost.','Outdoor cats that tolerate a tracker','https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=700&h=520&fit=crop&auto=format','products/tractive-gps-cat-mini.webp','Tractive GPS CAT Mini tracker','Tractive','https://tractive.com/','Sep 2026',6,FALSE,TRUE),
('tracker-garmin',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'garmin-alpha-t20','Garmin Alpha T 20','Garmin',249.99,'$249.99','No cellular plan; compatible handheld required',3.7,'A long-range training and tracking collar for rural use, with higher upfront cost and a more complex setup.','Working dogs and rural tracking','https://images.unsplash.com/photo-1552053831-71594a27632d?w=700&h=520&fit=crop&auto=format','products/garmin-alpha-t20.webp','Garmin Alpha T 20 dog tracking collar','Garmin','https://www.garmin.com/','Sep 2026',7,FALSE,TRUE),
('camera-petcube',(SELECT id FROM categories WHERE slug='pet-cameras'),'petcube-cam-360','Petcube Cam 360','Petcube',49.99,'$49.99','Optional plan',3.7,'A compact pan-and-tilt camera with two-way audio and a lower entry price than treat-dispensing models.','Room coverage on a smaller budget','https://images.unsplash.com/photo-1558008258-3256797b43f3?w=700&h=440&fit=crop&auto=format','products/petcube-cam-360.webp','Petcube Cam 360 pet camera','Petcube','https://petcube.com/','Sep 2026',5,FALSE,TRUE),
('camera-blink',(SELECT id FROM categories WHERE slug='pet-cameras'),'blink-mini-2','Blink Mini 2','Blink',39.99,'$39.99','Optional Blink subscription',3.5,'A low-cost indoor camera with basic detection and optional cloud recording, but limited pet-specific interaction.','Basic live video on a tight budget','https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=700&h=440&fit=crop&auto=format','products/blink-mini-2.webp','Blink Mini 2 indoor camera for pets','Blink','https://blinkforhome.com/','Sep 2026',6,FALSE,TRUE),
('water-drinkwell',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'petsafe-drinkwell-cep','PetSafe Drinkwell Ceramic Pagoda','PetSafe',89.99,'$89.99','Replacement filters',3.6,'A ceramic fountain with a visible stream and no required app, traded against filter replacement and more parts to clean.','Pets that prefer a visible stream','https://images.unsplash.com/photo-1589924691106-073b0f4d7f0a?w=700&h=520&fit=crop&auto=format','products/petsafe-drinkwell-ceramic.webp','PetSafe Drinkwell Ceramic Pagoda fountain','PetSafe','https://www.petsafe.com/','Sep 2026',5,FALSE,TRUE),
('door-hightech',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'high-tech-pet-px2','High Tech Pet Power Pet Door PX-2','High Tech Pet',399.00,'$399','None required',3.7,'A motorized door designed for larger pets with collar-based access and a substantial installation commitment.','Large dogs and dedicated installations','https://images.unsplash.com/photo-1544568100-847a948585b9?w=700&h=520&fit=crop&auto=format','products/high-tech-pet-px2.webp','High Tech Pet Power Pet Door PX-2','High Tech Pet','https://www.hitecpet.com/','Sep 2026',4,FALSE,TRUE),
('health-fitbark',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'fitbark-2','FitBark 2','FitBark',69.95,'$69.95','None required',3.6,'An activity-focused wearable that is simpler and lighter than broader wellness-monitoring collars.','Owners tracking activity trends without a plan','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=700&h=520&fit=crop&auto=format','products/fitbark-2.webp','FitBark 2 dog activity monitor','FitBark','https://www.fitbark.com/','Sep 2026',4,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),brand=VALUES(brand),price=VALUES(price),price_display=VALUES(price_display),subscription=VALUES(subscription),score=VALUES(score),verdict=VALUES(verdict),best_for=VALUES(best_for),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),merchant_name=VALUES(merchant_name),merchant_url=VALUES(merchant_url),updated_label=VALUES(updated_label),rank_order=VALUES(rank_order),is_featured=VALUES(is_featured),is_published=TRUE;

INSERT INTO comparisons
  (slug,category_id,product_a_id,product_b_id,product_a_name,product_b_name,verdict,views_count,read_time,updated_label,content_json,sort_order,is_featured,is_published)
VALUES
('neakasa-m1-plus-vs-litter-robot-4',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='neakasa-m1-plus'),(SELECT id FROM products WHERE slug='litter-robot-4'),'Neakasa M1 Plus','Whisker Litter-Robot 4','An open-top entry and a rotating globe take different approaches to cat acceptance, waste handling, app detail, and maintenance.',0,'9 min read','Sep 2026',JSON_OBJECT('matchType','direct-alternatives','matchLabel','Direct alternatives','whyCompare','Both target premium buyers who want less daily scooping but differ in structure and cat fit.','decisionQuestion','Will an open-top design or a mature rotating workflow suit your cats better?'),19,FALSE,TRUE),
('petlibro-air-vs-honeyguardian-a36',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petlibro-air-feeder'),(SELECT id FROM products WHERE slug='honeyguardian-a36'),'PETLIBRO Air Automatic Feeder','HoneyGuaridan A36 Automatic Feeder','Both cover scheduled feeding without a subscription; portion repeatability, bowl layout, and household pet access separate them.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','value-alternatives','matchLabel','Value alternatives','whyCompare','These are simple feeders for owners who do not need a camera or cloud workflow.','decisionQuestion','Which low-cost schedule and bowl setup better fits your pets?'),20,FALSE,TRUE),
('petcube-360-vs-blink-mini-2',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='petcube-cam-360'),(SELECT id FROM products WHERE slug='blink-mini-2'),'Petcube Cam 360','Blink Mini 2','Petcube adds pan-and-tilt and pet-oriented controls, while Blink keeps the hardware price low with a general indoor-camera workflow.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','specialist-vs-generalist','matchLabel','Specialist vs generalist','whyCompare','Both provide affordable live video but make different trade-offs around coverage and pet features.','decisionQuestion','Do you need pet-focused coverage or the lowest-cost basic camera?'),21,FALSE,TRUE),
('petsafe-drinkwell-vs-dockstream-2',(SELECT id FROM categories WHERE slug='smart-water-fountains'),(SELECT id FROM products WHERE slug='petsafe-drinkwell-cep'),(SELECT id FROM products WHERE slug='petlibro-dockstream-2'),'PetSafe Drinkwell Ceramic Pagoda','PETLIBRO Dockstream 2 Smart Water Fountain','A visible-stream ceramic fountain is compared with an app-connected fountain focused on hydration trends and a more contained water path.',0,'8 min read','Sep 2026',JSON_OBJECT('matchType','feature-tradeoff','matchLabel','Different approaches','whyCompare','Both aim to encourage drinking but prioritize different cleaning, monitoring, and stream designs.','decisionQuestion','Should you prioritize a visible stream or app-visible hydration trends?'),22,FALSE,TRUE),
('sureflap-vs-hightech-pet-door',(SELECT id FROM categories WHERE slug='smart-pet-doors'),(SELECT id FROM products WHERE slug='sureflap-microchip-pet-door-connect'),(SELECT id FROM products WHERE slug='high-tech-pet-px2'),'SureFlap Microchip Pet Door Connect','High Tech Pet Power Pet Door PX-2','Microchip-led selective access for smaller pets meets a motorized collar-key door intended for larger installations.',0,'8 min read','Sep 2026',JSON_OBJECT('matchType','fit-first','matchLabel','Fit-first decision','whyCompare','Pet size and installation constraints dominate this choice before connected features.','decisionQuestion','Which access technology fits your pet and opening?'),23,FALSE,TRUE),
('petpace-vs-fitbark',(SELECT id FROM categories WHERE slug='pet-health-monitors'),(SELECT id FROM products WHERE slug='petpace-smart-collar'),(SELECT id FROM products WHERE slug='fitbark-2'),'PetPace Smart Collar','FitBark 2','PetPace emphasizes broader wellness signals with a plan; FitBark keeps activity tracking simpler and subscription-free.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','scope-tradeoff','matchLabel','Scope trade-off','whyCompare','The right choice depends on whether broader signals justify more setup and ongoing cost.','decisionQuestion','Do you need broader wellness context or simple activity trends?'),24,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_a_id=VALUES(product_a_id),product_b_id=VALUES(product_b_id),product_a_name=VALUES(product_a_name),product_b_name=VALUES(product_b_name),verdict=VALUES(verdict),content_json=VALUES(content_json),updated_label=VALUES(updated_label),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO comparison_best_for (comparison_id,pick_name,audience,sort_order)
SELECT x.id,v.pick_name,v.audience,v.sort_order FROM comparisons x JOIN (
SELECT 'neakasa-m1-plus-vs-litter-robot-4' slug,'Neakasa M1 Plus' pick_name,'Cats that prefer an open-top entry and owners checking the larger footprint.' audience,1 sort_order UNION ALL SELECT 'neakasa-m1-plus-vs-litter-robot-4','Whisker Litter-Robot 4','Multi-cat owners prioritizing a mature rotating workflow and established app.' ,2 UNION ALL
SELECT 'petlibro-air-vs-honeyguardian-a36','PETLIBRO Air Automatic Feeder','Small spaces and owners who want a compact basic feeder.',1 UNION ALL SELECT 'petlibro-air-vs-honeyguardian-a36','HoneyGuaridan A36 Automatic Feeder','Two pets sharing a dual-bowl schedule.',2 UNION ALL
SELECT 'petcube-360-vs-blink-mini-2','Petcube Cam 360','Owners who value pan-and-tilt coverage.',1 UNION ALL SELECT 'petcube-360-vs-blink-mini-2','Blink Mini 2','Owners who need basic live video at the lowest hardware price.',2 UNION ALL
SELECT 'petsafe-drinkwell-vs-dockstream-2','PetSafe Drinkwell Ceramic Pagoda','Pets that respond to a visible stream.',1 UNION ALL SELECT 'petsafe-drinkwell-vs-dockstream-2','PETLIBRO Dockstream 2 Smart Water Fountain','Owners who want app-visible hydration trends.',2 UNION ALL
SELECT 'sureflap-vs-hightech-pet-door','SureFlap Microchip Pet Door Connect','Cats and smaller pets needing selective microchip access.',1 UNION ALL SELECT 'sureflap-vs-hightech-pet-door','High Tech Pet Power Pet Door PX-2','Larger dogs and dedicated installations.',2 UNION ALL
SELECT 'petpace-vs-fitbark','PetPace Smart Collar','Vet-guided broader wellness monitoring.',1 UNION ALL SELECT 'petpace-vs-fitbark','FitBark 2','Simple activity trends without a subscription.',2
) v ON v.slug=x.slug WHERE NOT EXISTS (SELECT 1 FROM comparison_best_for b WHERE b.comparison_id=x.id AND b.pick_name=v.pick_name);

INSERT INTO best_picks
  (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,image_url,image_key,content_json,sort_order,is_published)
VALUES
('best-open-top-automatic-litter-box',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Best open-top automatic litter box',(SELECT id FROM products WHERE slug='neakasa-m1-plus'),'Neakasa M1 Plus','$549','Open-top acceptance comes with a larger footprint and fit checks.',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'best-picks/open-top-litter-box.webp',JSON_OBJECT('why','Open entry can suit cats that resist enclosed globes','notFor','Small rooms or owners seeking the smallest footprint'),14,TRUE),
('best-basic-pet-feeder-small-space',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Feeders','Best basic feeder for a small space',(SELECT id FROM products WHERE slug='petlibro-air-feeder'),'PETLIBRO Air Automatic Feeder','$59.99','No camera or advanced remote features.',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'best-picks/basic-small-feeder.webp',JSON_OBJECT('why','Compact body and simple scheduling without a plan','notFor','Owners needing remote video or medical-grade accuracy'),15,TRUE),
('best-budget-pet-camera-live-video',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Best budget camera for live video',(SELECT id FROM products WHERE slug='blink-mini-2'),'Blink Mini 2','$39.99 + optional plan','General indoor camera features with limited pet interaction.',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'best-picks/budget-live-video.webp',JSON_OBJECT('why','Low hardware price and straightforward live view','notFor','Owners needing treat tossing or pet-specific alerts'),16,TRUE),
('best-visible-stream-water-fountain',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'Water Fountains','Best fountain for a visible stream',(SELECT id FROM products WHERE slug='petsafe-drinkwell-cep'),'PetSafe Drinkwell Ceramic Pagoda','$89.99 plus filters','Ceramic parts and filters add cleaning and replacement work.',(SELECT image_url FROM categories WHERE slug='smart-water-fountains'),'best-picks/visible-stream-fountain.webp',JSON_OBJECT('why','Visible water movement can appeal to some pets','notFor','Owners who want app monitoring or minimal parts'),17,TRUE),
('best-large-dog-smart-door',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'Smart Pet Doors','Best smart pet door for a large dog',(SELECT id FROM products WHERE slug='high-tech-pet-px2'),'High Tech Pet Power Pet Door PX-2','$399','Installation is more involved and collar-key access must fit the dog.',(SELECT image_url FROM categories WHERE slug='smart-pet-doors'),'best-picks/large-dog-door.webp',JSON_OBJECT('why','Motorized opening and large-pet fit are the core advantages','notFor','Renters or cats needing microchip-only access'),18,TRUE),
('best-simple-pet-activity-monitor',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'Health Monitors','Best simple pet activity monitor',(SELECT id FROM products WHERE slug='fitbark-2'),'FitBark 2','$69.95','Activity trends are narrower than a broader wellness collar.',(SELECT image_url FROM categories WHERE slug='pet-health-monitors'),'best-picks/simple-activity-monitor.webp',JSON_OBJECT('why','Lightweight activity tracking without a recurring plan','notFor','Owners expecting temperature, breathing, or diagnostic signals'),19,TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),content_json=VALUES(content_json),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO troubleshooting_guides
  (slug,category_id,product_id,product_name,problem,title,description,difficulty,estimated_time,views_count,updated_label,content_json,sort_order,is_published)
VALUES
('neakasa-m1-plus-open-top-not-cycling',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='neakasa-m1-plus'),'Neakasa M1 Plus','Open-top unit does not start a cleaning cycle','Neakasa M1 Plus not cycling','Check drawer seating, weight detection, power, and the documented reset sequence.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Keep pets away from the unit during a supervised cycle.'),18,TRUE),
('petlibro-air-not-dispensing',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petlibro-air-feeder'),'PETLIBRO Air Automatic Feeder','Feeder skips a scheduled portion','PETLIBRO Air not dispensing','Verify the schedule, food path, portion setting, and battery or mains power.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','Provide a reliable backup meal while testing a missed schedule.'),19,TRUE),
('tractive-cat-mini-location-stale',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='tractive-gps-cat-mini'),'Tractive GPS CAT Mini','Cat location has not updated','Tractive CAT Mini location stale','Check battery, coverage, live mode, and whether the tracker is attached as expected.','Moderate','15 min',0,'Sep 2026',JSON_OBJECT('safety','Begin a physical search immediately if an outdoor cat is missing.'),20,TRUE),
('blink-mini-2-camera-offline',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='blink-mini-2'),'Blink Mini 2','Camera is offline','Blink Mini 2 offline','Check power, Wi-Fi band, router distance, and account pairing before resetting the camera.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','Do not rely on a camera as the only safety check for a pet.'),21,TRUE),
('petsafe-drinkwell-low-flow',(SELECT id FROM categories WHERE slug='smart-water-fountains'),(SELECT id FROM products WHERE slug='petsafe-drinkwell-cep'),'PetSafe Drinkwell Ceramic Pagoda','Water flow is weak','Drinkwell fountain weak flow','Clean the pump, intake screen, spout, and water path, then confirm the tank level.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','Disconnect power before opening or cleaning the pump.'),22,TRUE),
('hightech-px2-door-not-opening',(SELECT id FROM categories WHERE slug='smart-pet-doors'),(SELECT id FROM products WHERE slug='high-tech-pet-px2'),'High Tech Pet Power Pet Door PX-2','Motorized door does not open for the pet','High Tech Pet door not opening','Check collar-key battery, door power, alignment, and manual override behavior.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Keep the manual access mode available while testing.'),23,TRUE),
('fitbark-2-not-syncing',(SELECT id FROM categories WHERE slug='pet-health-monitors'),(SELECT id FROM products WHERE slug='fitbark-2'),'FitBark 2','Activity data is not syncing','FitBark 2 not syncing','Charge the device, confirm Bluetooth range, and allow a full sync before interpreting missing activity.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','A missing reading is not evidence that a pet is inactive or well.'),24,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_id=VALUES(product_id),product_name=VALUES(product_name),problem=VALUES(problem),title=VALUES(title),description=VALUES(description),difficulty=VALUES(difficulty),estimated_time=VALUES(estimated_time),updated_label=VALUES(updated_label),content_json=VALUES(content_json),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO troubleshooting_steps (guide_id,instruction,sort_order)
SELECT g.id,v.instruction,v.sort_order FROM troubleshooting_guides g JOIN (
SELECT 'neakasa-m1-plus-open-top-not-cycling' slug,'Reseat the waste drawer and confirm the unit is level.' instruction,1 sort_order UNION ALL SELECT 'neakasa-m1-plus-open-top-not-cycling','Check the power connection and weight-detection area.',2 UNION ALL SELECT 'neakasa-m1-plus-open-top-not-cycling','Remove loose litter from the cycle path.',3 UNION ALL SELECT 'neakasa-m1-plus-open-top-not-cycling','Run one supervised empty cycle.',4 UNION ALL
SELECT 'petlibro-air-not-dispensing','Confirm the meal schedule and portion are saved.',1 UNION ALL SELECT 'petlibro-air-not-dispensing','Check for a bridge or blockage in the food path.',2 UNION ALL SELECT 'petlibro-air-not-dispensing','Confirm power and backup battery status.',3 UNION ALL SELECT 'petlibro-air-not-dispensing','Run one supervised manual portion.',4 UNION ALL
SELECT 'tractive-cat-mini-location-stale','Confirm the tracker is charged and attached securely.',1 UNION ALL SELECT 'tractive-cat-mini-location-stale','Move outdoors or to an area with known coverage.',2 UNION ALL SELECT 'tractive-cat-mini-location-stale','Start live mode and wait for a fresh location.',3 UNION ALL SELECT 'tractive-cat-mini-location-stale','Contact support if the timestamp remains stale.',4 UNION ALL
SELECT 'blink-mini-2-camera-offline','Confirm the camera light and power adapter are working.',1 UNION ALL SELECT 'blink-mini-2-camera-offline','Check the configured Wi-Fi band and router distance.',2 UNION ALL SELECT 'blink-mini-2-camera-offline','Restart the camera and app once.',3 UNION ALL SELECT 'blink-mini-2-camera-offline','Re-pair only after noting the existing settings.',4 UNION ALL
SELECT 'petsafe-drinkwell-low-flow','Disconnect power and remove the pump cover.',1 UNION ALL SELECT 'petsafe-drinkwell-low-flow','Clear hair and debris from the intake and impeller.',2 UNION ALL SELECT 'petsafe-drinkwell-low-flow','Clean the spout and water path.',3 UNION ALL SELECT 'petsafe-drinkwell-low-flow','Refill to the marked level and run one supervised test.',4 UNION ALL
SELECT 'hightech-px2-door-not-opening','Replace or recharge the collar-key battery.',1 UNION ALL SELECT 'hightech-px2-door-not-opening','Confirm the door has power and the flap is aligned.',2 UNION ALL SELECT 'hightech-px2-door-not-opening','Test the manual override without forcing the motor.',3 UNION ALL SELECT 'hightech-px2-door-not-opening','Contact support if the motor strains or remains locked.',4 UNION ALL
SELECT 'fitbark-2-not-syncing','Charge the tracker and keep it near the phone.',1 UNION ALL SELECT 'fitbark-2-not-syncing','Open the app and wait for the sync indicator.',2 UNION ALL SELECT 'fitbark-2-not-syncing','Toggle Bluetooth once if the device is not found.',3 UNION ALL SELECT 'fitbark-2-not-syncing','Contact support if a charged device still will not sync.',4
) v ON v.slug=g.slug WHERE NOT EXISTS (SELECT 1 FROM troubleshooting_steps s WHERE s.guide_id=g.id AND s.instruction=v.instruction);
