SET NAMES utf8mb4;

-- Round-two catalog expansion: two additional products per category.
INSERT INTO products
  (external_id,category_id,slug,name,brand,price,price_display,subscription,score,verdict,best_for,image_url,image_key,alt_text,merchant_name,merchant_url,updated_label,rank_order,is_featured,is_published)
VALUES
('litter-pura-max2',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'petkit-pura-max-2','PETKIT Pura Max 2','PETKIT',599.00,'$599','Optional app features',4.0,'A compact rotating unit with strong odor control and app routines, but the enclosed entry needs a careful fit check.','Homes wanting a quieter premium globe','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format','products/petkit-pura-max-2.webp','PETKIT Pura Max 2 automatic litter box','PETKIT','https://petkit.com/','Sep 2026',9,FALSE,TRUE),
('litter-catgenie-ai',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'catgenie-ai','CatGenie A.I. Self-Washing Litter Box','CatGenie',499.00,'$499','Consumable granules and SaniSolution',3.7,'A plumbed self-washing approach that reduces solid-waste handling, with installation and consumables to plan for.','Utility rooms with plumbing access','https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=700&h=520&fit=crop&auto=format','products/catgenie-ai.webp','CatGenie A.I. self-washing litter box','CatGenie','https://www.catgenie.com/','Sep 2026',10,FALSE,TRUE),
('feeder-wopet-7l',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'wopet-7l-smart-feeder','WOPET 7L Smart Feeder','WOPET',89.99,'$89.99','Optional app features',3.7,'A larger hopper and scheduled portions suit longer gaps between refills, while very small portions can vary.','Medium and large dogs','https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=700&h=520&fit=crop&auto=format','products/wopet-7l-smart-feeder.webp','WOPET 7L smart pet feeder','WOPET','https://wopet.com/','Sep 2026',8,FALSE,TRUE),
('feeder-petsafe-smart-feed-2',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'petsafe-smart-feed-2','PetSafe Smart Feed 2.0','PetSafe',149.99,'$149.99','Optional app features',3.8,'A polished app-connected feeder with a conveyor-style outlet and dependable scheduling, at a higher price.','Owners wanting app control from a known brand','https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=700&h=520&fit=crop&auto=format','products/petsafe-smart-feed-2.webp','PetSafe Smart Feed 2.0 automatic feeder','PetSafe','https://www.petsafe.com/','Sep 2026',9,FALSE,TRUE),
('tracker-fi-series3-collar',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'fi-series-3-smart-collar','Fi Series 3 Smart Dog Collar','Fi',149.00,'$149 plus membership','$19/mo',4.0,'A durable LTE collar with geofencing and activity history, balanced against a required membership for core tracking.','Escape-prone dogs in covered LTE areas','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=700&h=520&fit=crop&auto=format','products/fi-series-3-smart-collar.webp','Fi Series 3 smart GPS dog collar','Fi','https://tryfi.com/','Sep 2026',8,FALSE,TRUE),
('tracker-pawscout-smarter',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'pawscout-smarter-tracker','Pawscout Smarter GPS Tracker','Pawscout',99.95,'$99.95','Optional plan',3.5,'A lighter tracker with community location support and basic activity context, with less consistent coverage than LTE-first rivals.','Neighborhood roaming cats and small dogs','https://images.unsplash.com/photo-1558929996-da64ba858215?w=700&h=520&fit=crop&auto=format','products/pawscout-smarter-tracker.webp','Pawscout Smarter GPS pet tracker','Pawscout','https://pawscout.com/','Sep 2026',9,FALSE,TRUE),
('camera-eufy-pet-s350',(SELECT id FROM categories WHERE slug='pet-cameras'),'eufy-pet-camera-s350','eufy Pet Camera S350','eufy',129.99,'$129.99','No required plan; optional cloud',4.0,'A sharper pan-and-tilt camera with local-storage options and useful tracking, though setup has more choices.','Owners prioritizing image quality and local storage','https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=700&h=440&fit=crop&auto=format','products/eufy-pet-camera-s350.webp','eufy Pet Camera S350 indoor camera','eufy','https://www.eufy.com/','Sep 2026',7,FALSE,TRUE),
('camera-petkit-petwant',(SELECT id FROM categories WHERE slug='pet-cameras'),'petkit-petwant-camera','PETKIT PetWant Camera','PETKIT',79.99,'$79.99','Optional plan',3.6,'A simple wide-angle camera that pairs with PETKIT routines, with fewer advanced controls than dedicated security cameras.','PETKIT households wanting one companion app','https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=700&h=440&fit=crop&auto=format','products/petkit-petwant-camera.webp','PETKIT PetWant pet camera','PETKIT','https://petkit.com/','Sep 2026',8,FALSE,TRUE),
('water-pioneer-raindrop',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'pioneer-raindrop-stainless','Pioneer Pet Raindrop Stainless','Pioneer Pet',49.99,'$49.99 plus filters','Replacement filters',3.7,'A quiet stainless fountain with a broad drinking surface and simple controls, but no connected usage history.','Cats that dislike narrow streams','https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=700&h=520&fit=crop&auto=format','products/pioneer-raindrop-stainless.webp','Pioneer Pet Raindrop stainless steel fountain','Pioneer Pet','https://pioneerpet.com/','Sep 2026',6,FALSE,TRUE),
('water-catit-flower-stainless',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'catit-flower-stainless','Catit Flower Fountain Stainless Top','Catit',59.99,'$59.99 plus filters','Replacement filters',3.8,'A compact fountain with interchangeable flow settings and a stainless drinking top that is easy to wipe down.','Cats sharing a compact feeding station','https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=700&h=520&fit=crop&auto=format','products/catit-flower-stainless.webp','Catit Flower stainless top water fountain','Catit','https://www.catit.com/','Sep 2026',7,FALSE,TRUE),
('door-petsafe-smartdoor',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'petsafe-smartdoor-microchip','PetSafe SmartDoor Connected Pet Door','PetSafe',299.99,'$299.99','Optional app features',3.8,'A connected selective-access door with schedules and app alerts, but wall thickness and hub placement matter.','Multi-pet homes needing schedules','https://images.unsplash.com/photo-1560807707-8cc77767d783?w=700&h=520&fit=crop&auto=format','products/petsafe-smartdoor-microchip.webp','PetSafe SmartDoor Connected pet door','PetSafe','https://www.petsafe.com/','Sep 2026',5,FALSE,TRUE),
('door-sureflap-dualscan',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'sureflap-dualscan-connect','SureFlap DualScan Connect','SureFlap',249.99,'$249.99','Optional hub features',4.0,'A microchip door with inside-and-outside permissions for multi-cat homes, with a smaller opening than dog doors.','Multi-cat homes with selective access','https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=700&h=520&fit=crop&auto=format','products/sureflap-dualscan-connect.webp','SureFlap DualScan Connect microchip pet door','SureFlap','https://www.surepetcare.com/','Sep 2026',6,FALSE,TRUE),
('health-whistle-health',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'whistle-health-monitor','Whistle Health Monitor','Whistle',119.95,'$119.95','$8.25/mo',3.7,'A collar-based wellness dashboard for activity, sleep, and scratching trends, with insights tied to a subscription.','Owners watching recurring wellness patterns','https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=700&h=520&fit=crop&auto=format','products/whistle-health-monitor.webp','Whistle Health pet monitor','Whistle','https://www.whistle.com/','Sep 2026',5,FALSE,TRUE),
('health-petivity-litter-monitor-2',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'petivity-smart-litter-monitor-2','Petivity Smart Litter Box Monitor 2','Petivity',119.99,'$119.99','No required plan',3.8,'A scale-based monitor that tracks litter-box visits and weight trends without putting a collar on the pet.','Multi-cat homes tracking litter habits','https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=700&h=520&fit=crop&auto=format','products/petivity-smart-litter-monitor-2.webp','Petivity Smart Litter Box Monitor 2','Petivity','https://petivity.com/','Sep 2026',6,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),brand=VALUES(brand),price=VALUES(price),price_display=VALUES(price_display),subscription=VALUES(subscription),score=VALUES(score),verdict=VALUES(verdict),best_for=VALUES(best_for),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),merchant_name=VALUES(merchant_name),merchant_url=VALUES(merchant_url),updated_label=VALUES(updated_label),rank_order=VALUES(rank_order),is_published=TRUE;

INSERT INTO comparisons
  (slug,category_id,product_a_id,product_b_id,product_a_name,product_b_name,verdict,views_count,read_time,updated_label,content_json,sort_order,is_featured,is_published)
VALUES
('petkit-pura-max-2-vs-catgenie-ai',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='petkit-pura-max-2'),(SELECT id FROM products WHERE slug='catgenie-ai'),'PETKIT Pura Max 2','CatGenie A.I.','A contained rotating workflow is easier to place, while CatGenie trades installation work for self-washing waste handling.',0,'8 min read','Sep 2026',JSON_OBJECT('matchType','workflow-tradeoff','matchLabel','Workflow trade-off','whyCompare','These premium boxes reduce scooping in very different ways.','decisionQuestion','Do you prefer a simpler install or a self-washing system?'),25,FALSE,TRUE),
('wopet-7l-vs-petsafe-smart-feed-2',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='wopet-7l-smart-feeder'),(SELECT id FROM products WHERE slug='petsafe-smart-feed-2'),'WOPET 7L Smart Feeder','PetSafe Smart Feed 2.0','WOPET offers more hopper capacity, while PetSafe delivers a more polished app and conveyor-style dispensing.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','capacity-vs-polish','matchLabel','Capacity vs polish','whyCompare','Both automate meals but prioritize different ownership routines.','decisionQuestion','Is fewer refills or a refined app workflow more important?'),26,FALSE,TRUE),
('fi-series-3-vs-pawscout-smarter',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='fi-series-3-smart-collar'),(SELECT id FROM products WHERE slug='pawscout-smarter-tracker'),'Fi Series 3 Smart Dog Collar','Pawscout Smarter GPS Tracker','Fi has stronger LTE and escape alerts with a membership; Pawscout lowers ongoing commitment but depends more on local coverage.',0,'8 min read','Sep 2026',JSON_OBJECT('matchType','coverage-vs-cost','matchLabel','Coverage vs cost','whyCompare','The trade-off is dependable cellular tracking versus a lighter ownership cost.','decisionQuestion','How much coverage certainty justifies a monthly plan?'),27,FALSE,TRUE),
('eufy-s350-vs-petkit-petwant',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='eufy-pet-camera-s350'),(SELECT id FROM products WHERE slug='petkit-petwant-camera'),'eufy Pet Camera S350','PETKIT PetWant Camera','eufy provides sharper pan-and-tilt coverage and local storage; PETKIT keeps setup simpler for existing PETKIT users.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','image-vs-ecosystem','matchLabel','Image vs ecosystem','whyCompare','Both cover a room, but one leans security-camera quality and the other app simplicity.','decisionQuestion','Do you value local video quality or one pet-focused ecosystem?'),28,FALSE,TRUE),
('pioneer-raindrop-vs-catit-flower-stainless',(SELECT id FROM categories WHERE slug='smart-water-fountains'),(SELECT id FROM products WHERE slug='pioneer-raindrop-stainless'),(SELECT id FROM products WHERE slug='catit-flower-stainless'),'Pioneer Pet Raindrop Stainless','Catit Flower Fountain Stainless Top','Pioneer offers a wide drinking surface, while Catit adds configurable flow and a compact footprint.',0,'6 min read','Sep 2026',JSON_OBJECT('matchType','surface-vs-settings','matchLabel','Surface vs settings','whyCompare','Both are simple fountains for owners who do not need an app.','decisionQuestion','Will your pet prefer a broad pool or adjustable streams?'),29,FALSE,TRUE),
('petsafe-smartdoor-vs-sureflap-dualscan',(SELECT id FROM categories WHERE slug='smart-pet-doors'),(SELECT id FROM products WHERE slug='petsafe-smartdoor-microchip'),(SELECT id FROM products WHERE slug='sureflap-dualscan-connect'),'PetSafe SmartDoor Connected Pet Door','SureFlap DualScan Connect','PetSafe favors scheduled connected access, while SureFlap offers fine-grained two-way permissions for cats.',0,'8 min read','Sep 2026',JSON_OBJECT('matchType','schedule-vs-permission','matchLabel','Schedules vs permissions','whyCompare','Pet size, opening dimensions, and access rules matter more than app branding.','decisionQuestion','Do you need scheduled access or per-cat in/out permissions?'),30,FALSE,TRUE),
('whistle-health-vs-petivity-monitor-2',(SELECT id FROM categories WHERE slug='pet-health-monitors'),(SELECT id FROM products WHERE slug='whistle-health-monitor'),(SELECT id FROM products WHERE slug='petivity-smart-litter-monitor-2'),'Whistle Health Monitor','Petivity Smart Litter Box Monitor 2','Whistle follows the pet throughout the day; Petivity focuses on litter visits and weight without a wearable.',0,'7 min read','Sep 2026',JSON_OBJECT('matchType','wearable-vs-environment','matchLabel','Wearable vs environment','whyCompare','Choose the signal source that your pet will tolerate and your household can act on.','decisionQuestion','Do you need whole-day activity or litter-box-specific trends?'),31,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_a_id=VALUES(product_a_id),product_b_id=VALUES(product_b_id),product_a_name=VALUES(product_a_name),product_b_name=VALUES(product_b_name),verdict=VALUES(verdict),content_json=VALUES(content_json),updated_label=VALUES(updated_label),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO comparison_best_for (comparison_id,pick_name,audience,sort_order)
SELECT x.id,v.pick_name,v.audience,v.sort_order FROM comparisons x JOIN (
SELECT 'petkit-pura-max-2-vs-catgenie-ai' slug,'PETKIT Pura Max 2' pick_name,'Owners wanting a premium globe without plumbing work.' audience,1 sort_order UNION ALL SELECT 'petkit-pura-max-2-vs-catgenie-ai','CatGenie A.I.','Utility rooms where self-washing and consumables are acceptable.',2 UNION ALL
SELECT 'wopet-7l-vs-petsafe-smart-feed-2','WOPET 7L Smart Feeder','Large pets and owners who refill less often.',1 UNION ALL SELECT 'wopet-7l-vs-petsafe-smart-feed-2','PetSafe Smart Feed 2.0','Owners prioritizing a polished schedule app.',2 UNION ALL
SELECT 'fi-series-3-vs-pawscout-smarter','Fi Series 3 Smart Dog Collar','Escape-prone dogs needing dependable LTE alerts.',1 UNION ALL SELECT 'fi-series-3-vs-pawscout-smarter','Pawscout Smarter GPS Tracker','Owners avoiding a required membership.',2 UNION ALL
SELECT 'eufy-s350-vs-petkit-petwant','eufy Pet Camera S350','Owners who want sharper video and local storage.',1 UNION ALL SELECT 'eufy-s350-vs-petkit-petwant','PETKIT PetWant Camera','PETKIT households wanting one companion app.',2 UNION ALL
SELECT 'pioneer-raindrop-vs-catit-flower-stainless','Pioneer Pet Raindrop Stainless','Cats that like a broad, quiet drinking surface.',1 UNION ALL SELECT 'pioneer-raindrop-vs-catit-flower-stainless','Catit Flower Fountain Stainless Top','Cats that respond to adjustable flow.',2 UNION ALL
SELECT 'petsafe-smartdoor-vs-sureflap-dualscan','PetSafe SmartDoor Connected Pet Door','Homes using schedules across several pets.',1 UNION ALL SELECT 'petsafe-smartdoor-vs-sureflap-dualscan','SureFlap DualScan Connect','Cat owners needing separate in/out permissions.',2 UNION ALL
SELECT 'whistle-health-vs-petivity-monitor-2','Whistle Health Monitor','Owners monitoring whole-day activity and sleep.',1 UNION ALL SELECT 'whistle-health-vs-petivity-monitor-2','Petivity Smart Litter Box Monitor 2','Multi-cat homes focused on litter and weight trends.',2
) v ON v.slug=x.slug WHERE NOT EXISTS (SELECT 1 FROM comparison_best_for b WHERE b.comparison_id=x.id AND b.pick_name=v.pick_name);

INSERT INTO best_picks
  (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,image_url,image_key,content_json,sort_order,is_published)
VALUES
('best-premium-compact-litter-box',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Best premium compact litter box',(SELECT id FROM products WHERE slug='petkit-pura-max-2'),'PETKIT Pura Max 2','$599','Enclosed globe fit and app setup need a careful check.',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'best-picks/premium-compact-litter-box.webp',JSON_OBJECT('why','Premium automation in a footprint that is easier to place','notFor','Cats that refuse enclosed entries'),20,TRUE),
('best-large-hopper-smart-feeder',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Feeders','Best large-hopper smart feeder',(SELECT id FROM products WHERE slug='wopet-7l-smart-feeder'),'WOPET 7L Smart Feeder','$89.99','The larger hopper does not guarantee perfect tiny portions.',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'best-picks/large-hopper-feeder.webp',JSON_OBJECT('why','Seven-liter capacity reduces refill frequency','notFor','Very small meals that require laboratory-level repeatability'),21,TRUE),
('best-escape-alert-dog-collar',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Trackers','Best escape-alert dog collar',(SELECT id FROM products WHERE slug='fi-series-3-smart-collar'),'Fi Series 3 Smart Dog Collar','$149 plus membership','Core tracking requires an ongoing membership and LTE coverage.',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'best-picks/escape-alert-dog-collar.webp',JSON_OBJECT('why','Geofencing and LTE alerts are built around escape prevention','notFor','Owners unwilling to pay a recurring plan'),20,TRUE),
('best-local-storage-pet-camera',(SELECT id FROM categories WHERE slug='pet-cameras'),'Cameras','Best pet camera with local storage',(SELECT id FROM products WHERE slug='eufy-pet-camera-s350'),'eufy Pet Camera S350','$129.99','More setup choices than a basic cloud-first camera.',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'best-picks/local-storage-pet-camera.webp',JSON_OBJECT('why','Sharp pan-and-tilt video with local recording options','notFor','Owners who want the simplest possible setup'),20,TRUE),
('best-wide-surface-water-fountain',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'Water Fountains','Best wide-surface water fountain',(SELECT id FROM products WHERE slug='pioneer-raindrop-stainless'),'Pioneer Pet Raindrop Stainless','$49.99 plus filters','No app or hydration history.',(SELECT image_url FROM categories WHERE slug='smart-water-fountains'),'best-picks/wide-surface-fountain.webp',JSON_OBJECT('why','Broad stainless surface suits whisker-sensitive cats','notFor','Owners who need connected usage alerts'),20,TRUE),
('best-multi-cat-access-door',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'Smart Pet Doors','Best multi-cat access door',(SELECT id FROM products WHERE slug='sureflap-dualscan-connect'),'SureFlap DualScan Connect','$249.99','Cat-sized opening and optional hub add constraints.',(SELECT image_url FROM categories WHERE slug='smart-pet-doors'),'best-picks/multi-cat-access-door.webp',JSON_OBJECT('why','Separate in/out permissions help manage multi-cat homes','notFor','Large dogs or wall openings outside the fit range'),20,TRUE),
('best-collar-free-health-monitor',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'Health Monitors','Best collar-free health monitor',(SELECT id FROM products WHERE slug='petivity-smart-litter-monitor-2'),'Petivity Smart Litter Box Monitor 2','$119.99','It focuses on litter and weight signals rather than whole-day activity.',(SELECT image_url FROM categories WHERE slug='pet-health-monitors'),'best-picks/collar-free-health-monitor.webp',JSON_OBJECT('why','Tracks visits and weight without attaching a device to the pet','notFor','Owners needing sleep or movement data'),20,TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),content_json=VALUES(content_json),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO guides
  (slug,category_id,category_label,title,description,read_time,updated_label,image_url,image_key,content_json,sort_order,is_published)
VALUES
('automatic-litter-box-maintenance-routine',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),'Litter Boxes','Build an automatic litter box maintenance routine','A simple weekly and monthly checklist keeps sensors, waste drawers, seals, and odor control working consistently.','6 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='automatic-litter-boxes'),'guides/automatic-litter-box-maintenance-routine.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Daily glance','body','Check the waste level, litter supply, and whether the cycle completed.'),JSON_OBJECT('title','Weekly clean','body','Wipe sensors and contact surfaces with the manufacturer-approved method.'),JSON_OBJECT('title','Monthly reset','body','Inspect seals, filters, and moving parts before buildup causes a jam.'))),16,TRUE),
('smart-feeder-backup-plan',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),'Smart Pet Feeders','Create a backup plan for a smart feeder','Pair schedules with a backup meal, a power check, and a person who can verify dispensing when you are away.','5 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='smart-pet-feeders'),'guides/smart-feeder-backup-plan.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Test before travel','body','Run a manual portion and confirm the bowl is accessible.'),JSON_OBJECT('title','Keep a backup meal','body','Leave a measured backup portion for any missed schedule.'),JSON_OBJECT('title','Share access','body','Make sure a trusted person can check the feeder and pets.'))),17,TRUE),
('gps-tracker-coverage-checklist',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),'GPS Pet Trackers','GPS tracker coverage and battery checklist','Understand cellular dead zones, live-mode battery cost, geofence timing, and what to do when a location is stale.','7 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='gps-pet-trackers'),'guides/gps-tracker-coverage-checklist.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Map your routine','body','Test the tracker around your home, usual walks, and likely roaming areas.'),JSON_OBJECT('title','Set realistic geofences','body','Allow enough room for GPS drift without making alerts meaningless.'),JSON_OBJECT('title','Plan for low battery','body','Charge on a repeatable schedule and keep a backup identification method.'))),18,TRUE),
('pet-camera-privacy-setup',(SELECT id FROM categories WHERE slug='pet-cameras'),'Pet Cameras','Pet camera privacy and placement setup','Use strong account security, thoughtful placement, and local-storage settings to monitor pets without overexposing your home.','6 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='pet-cameras'),'guides/pet-camera-privacy-setup.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Choose the view','body','Aim at pet areas and entrances rather than private rooms whenever possible.'),JSON_OBJECT('title','Lock the account','body','Use a unique password and two-factor authentication if available.'),JSON_OBJECT('title','Review storage','body','Know how long clips are retained and who can access shared feeds.'))),19,TRUE),
('water-fountain-cleaning-calendar',(SELECT id FROM categories WHERE slug='smart-water-fountains'),'Smart Water Fountains','Set a water fountain cleaning calendar','A repeatable cleaning cadence prevents biofilm, pump noise, and weak flow before pets stop drinking.','5 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='smart-water-fountains'),'guides/water-fountain-cleaning-calendar.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Refresh often','body','Top up with fresh water and remove visible hair or food daily.'),JSON_OBJECT('title','Deep clean','body','Disassemble the pump and drinking path on the maker\'s recommended cadence.'),JSON_OBJECT('title','Replace filters','body','Use the household\'s water hardness and pet count to set reminders.'))),20,TRUE),
('pet-door-installation-measurements',(SELECT id FROM categories WHERE slug='smart-pet-doors'),'Smart Pet Doors','Measure before installing a smart pet door','Get the flap height, pet clearance, wall thickness, and power route right before cutting or drilling.','6 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='smart-pet-doors'),'guides/pet-door-installation-measurements.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Measure the pet','body','Use shoulder height and the widest point of the pet, not a generic breed chart.'),JSON_OBJECT('title','Measure the opening','body','Check the clear flap dimensions and the surrounding trim or wall.'),JSON_OBJECT('title','Plan power','body','Keep outlets, hubs, and manual override access reachable after installation.'))),21,TRUE),
('pet-health-monitor-baseline',(SELECT id FROM categories WHERE slug='pet-health-monitors'),'Pet Health Monitors','How to establish a pet health baseline','Record normal activity, weight, sleep, and litter routines before using a monitor to spot meaningful changes.','7 min read','Sep 2026',(SELECT image_url FROM categories WHERE slug='pet-health-monitors'),'guides/pet-health-monitor-baseline.webp',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Observe first','body','Write down appetite, mobility, sleep, and bathroom patterns for several days.'),JSON_OBJECT('title','Check device fit','body','A loose collar or shared litter box can make a trend unreliable.'),JSON_OBJECT('title','Escalate wisely','body','Use persistent changes as a prompt to contact a veterinarian, not as a diagnosis.'))),22,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),category_label=VALUES(category_label),title=VALUES(title),description=VALUES(description),read_time=VALUES(read_time),updated_label=VALUES(updated_label),image_url=VALUES(image_url),image_key=VALUES(image_key),content_json=VALUES(content_json),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO troubleshooting_guides
  (slug,category_id,product_id,product_name,problem,title,description,difficulty,estimated_time,views_count,updated_label,content_json,sort_order,is_published)
VALUES
('pura-max-2-cycle-stops',(SELECT id FROM categories WHERE slug='automatic-litter-boxes'),(SELECT id FROM products WHERE slug='petkit-pura-max-2'),'PETKIT Pura Max 2','Cleaning cycle stops before completing','Pura Max 2 cycle stops','Check the drum position, waste drawer, sensor window, and litter level before restarting.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Keep pets away during a supervised test cycle.'),25,TRUE),
('petsafe-smart-feed-2-not-connecting',(SELECT id FROM categories WHERE slug='smart-pet-feeders'),(SELECT id FROM products WHERE slug='petsafe-smart-feed-2'),'PetSafe Smart Feed 2.0','Feeder will not connect to the app','Smart Feed 2.0 not connecting','Confirm the supported Wi-Fi band, Bluetooth setup distance, and account pairing state.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Leave a backup meal while changing network settings.'),26,TRUE),
('fi-series-3-geofence-late',(SELECT id FROM categories WHERE slug='gps-pet-trackers'),(SELECT id FROM products WHERE slug='fi-series-3-smart-collar'),'Fi Series 3 Smart Dog Collar','Escape alert arrives late','Fi Series 3 geofence alert late','Review geofence size, LTE coverage, collar battery, and the last successful location timestamp.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Do not wait for an alert before checking on a missing dog.'),27,TRUE),
('eufy-s350-video-blurry',(SELECT id FROM categories WHERE slug='pet-cameras'),(SELECT id FROM products WHERE slug='eufy-pet-camera-s350'),'eufy Pet Camera S350','Video looks soft or blurry','eufy S350 video blurry','Clean the lens, verify stream quality, and improve lighting before changing tracking settings.','Easy fix','10 min',0,'Sep 2026',JSON_OBJECT('safety','A camera view is not a substitute for an in-person safety check.'),28,TRUE),
('pioneer-raindrop-pump-noisy',(SELECT id FROM categories WHERE slug='smart-water-fountains'),(SELECT id FROM products WHERE slug='pioneer-raindrop-stainless'),'Pioneer Pet Raindrop Stainless','Pump is noisy or rattling','Raindrop fountain pump noisy','Refill to the correct level and clear hair or debris from the impeller and intake.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','Unplug the fountain before opening the pump.'),29,TRUE),
('sureflap-dualscan-not-reading',(SELECT id FROM categories WHERE slug='smart-pet-doors'),(SELECT id FROM products WHERE slug='sureflap-dualscan-connect'),'SureFlap DualScan Connect','Door does not recognize a registered microchip','DualScan not reading chip','Check battery, scanner alignment, registration, and whether the pet is moving through too quickly.','Moderate','20 min',0,'Sep 2026',JSON_OBJECT('safety','Keep manual access available while testing recognition.'),30,TRUE),
('petivity-monitor-weight-drift',(SELECT id FROM categories WHERE slug='pet-health-monitors'),(SELECT id FROM products WHERE slug='petivity-smart-litter-monitor-2'),'Petivity Smart Litter Box Monitor 2','Weight readings drift between visits','Petivity monitor weight drift','Place the scale on a hard level surface and confirm the same litter-box setup between readings.','Easy fix','15 min',0,'Sep 2026',JSON_OBJECT('safety','Treat unusual readings as a prompt for observation, not a diagnosis.'),31,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_id=VALUES(product_id),product_name=VALUES(product_name),problem=VALUES(problem),title=VALUES(title),description=VALUES(description),difficulty=VALUES(difficulty),estimated_time=VALUES(estimated_time),updated_label=VALUES(updated_label),content_json=VALUES(content_json),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO troubleshooting_steps (guide_id,instruction,sort_order)
SELECT g.id,v.instruction,v.sort_order FROM troubleshooting_guides g JOIN (
SELECT 'pura-max-2-cycle-stops' slug,'Confirm the drum and waste drawer are seated correctly.' instruction,1 sort_order UNION ALL SELECT 'pura-max-2-cycle-stops','Wipe the sensor window and remove excess litter.',2 UNION ALL SELECT 'pura-max-2-cycle-stops','Restart one supervised cycle.',3 UNION ALL
SELECT 'petsafe-smart-feed-2-not-connecting','Bring the feeder and phone close to the router.',1 UNION ALL SELECT 'petsafe-smart-feed-2-not-connecting','Confirm the network uses a supported 2.4 GHz setup.',2 UNION ALL SELECT 'petsafe-smart-feed-2-not-connecting','Re-run pairing only after noting the current schedule.',3 UNION ALL
SELECT 'fi-series-3-geofence-late','Check the collar battery and last location timestamp.',1 UNION ALL SELECT 'fi-series-3-geofence-late','Test the geofence in an open area with known LTE coverage.',2 UNION ALL SELECT 'fi-series-3-geofence-late','Widen the boundary slightly to account for GPS drift.',3 UNION ALL
SELECT 'eufy-s350-video-blurry','Clean the lens with a soft dry cloth.',1 UNION ALL SELECT 'eufy-s350-video-blurry','Set the stream to a higher quality when bandwidth allows.',2 UNION ALL SELECT 'eufy-s350-video-blurry','Add light or reposition away from a bright window.',3 UNION ALL
SELECT 'pioneer-raindrop-pump-noisy','Unplug the fountain and lift out the pump.',1 UNION ALL SELECT 'pioneer-raindrop-pump-noisy','Clear hair and debris from the intake and impeller.',2 UNION ALL SELECT 'pioneer-raindrop-pump-noisy','Refill to the marked level before testing.',3 UNION ALL
SELECT 'sureflap-dualscan-not-reading','Replace the batteries and wait for the scan light.',1 UNION ALL SELECT 'sureflap-dualscan-not-reading','Confirm the chip number is registered to the correct pet.',2 UNION ALL SELECT 'sureflap-dualscan-not-reading','Walk the pet through slowly and squarely.',3 UNION ALL
SELECT 'petivity-monitor-weight-drift','Move the monitor onto a hard, level floor.',1 UNION ALL SELECT 'petivity-monitor-weight-drift','Keep litter depth and box position consistent.',2 UNION ALL SELECT 'petivity-monitor-weight-drift','Compare several readings before acting on a trend.',3
) v ON v.slug=g.slug WHERE NOT EXISTS (SELECT 1 FROM troubleshooting_steps s WHERE s.guide_id=g.id AND s.instruction=v.instruction);
