/* Expand every published product review with a consistent, useful detail
   structure. Keep Amazon rating separate from the retired editorial score. */
SET NAMES utf8mb4;

UPDATE product_reviews r JOIN products p ON p.slug='litter-robot-4' SET
  r.summary='Whisker Litter-Robot 4 is a rotating self-cleaning litter box designed to separate clumps after each visit and store waste in a covered drawer. The supply bundle adds the consumables needed for setup, so confirm the exact Amazon bundle contents before checkout.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Litter type','value','Clumping litter'),JSON_OBJECT('label','Waste handling','value','Rotating globe + sealed drawer'),JSON_OBJECT('label','Noise','value','About 47 dB at 1 m'),JSON_OBJECT('label','Connectivity','value','Wi-Fi app'),JSON_OBJECT('label','Warranty','value','18 months'),JSON_OBJECT('label','Subscription','value','Optional features')),
  r.strengths_json=JSON_ARRAY('Rotating globe keeps clean litter separate from waste','Large covered drawer reduces daily scooping','App records cycles and usage trends','Bundle includes useful filters, liners and odor supplies','No proprietary litter cartridge required'),
  r.limitations_json=JSON_ARRAY('High upfront price, especially for a bundle','Requires compatible clumping litter','Large cats may find the entry opening restrictive','Odor consumables add recurring cost','Sensor or pinch alerts can pause a cycle until checked'),
  r.sections_json=JSON_ARRAY(
    JSON_OBJECT('title','Daily cleaning workflow','body','After a cat leaves, the globe rotates, sifts the clump and drops it into the drawer. Emptying the drawer and checking the litter level remain regular tasks; automation reduces scooping rather than eliminating maintenance.'),
    JSON_OBJECT('title','Cat fit and transition','body','Measure the entrance, interior and the path to the unit before purchase. Keep a familiar box beside it during the transition and watch each cat use the new box before removing the backup.'),
    JSON_OBJECT('title','App and alerts','body','The app is useful for cycle history, drawer reminders and usage changes. Treat an alert as a prompt to inspect the unit, not as proof of a specific mechanical failure.'),
    JSON_OBJECT('title','Maintenance and consumables','body','Wipe the sensor areas, clean accessible globe surfaces and replace liners, filters or odor supplies on their actual condition. Unplug the base before removing moving parts.'),
    JSON_OBJECT('title','Who should buy it','body','It suits multi-cat homes that value a mature rotating workflow and can accommodate the footprint. It is a weaker fit for very large cats, tight rooms or owners seeking the lowest total cost.')
  ), r.research_date='2026-08-14',r.price_checked_date='2026-09-01',r.next_review_label='November 2026',r.source_count=11
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='petsafe-scoopfree-ultra' SET
  r.summary='PetSafe ScoopFree Crystal Pro Legacy is a crystal-tray self-cleaning litter box. It trades rotating-globe flexibility for a simple rake-and-tray workflow that can be easier to place and explain to a first-time owner.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Litter type','value','Crystal trays'),JSON_OBJECT('label','Waste handling','value','Automatic rake + disposable tray'),JSON_OBJECT('label','Connectivity','value','No app required'),JSON_OBJECT('label','Maintenance','value','Replace crystal tray'),JSON_OBJECT('label','Best fit','value','Single-cat homes')),
  r.strengths_json=JSON_ARRAY('Straightforward setup and controls','Crystal tray contains urine and odor','No cloud account or subscription required','Compact workflow for a single cat'),
  r.limitations_json=JSON_ARRAY('Ongoing disposable-tray cost','Crystal litter is not compatible with every cat','Rake and tray need regular inspection','Less suitable for multi-cat heavy use'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','How the tray workflow works','body','The rake moves waste into the covered end of the crystal tray after a delay. The tray is the consumable, so ownership cost depends on how quickly it saturates in your household.'),JSON_OBJECT('title','Litter and cat acceptance','body','Introduce the crystal texture gradually and keep a familiar box available. Do not mix incompatible litter types or exceed the fill guidance.'),JSON_OBJECT('title','Odor and maintenance','body','Use the delay setting and replace the tray before odor becomes a problem. Clear visible debris and unplug the unit before inspecting the rake path.'),JSON_OBJECT('title','Space and noise','body','Measure the full tray and service clearance, not only the housing. A clear placement makes tray changes safer and reduces accidental obstruction.'),JSON_OBJECT('title','Who should buy it','body','It is best for single-cat owners who prefer simple controls and accept disposable trays. Choose a clumping system if you want reusable litter and a larger multi-cat capacity.')),
  r.research_date='2026-08-20',r.price_checked_date='2026-09-01',r.next_review_label='December 2026',r.source_count=7
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='jiobit-smart-tag' SET
  r.summary='Tractive Smart Cat GPS Tracker is a small connected tracker for cats that tolerate a collar attachment. Its value depends on cellular coverage, safe attachment, battery routine and an active service plan.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Use','value','Outdoor cat location'),JSON_OBJECT('label','Connection','value','Cellular GPS'),JSON_OBJECT('label','App','value','Live location + safe zones'),JSON_OBJECT('label','Attachment','value','Cat-safe collar mount'),JSON_OBJECT('label','Plan','value','Required for remote tracking')),
  r.strengths_json=JSON_ARRAY('Small form factor for suitable cats','Live location and safe-zone alerts','Activity context helps interpret routines','App supports shared household access'),
  r.limitations_json=JSON_ARRAY('Requires cellular coverage and subscription','Battery drains faster in live mode','Not every cat accepts a tracker collar','Indoor location can be delayed or approximate'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','Location behavior','body','GPS estimates the position and cellular service sends it to the app. Read the timestamp and accuracy area before acting on a dot, especially indoors or in weak coverage.'),JSON_OBJECT('title','Fit and safety','body','Use only the documented cat attachment and confirm the collar can release safely. Check for rubbing, snagging or behavior changes during a supervised trial.'),JSON_OBJECT('title','Battery routine','body','Set a charging reminder around your cat’s actual roaming pattern. Live mode and weak coverage consume more power than time spent in a known home zone.'),JSON_OBJECT('title','Safe-zone alerts','body','Test the boundary at home and on the routes your cat uses. A safe-zone alert is a software signal, not a substitute for an ID tag and microchip.'),JSON_OBJECT('title','Who should buy it','body','It suits outdoor cats that tolerate the attachment and travel in supported coverage. It is not a good fit for indoor-only cats or owners unwilling to maintain a service plan.')),
  r.research_date='2026-08-22',r.price_checked_date='2026-09-01',r.next_review_label='December 2026',r.source_count=8
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='petlibro-granary' SET
  r.summary='PETLIBRO Granary 5L Automatic Feeder is a scheduled dry-food dispenser with app control on supported models. The important test is repeatable portion delivery with your food, bowl placement and backup plan.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Food','value','Dry food'),JSON_OBJECT('label','Capacity','value','5 L hopper'),JSON_OBJECT('label','Control','value','Scheduled portions + app'),JSON_OBJECT('label','Power','value','Mains power; verify backup'),JSON_OBJECT('label','Cleaning','value','Removable food-contact parts')),
  r.strengths_json=JSON_ARRAY('Large hopper supports regular schedules','Portion programming is flexible','App provides remote schedule visibility','Bowl and chute are easy to monitor','Useful for measured feeding routines'),
  r.limitations_json=JSON_ARRAY('Food shape affects portion consistency','Wi-Fi or app problems can hide schedule status','Hopper and chute still need cleaning','Backup feeding plan remains essential'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','Portion accuracy','body','Run several weighed portions using the food you actually buy. Compare the average and variation rather than trusting a single first dispense.'),JSON_OBJECT('title','Food compatibility','body','Check kibble size and shape against the exact model guidance. Broken or oily pieces can bridge the chute and change delivered portions.'),JSON_OBJECT('title','App and offline behavior','body','Record schedules before changing Wi-Fi or resetting the feeder. Confirm whether the unit can continue a locally stored schedule when the app is unavailable.'),JSON_OBJECT('title','Cleaning and refills','body','Keep the chute, bowl and sensor areas dry and clear. Refill before the low level becomes a missed meal, and inspect the first portion after each food change.'),JSON_OBJECT('title','Who should buy it','body','It fits owners who want measured dry-food schedules and remote visibility. Pair it with a manual backup whenever a meal is medically or time critical.')),
  r.research_date='2026-08-18',r.price_checked_date='2026-09-01',r.next_review_label='November 2026',r.source_count=9
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='petsafe-healthy-pet-simply-feed' SET
  r.summary='PetSafe Healthy Pet Simply Feed is a standalone programmable feeder for owners who prefer dependable schedules without making cloud connectivity central to the routine.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','Food','value','Dry food'),JSON_OBJECT('label','Control','value','On-device schedule'),JSON_OBJECT('label','Connectivity','value','No app required'),JSON_OBJECT('label','Portions','value','Timed servings'),JSON_OBJECT('label','Power','value','Verify battery or adapter setup')),
  r.strengths_json=JSON_ARRAY('Works without a cloud account','Simple schedule is easy to audit','Good fit for routine dry-food meals','Fewer network settings to troubleshoot'),
  r.limitations_json=JSON_ARRAY('No remote status from an app','Portions depend on food shape','Cleaning is still manual','Power interruption can affect schedules'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','Schedule design','body','Program meals around the pet’s real routine and daylight changes. Verify the next two servings after setup instead of assuming a saved display guarantees delivery.'),JSON_OBJECT('title','Portion testing','body','Weigh multiple servings and record the variance. Adjust the programmed amount only after testing the actual food and bowl position.'),JSON_OBJECT('title','Power and recovery','body','Confirm the correct adapter or battery arrangement and keep a visible backup schedule. Recheck the clock after an outage.'),JSON_OBJECT('title','Cleaning','body','Empty crumbs from the chute and bowl regularly. Disconnect power before removing food-contact parts or clearing a blockage.'),JSON_OBJECT('title','Who should buy it','body','It suits owners who value offline simplicity over remote controls. Choose a connected feeder only when you will actively use its status and alert features.')),
  r.research_date='2026-08-19',r.price_checked_date='2026-09-01',r.next_review_label='December 2026',r.source_count=6
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='furbo-360' SET
  r.summary='Furbo 360 Dog Camera is a rotating indoor pet camera with two-way audio, night vision and treat interaction. Its usefulness comes from quiet observation and reliable Wi-Fi, not from using remote controls as a behavior treatment.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','View','value','Rotating room coverage'),JSON_OBJECT('label','Audio','value','Two-way talk'),JSON_OBJECT('label','Interaction','value','Treat toss'),JSON_OBJECT('label','Night view','value','Color or low-light mode'),JSON_OBJECT('label','Plan','value','Some cloud features optional')),
  r.strengths_json=JSON_ARRAY('Wide rotating view reduces blind spots','Clear live video and audio','Treat interaction can support a calm routine','Dog-focused notifications are useful context'),
  r.limitations_json=JSON_ARRAY('Cloud features may add recurring cost','Remote voice can increase distress for some dogs','Treat size and chute need testing','Requires stable Wi-Fi and careful placement'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','What the camera is for','body','Use it to observe pacing, barking, settling and triggers across the room. Record patterns before changing settings so the camera supports a real plan.'),JSON_OBJECT('title','Placement and privacy','body','Place the camera where movement is visible without pointing it at private areas. Secure the cable and test the view from the places your dog actually uses.'),JSON_OBJECT('title','Audio and alerts','body','Start with quiet observation. Test two-way audio briefly because a remote voice helps some dogs and unsettles others; tune alerts to useful events.'),JSON_OBJECT('title','Treat interaction','body','Use only compatible dry treats and test the landing area while supervised. Do not dispense repeatedly in response to panic or barking.'),JSON_OBJECT('title','Who should buy it','body','It fits owners who need broad visual coverage and occasional interaction. Choose a local-storage camera if avoiding cloud plans is the priority.')),
  r.research_date='2026-08-16',r.price_checked_date='2026-09-01',r.next_review_label='November 2026',r.source_count=8
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='eufy-pet-camera-e220' SET
  r.summary='eufy Security Indoor Cam E220 is a general indoor camera that can monitor a pet without requiring a pet-specific workflow. It is strongest when local-style monitoring and pan/tilt matter more than treats or dog alerts.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','View','value','Indoor pan/tilt'),JSON_OBJECT('label','Storage','value','Verify local or cloud option'),JSON_OBJECT('label','Audio','value','Two-way talk'),JSON_OBJECT('label','Night view','value','Infrared or low light'),JSON_OBJECT('label','Best fit','value','General indoor monitoring')),
  r.strengths_json=JSON_ARRAY('Flexible pan and tilt coverage','Useful as a general household camera','Can avoid pet-specific subscription features depending on setup','Simple live-view use case'),
  r.limitations_json=JSON_ARRAY('Not designed around treat interaction','Alert behavior varies by model and plan','Privacy and storage settings require review','Placement still determines blind spots'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','Monitoring workflow','body','Define the room and behavior you need to observe before choosing a view. A general camera can be enough when live video and basic alerts are the only requirements.'),JSON_OBJECT('title','Storage and privacy','body','Decide where clips should live, who can access them and how long they should remain. Disable unnecessary sharing and test account permissions.'),JSON_OBJECT('title','Placement','body','Use a stable surface with a clear view of the pet’s normal area. Check night visibility and audio delay from another room.'),JSON_OBJECT('title','Connectivity','body','Test the camera near its final location and verify recovery after a router restart. A stale timestamp is evidence of a connection issue, not current location.'),JSON_OBJECT('title','Who should buy it','body','It suits owners who want general indoor monitoring and pan/tilt. Choose a pet-specific camera when treat interaction or dog-focused alerts are central.')),
  r.research_date='2026-08-21',r.price_checked_date='2026-09-01',r.next_review_label='December 2026',r.source_count=7
WHERE r.is_published=TRUE AND r.product_id=p.id;

UPDATE product_reviews r JOIN products p ON p.slug='wyze-cam-v3' SET
  r.summary='Wyze Cam v3 is a low-cost indoor camera that can cover a pet area with live video, motion alerts and night vision. Confirm the exact storage and subscription behavior because those details shape the total cost.',
  r.quick_specs_json=JSON_ARRAY(JSON_OBJECT('label','View','value','Fixed indoor view'),JSON_OBJECT('label','Night view','value','Low-light color mode'),JSON_OBJECT('label','Alerts','value','Motion and sound'),JSON_OBJECT('label','Storage','value','Local or cloud; verify plan'),JSON_OBJECT('label','Audio','value','Two-way talk')),
  r.strengths_json=JSON_ARRAY('Low entry price','Good basic video coverage','Night visibility is useful for a pet room','Small footprint is easy to place'),
  r.limitations_json=JSON_ARRAY('Fixed view can leave blind spots','Advanced alerts or storage may require a plan','Audio is not a behavior treatment','Wi-Fi placement affects reliability'),
  r.sections_json=JSON_ARRAY(JSON_OBJECT('title','Basic coverage','body','Aim the fixed view at the area where the pet spends time and leave enough margin for movement. Walk the room once to identify blind spots before relying on alerts.'),JSON_OBJECT('title','Night and motion testing','body','Test motion and sound alerts during the day and at night. Tune sensitivity so normal activity is useful rather than overwhelming.'),JSON_OBJECT('title','Storage choices','body','Compare local storage, cloud retention and recurring fees for the exact model. Set a retention period that matches your actual need.'),JSON_OBJECT('title','Network reliability','body','Place the camera where the Wi-Fi signal is stable and check the timestamp after a brief outage. Keep a physical check-in routine for important situations.'),JSON_OBJECT('title','Who should buy it','body','It suits budget-conscious owners who need a fixed view. Choose a pan/tilt or pet-specific camera if the animal regularly leaves the frame.')),
  r.research_date='2026-08-21',r.price_checked_date='2026-09-01',r.next_review_label='December 2026',r.source_count=7
WHERE r.is_published=TRUE AND r.product_id=p.id;
