SET NAMES utf8mb4;

/* Bring the newer guide set up to the same decision-ready depth as the core guides. */
UPDATE guides SET read_time='9 min read', content_json=JSON_OBJECT(
  'summary','Automatic litter boxes still need short, regular checks. A predictable daily, weekly, and monthly routine prevents small sensor, litter, and waste-drawer problems from becoming missed cycles or persistent odor.',
  'takeaways',JSON_ARRAY('Check the unit every day even when the app reports normal operation.','Use only cleaning products and litter types approved for the model.','Clean sensors gently; residue and scratches can both affect readings.','Keep a conventional litter box available during deep cleaning or repairs.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Build a realistic schedule','paragraphs',JSON_ARRAY('Maintenance frequency depends on cat count, litter type, humidity, and the size of the waste drawer. Start with the manufacturer schedule, then shorten it if odor, tracking, or residue appears sooner.','Assign the routine to a person, not just an app reminder. A completed notification does not confirm that the globe is clean, the drawer is seated, or every cat is using the box normally.'),'table',JSON_OBJECT('headers',JSON_ARRAY('Cadence','Tasks','Watch for'),'rows',JSON_ARRAY(JSON_ARRAY('Daily','Confirm a completed cycle, litter level, waste level, and normal output','Repeated faults, diarrhea, straining, or a cat avoiding the box'),JSON_ARRAY('Weekly','Empty and reseat the drawer; wipe approved contact areas and sensors','Residue, torn liners, trapped litter, or new odor'),JSON_ARRAY('Monthly','Deep-clean removable parts; inspect seals, filters, and moving interfaces','Wear, swelling, cracks, grinding, or persistent buildup')))),
    JSON_OBJECT('title','2. Daily check: operation and cat health','paragraphs',JSON_ARRAY('Look at the physical unit before relying on its status screen. Confirm the entrance is clear, the bed has the correct depth, and the last cycle returned fully to the home position.','Waste is also health information. A change in visit frequency, urine volume, stool, or a cat repeatedly entering without eliminating deserves attention even if the machine itself is working.'),'checklist',JSON_ARRAY('Verify every cat has urinated and defecated on its usual pattern.','Check the app for repeated or unresolved errors.','Level litter only to the model’s fill line.','Empty the drawer before waste can interfere with cycling.','Keep the step and surrounding floor dry and clear.')),
    JSON_OBJECT('title','3. Weekly clean without damaging sensors','paragraphs',JSON_ARRAY('Power the unit off or unplug it as directed before reaching into moving areas. Remove loose litter with a dry cloth or soft brush first; rubbing gritty residue across a sensor window can scratch it.','Apply approved cleaner to the cloth rather than spraying electronics, seams, or openings. Dry every cleaned surface before restoring power, then run one supervised cycle.'),'bullets',JSON_ARRAY('Do not mix cleaners or use bleach, essential oils, or strong fragrance unless the manual explicitly permits it.','Do not force a globe, rake, drawer, or latch that is out of position.','Photograph recurring residue or errors before cleaning if support may need evidence.')),
    JSON_OBJECT('title','4. Monthly deep clean and inspection','paragraphs',JSON_ARRAY('Disassemble only the parts identified as removable in the manual. Wash, rinse, and dry them completely; retained moisture can make litter clump onto mechanisms or interfere with electrical contacts.','Inspect liners, seals, pinch points, gears, and waste-drawer contacts while surfaces are clean. Replacing a worn consumable early is usually easier than diagnosing intermittent cycles later.'),'checklist',JSON_ARRAY('Check the power cable and plug for damage.','Inspect liners and seals for tears or trapped litter.','Clean accessible vents and odor-control holders.','Confirm the unit sits firmly on the required floor surface.','Reset or recalibrate only when the model instructions call for it.')),
    JSON_OBJECT('title','5. When to stop and get help','paragraphs',JSON_ARRAY('Stop using the automatic cycle if a pet could contact a moving part, the unit strains or grinds, liquid reaches electronics, or an error returns after one careful clean and reseat. Provide a clean conventional box while troubleshooting.','Contact a veterinarian promptly for straining, repeated unproductive visits, blood, marked output changes, vomiting, lethargy, or sudden box avoidance. A maintenance problem and a health problem can happen at the same time.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Can I rely on the waste-drawer notification?','answer','No. Treat it as a reminder and verify the drawer physically; liners, waste distribution, or a dirty sensor can affect the estimate.'),JSON_OBJECT('question','How often should I replace filters?','answer','Follow the exact model instructions, then adjust for cat count and odor. A filter does not replace cleaning the drawer and seals.'),JSON_OBJECT('question','Should I lubricate moving parts?','answer','Only if the manufacturer explicitly identifies a lubricant and application point. Household oils can attract litter or damage materials.')),
  'sourceNote','Exact disassembly, cleaning products, litter depth, and reset steps vary by model. Follow the current manual for your unit.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','Whisker — Litter-Robot support','url','https://www.litter-robot.com/support/'),JSON_OBJECT('label','Cornell Feline Health Center — feline lower urinary tract disease','url','https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-lower-urinary-tract-disease'))
) WHERE slug='automatic-litter-box-maintenance-routine';

UPDATE guides SET read_time='8 min read', content_json=JSON_OBJECT(
  'summary','A smart feeder is a scheduling tool, not a substitute for someone confirming that food reached the bowl and the pet ate. Build backups for power, connectivity, jams, empty hoppers, and human handoff before leaving home.',
  'takeaways',JSON_ARRAY('Test several scheduled meals with the actual food before depending on the feeder.','Battery backup may preserve dispensing but not app control.','Leave written portions and access instructions with a trusted person.','Diet changes and missed meals can be medically important for some pets.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Map every failure point','table',JSON_OBJECT('headers',JSON_ARRAY('Failure','What may still work','Your backup'),'rows',JSON_ARRAY(JSON_ARRAY('Internet or cloud outage','Saved local schedules may continue','Verify the model offline; arrange an in-person check'),JSON_ARRAY('Power outage','Battery-backed schedules may continue','Install fresh approved batteries and keep manual meals ready'),JSON_ARRAY('Food bridge or jam','App and motor may appear normal','Use compatible kibble and have someone inspect the bowl'),JSON_ARRAY('Empty or inaccessible bowl','Dispensing may be recorded','Keep the bowl area clear and verify by sight'))),'paragraphs',JSON_ARRAY('Read the manual to learn which schedules live on the device and which functions depend on a server. Test by briefly disconnecting Wi-Fi while you are home instead of assuming offline behavior.')),
    JSON_OBJECT('title','2. Run a pre-travel test','paragraphs',JSON_ARRAY('Use the same kibble, portion size, batteries, bowl, and schedule you will use while away. Observe multiple meals across at least a full day so intermittent bridging or double-dispensing is easier to see.','Weigh several dispensed portions if meal size matters. “Portions” in an app are usually rotations or volume units, not guaranteed grams for every kibble shape.'),'checklist',JSON_ARRAY('Confirm date, time zone, and every enabled schedule.','Fill below the maximum line and close the lid fully.','Check that the outlet and bowl cannot be shifted by the pet.','Test the battery warning and replace weak batteries.','Confirm cameras or alerts show the bowl, not merely the machine.')),
    JSON_OBJECT('title','3. Prepare the human backup','paragraphs',JSON_ARRAY('Give a nearby person a key, contact details, feeding instructions, and permission to enter without waiting for an app alert. Tell them where manual portions are stored and how to disable the feeder safely.','Ask for a photo of the pet and bowl at agreed times. For longer absences, an in-person welfare check also catches spilled water, illness, temperature problems, or a pet that cannot reach the food.'),'bullets',JSON_ARRAY('Label meals by day and time.','Write the veterinarian and emergency contact numbers.','Explain which missed meal or symptom requires immediate action.','Do not expose your primary account password; use household sharing when available.')),
    JSON_OBJECT('title','4. Choose a safe fallback meal','paragraphs',JSON_ARRAY('A backup should not invite overeating or spoilage. Avoid leaving an unrestricted mound of food for pets with weight, glucose, urinary, or digestive management needs. Your veterinarian can help define a safe missed-meal plan.','Store measured food in a pet-proof place the helper can reach. If wet food is required, use a suitable chilled workflow and shorten unattended intervals.')),
    JSON_OBJECT('title','5. Recheck after any change','paragraphs',JSON_ARRAY('Repeat the supervised test after changing kibble size, portion settings, router, batteries, firmware, or feeder location. Small changes can alter flow and connectivity.','On return, compare remaining food with expected use and review the pet’s appetite, weight, stool, and behavior rather than trusting the event log alone.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Will schedules run when Wi-Fi is down?','answer','Some feeders store schedules locally and others depend on connected services for certain actions. Verify the exact model in its manual and with a supervised offline test.'),JSON_OBJECT('question','Is a camera enough backup?','answer','No. A camera can reveal a problem but cannot clear a jam, refill water, assess illness, or evacuate a pet.'),JSON_OBJECT('question','How long can a pet be left with an automatic feeder?','answer','The feeder does not determine a safe absence. Species, age, health, medication, water, toileting, temperature, and local welfare guidance all matter; arrange appropriate in-person care.')),
  'sourceNote','Feeding requirements are individual. Follow the feeder manual and your veterinarian’s plan for pets with medical or prescription diets.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','FDA — complete and balanced pet food','url','https://www.fda.gov/animal-veterinary/animal-health-literacy/complete-and-balanced-pet-food'),JSON_OBJECT('label','AAHA — nutrition and weight management guidelines','url','https://www.aaha.org/resources/2021-aaha-nutrition-and-weight-management-guidelines/'))
) WHERE slug='smart-feeder-backup-plan';

UPDATE guides SET read_time='9 min read', content_json=JSON_OBJECT(
  'summary','Tracker performance is a chain: charged hardware, a usable sky view, supported cellular coverage, correctly sized safe zones, phone notifications, and a practiced recovery plan. Test that chain where your pet actually goes.',
  'takeaways',JSON_ARRAY('A map pin has a timestamp and uncertainty; it is not continuous proof of location.','Live tracking uses substantially more battery than normal mode.','Geofence alerts can be delayed by detection intervals and weak coverage.','An ID tag and registered microchip remain essential independent layers.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Test real coverage','paragraphs',JSON_ARRAY('Walk the normal route, yard boundary, park, and likely escape corridors with the tracker attached as intended. Compare timestamps and accuracy areas at several known landmarks.','Repeat under tree cover, near tall buildings, and at the edge of cellular service. One successful test beside a window does not represent the device’s hardest conditions.'),'checklist',JSON_ARRAY('Confirm the exact model supports local cellular bands.','Check that the phone can receive notifications with its screen locked.','Invite a second household member and test their access.','Record how the app labels stale, approximate, and offline locations.')),
    JSON_OBJECT('title','2. Set a useful safe zone','paragraphs',JSON_ARRAY('A geofence is a software boundary. Make it large enough to absorb ordinary GPS drift but small enough to give useful warning. Place its edge away from the house when the tracker uses home Wi-Fi or a base station to save power.','Walk across the boundary in several directions and time each notification. Adjust only after multiple tests; a very tight circle may trade faster-looking alerts for repeated false exits.'),'table',JSON_OBJECT('headers',JSON_ARRAY('Symptom','Likely contributor','Check'),'rows',JSON_ARRAY(JSON_ARRAY('False exits at home','Boundary too small or poor sky view','Enlarge slightly and inspect home-zone setup'),JSON_ARRAY('Late exit alert','Detection interval or weak data link','Test timing and cellular coverage'),JSON_ARRAY('Pet shown home after leaving','Stale home-zone state','Read timestamp and verify base/Wi-Fi placement'),JSON_ARRAY('Alert appears in app only','Phone notification restriction','Check permissions, focus modes, and battery optimization')))),
    JSON_OBJECT('title','3. Plan battery around risk','paragraphs',JSON_ARRAY('Advertised endurance usually assumes long periods in power-saving mode. Live tracking, poor signal, cold weather, and frequent alerts can shorten it. Measure your own normal-use baseline instead of planning to the maximum claim.','Choose a charge threshold that leaves time to act. Build charging into a routine, inspect contacts, and put the tracker back on the pet immediately after charging.'),'bullets',JSON_ARRAY('Carry the correct charger on trips.','Replace swollen or damaged batteries or devices according to support guidance.','Avoid starting live mode casually if you may need its remaining charge during a real search.')),
    JSON_OBJECT('title','4. Read the map before moving','paragraphs',JSON_ARRAY('First read the update time and accuracy circle. A precise-looking dot with an old timestamp is only a last-known location. Begin a physical search from that point and likely travel routes while requesting fresh updates.','Share one coordinated map or timestamp with helpers to avoid sending people toward different stale points. Keep someone checking home and familiar return routes.')),
    JSON_OBJECT('title','5. Rehearse the recovery plan','checklist',JSON_ARRAY('Know how to enter live or lost mode.','Keep a current pet photo and description ready.','Verify microchip registration and phone numbers.','Prepare local shelter, veterinarian, and animal-control contacts.','Decide who searches, who monitors updates, and who stays at home.','Never delay a physical search while waiting for a new map pin.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Why does the location stop updating indoors?','answer','Roofs and walls reduce satellite visibility, while weak cellular or Wi-Fi state can prevent a new position from reaching the service.'),JSON_OBJECT('question','Should I use the smallest possible geofence?','answer','Not necessarily. An overly tight boundary can create false alerts from normal location drift. Test several crossings and balance speed with reliability.'),JSON_OBJECT('question','Does a tracker replace a microchip?','answer','No. A microchip supports permanent identification when scanned; a tracker supports active location while attached, charged, and connected. Use both.')),
  'sourceNote','Coverage, update intervals, roaming, and battery behavior vary by model, plan, region, and conditions.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','GPS.gov — GPS accuracy','url','https://www.gps.gov/systems/gps/performance/accuracy/'),JSON_OBJECT('label','AVMA — microchipping of animals','url','https://www.avma.org/resources-tools/pet-owners/petcare/microchips-reunite-pets-families'))
) WHERE slug='gps-tracker-coverage-checklist';

UPDATE guides SET read_time='8 min read', content_json=JSON_OBJECT(
  'summary','Good pet-camera placement shows the animal’s routine without recording more of the home than necessary. Pair a limited field of view with strong account security, deliberate storage settings, and clear rules for every person who has access.',
  'takeaways',JSON_ARRAY('Point the camera at pet zones, not private rooms or neighboring property.','Use a unique password, multi-factor authentication, and the fewest shared accounts possible.','Understand whether clips are stored locally, in the cloud, or both.','Tell household members, visitors, and carers when and where recording occurs.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Define the purpose first','paragraphs',JSON_ARRAY('Write down the question the camera needs to answer: whether a pet reaches its bowl, settles after departure, uses a doorway, or shows a recurring symptom. That goal determines the smallest useful view and retention period.','Avoid defaulting to whole-room surveillance. A narrow, intentional view produces less irrelevant footage and reduces privacy exposure if an account or device is compromised.')),
    JSON_OBJECT('title','2. Choose a safe field of view','checklist',JSON_ARRAY('Include the pet’s bed, bowl, crate, or entry relevant to the goal.','Exclude bathrooms, bedrooms, desks, screens, and security keypads.','Avoid windows or angles that record neighboring homes or public space.','Secure the cable and mount outside chewing or tipping reach.','Keep infrared lights and moving parts from disturbing the pet.','Test glare, darkness, microphone pickup, and motion zones.')),
    JSON_OBJECT('title','3. Lock down the account and network','paragraphs',JSON_ARRAY('Use a long password that is not reused anywhere else and enable multi-factor authentication when offered. Give each person a separate shared account so access can be removed without changing the owner login.','Keep device firmware and the companion app current. Put cameras on a separate guest or IoT network if your router supports it, and disable remote viewing you do not use.'),'bullets',JSON_ARRAY('Review signed-in devices and remove old phones.','Do not share live-feed links in group chats.','Change default device names that reveal an address or room.','Check whether voice control or smart displays expose the feed.')),
    JSON_OBJECT('title','4. Decide what gets stored','table',JSON_OBJECT('headers',JSON_ARRAY('Mode','Advantage','Question to answer'),'rows',JSON_ARRAY(JSON_ARRAY('Live view only','Least retained footage','Does the provider still process thumbnails or events?'),JSON_ARRAY('Local storage','More control and no cloud plan may be needed','Is media encrypted and protected if the device is stolen?'),JSON_ARRAY('Cloud clips','Off-site access and event history','Where, how long, and under whose account is it retained?'),JSON_ARRAY('Continuous recording','Full timeline','Is that amount of household recording necessary?'))),'paragraphs',JSON_ARRAY('Choose the shortest retention that meets the stated purpose. Periodically delete obsolete clips and review whether event labels, thumbnails, or audio have separate settings.')),
    JSON_OBJECT('title','5. Set household rules','paragraphs',JSON_ARRAY('Tell adults, visitors, cleaners, walkers, and sitters about visible cameras before recording them. Laws differ by location, especially for audio, workplaces, rentals, and spaces where privacy is expected.','Create a simple pause or privacy-mode routine for times when monitoring is unnecessary. Revoke temporary access as soon as a trip or care arrangement ends.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Should I leave the microphone on?','answer','Only if audio serves a clear purpose and its use is lawful where you live. Audio can capture far more private information than the camera view.'),JSON_OBJECT('question','Is local storage automatically private?','answer','No. Account access, network security, physical access to the card or device, companion-app telemetry, and thumbnails can still matter.'),JSON_OBJECT('question','Can two-way audio calm a pet?','answer','Sometimes, but some pets become more agitated. Test while nearby and stop if vocalizing, pacing, searching, or distress increases.')),
  'sourceNote','Privacy and recording laws vary by jurisdiction and situation. This is a practical setup guide, not legal advice.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','CISA — securing Internet of Things devices','url','https://www.cisa.gov/news-events/news/securing-internet-things-iot'),JSON_OBJECT('label','FTC — how to secure your home security camera','url','https://consumer.ftc.gov/articles/how-secure-your-home-security-camera'))
) WHERE slug='pet-camera-privacy-setup';

UPDATE guides SET read_time='8 min read', content_json=JSON_OBJECT(
  'summary','Fountain care is about the entire water path, not just replacing a filter. Frequent rinsing plus regular pump disassembly prevents hair, mineral scale, and biofilm from reducing flow or making the water unappealing.',
  'takeaways',JSON_ARRAY('Refresh the water and remove visible debris every day.','Wash every wet surface; a new filter does not clean the reservoir or pump.','Open the pump and clean the impeller on the manufacturer schedule.','Provide another clean water source while the fountain is being cleaned or serviced.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Set the cadence for your home','table',JSON_OBJECT('headers',JSON_ARRAY('Cadence','Core tasks','Adjust sooner when'),'rows',JSON_ARRAY(JSON_ARRAY('Daily','Check level and flow; remove hair and food; refresh water','Several pets share it or debris is visible'),JSON_ARRAY('Every few days','Wash the drinking surface and reservoir','A slippery film, odor, or food contamination appears'),JSON_ARRAY('Weekly','Disassemble and clean the pump and water path','Flow weakens or the pump becomes noisy'),JSON_ARRAY('Per manual','Replace or rinse the filter as directed','Water is hard or the filter discolors quickly'))),'paragraphs',JSON_ARRAY('The label schedule is a starting point. Warm rooms, hard water, long-haired pets, and multiple animals can require more frequent cleaning.')),
    JSON_OBJECT('title','2. Daily water and flow check','checklist',JSON_ARRAY('Confirm the pump is submerged to the required level.','Look for hair, food, insects, foam, or discoloration.','Top up or replace with fresh potable water.','Check that every pet can approach and drink comfortably.','Keep the cable, plug, and surrounding floor dry.','Maintain a separate bowl as a backup source.')),
    JSON_OBJECT('title','3. Clean every wet surface','paragraphs',JSON_ARRAY('Unplug before handling the pump. Separate the lid, reservoir, channels, spout, filter holder, and other approved removable parts. Wash with the method specified by the manufacturer, reaching seams and corners where film collects.','Rinse thoroughly so detergent does not remain in the drinking water. Do not assume a dishwasher is safe unless the instructions identify the exact parts and rack placement.'),'bullets',JSON_ARRAY('Use dedicated small brushes for channels and corners.','Do not mix vinegar, bleach, or other cleaners.','Inspect plastic for scratches that retain residue.','Dry electrical contacts and the plug before reassembly.')),
    JSON_OBJECT('title','4. Open and clean the pump','paragraphs',JSON_ARRAY('Hair and mineral deposits often collect behind the pump cover and around the impeller even when the reservoir looks clean. Remove only the covers and rotor identified by the manual; never power the pump while it is open or dry.','After reassembly, fill to the correct level and listen. Persistent rattling, heat, a damaged cable, or weak flow after cleaning means the pump may need replacement.'),'checklist',JSON_ARRAY('Remove hair from the intake.','Clean the impeller well and magnetic rotor gently.','Clear the outlet tube and connecting channel.','Seat covers and seals without forcing them.','Run a supervised leak and flow test.')),
    JSON_OBJECT('title','5. Manage filters and mineral scale','paragraphs',JSON_ARRAY('Filters capture debris or affect taste, but they do not sterilize water and cannot replace washing. Rinse or soak a new filter only as its instructions direct, and orient it correctly so water cannot bypass it.','Hard-water scale may require more frequent descaling with a manufacturer-approved method. If scale returns quickly, filtered potable water may reduce deposits, but pets still need an appropriate mineral-balanced diet and ready water access.')),
    JSON_OBJECT('title','6. Watch the pet, not just the fountain','paragraphs',JSON_ARRAY('A sudden change in drinking can reflect stress, a dirty or noisy fountain, loss of access, or illness. Check the equipment and provide fresh water, but do not use the fountain as the explanation for a persistent increase or decrease.','Contact a veterinarian for marked drinking or urination changes, inability to keep water down, lethargy, dehydration signs, or other concerning symptoms.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Does the filter make fountain water safe indefinitely?','answer','No. Water, wet surfaces, channels, and the pump still need regular replacement or cleaning, and the filter must be changed as directed.'),JSON_OBJECT('question','Why is the pump noisy?','answer','Low water, trapped air, hair, mineral deposits, an unseated impeller, or wear can cause noise. Unplug, refill, clean, and inspect according to the manual.'),JSON_OBJECT('question','Can I use essential oils or fragrance?','answer','No. Add only potable water unless a veterinarian and the fountain manufacturer specifically direct otherwise; many concentrated oils can be unsafe for pets.')),
  'sourceNote','Cleaning chemistry, dishwasher safety, filter preparation, and pump disassembly vary by model. Follow the exact fountain manual.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','CDC — healthy pets and pet supplies','url','https://www.cdc.gov/healthy-pets/about/index.html'),JSON_OBJECT('label','Cornell Feline Health Center — hydration','url','https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/hydration'))
) WHERE slug='water-fountain-cleaning-calendar';

UPDATE guides SET read_time='8 min read', content_json=JSON_OBJECT(
  'summary','Measure the pet, the clear opening, and the installation surface before buying or cutting. The product’s outer dimensions are not the usable passage, and connected features do not compensate for poor physical fit.',
  'takeaways',JSON_ARRAY('Use the clear flap opening, not the frame size, to check pet fit.','Measure every pet that must pass through at the widest body point.','Confirm door or wall thickness, structure, weather exposure, and power before cutting.','Keep a secure manual access plan for battery, motor, or recognition failures.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Measure the pet in a natural stance','paragraphs',JSON_ARRAY('Measure shoulder or belly clearance while the pet stands normally, then measure the widest point that must pass through. Add practical clearance rather than expecting the animal to squeeze or crouch sharply.','Age, arthritis, body shape, coat, and confidence affect usable fit. If several pets share the door, size for the largest while checking that recognition and closing force remain safe for the smallest.'),'checklist',JSON_ARRAY('Record floor-to-belly or shoulder height.','Record chest, hip, or body width at the widest point.','Observe whether the pet readily uses a similar flap.','Allow for growth or reduced mobility where relevant.')),
    JSON_OBJECT('title','2. Separate opening size from product size','table',JSON_OBJECT('headers',JSON_ARRAY('Measurement','What it tells you','Common mistake'),'rows',JSON_ARRAY(JSON_ARRAY('Clear opening width and height','Space the pet can actually use','Using the outer frame dimensions'),JSON_ARRAY('Cut-out dimensions','Hole required in the surface','Assuming it equals the clear opening'),JSON_ARRAY('Frame depth or tunnel range','Compatible door or wall thickness','Ignoring trim, siding, or cavity depth'),JSON_ARRAY('Step-over height','How high the pet must lift its body','Mounting from a generic breed chart'))),'paragraphs',JSON_ARRAY('Use the current template for the exact size and model. Similar product names can have different cut-outs, tunnel extensions, or mounting hardware.')),
    JSON_OBJECT('title','3. Inspect the installation surface','paragraphs',JSON_ARRAY('Identify material, thickness, studs or framing, glass, wiring, plumbing, weather exposure, and the swing or movement of the existing door. Wall and glass installations often require different kits and professional work.','Do not cut until the template is level, the opening location works on both sides, and all structural or utility questions are resolved. Check landlord, warranty, building, fire, and association requirements where applicable.'),'bullets',JSON_ARRAY('Use a detector and inspect both faces of the proposed opening.','Confirm trim has room to sit flat.','Plan drainage and weather sealing for exterior installations.','Use a qualified installer for glass, structural, electrical, or uncertain wall work.')),
    JSON_OBJECT('title','4. Plan power, radio, and manual access','paragraphs',JSON_ARRAY('Check battery type and expected replacement access, or route low-voltage power without creating a chew, trip, or weather hazard. Hubs and Wi-Fi need usable signal at the installed location.','Learn how the lock behaves when power or connectivity fails. The household must be able to secure the opening and let pets through manually without dismantling a finished wall.')),
    JSON_OBJECT('title','5. Dry-run before the irreversible cut','checklist',JSON_ARRAY('Tape a paper outline of the clear opening at the proposed height.','Guide each pet through a safe mock opening without force.','Verify indoor and outdoor landing areas are clear.','Compare the printed template with the physical product.','Confirm every fastener, tunnel, adapter, and seal is present.','Test recognition and manual lock operation before permanent installation.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','Can I size the door from breed or weight alone?','answer','No. Pets of the same breed or weight can differ in height, width, coat, mobility, and willingness to use a flap. Measure the individual animal.'),JSON_OBJECT('question','Is the cut-out size the same as the passage?','answer','Usually not. The cut-out accepts the frame; the clear opening is the space available to the pet. Check both values.'),JSON_OBJECT('question','Can a wall model be installed in glass?','answer','Only when the manufacturer specifies a compatible glass installation method. Tempered and double-glazed panels typically require specialist fabrication or replacement.')),
  'sourceNote','Templates, compatible thicknesses, adapters, clearances, and weather sealing are model-specific. Verify the current manual before altering a door, wall, or glass panel.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','PetSafe — pet door support','url','https://support.petsafe.net/s/topic/0TO4X000000D3OLWA0/pet-doors'),JSON_OBJECT('label','Sure Petcare — support','url','https://www.surepetcare.com/en-us/support'))
) WHERE slug='pet-door-installation-measurements';

UPDATE guides SET read_time='9 min read', content_json=JSON_OBJECT(
  'summary','A useful baseline describes the individual pet during ordinary life. Collect consistent data long enough to see daily variation, then interpret device trends alongside appetite, behavior, mobility, medication, and direct observation.',
  'takeaways',JSON_ARRAY('A baseline is a range and pattern, not one “normal” number.','Keep device fit, placement, household routine, and measurement conditions consistent.','Multi-pet attribution errors can make clean-looking data misleading.','Consumer monitors support observation; they do not diagnose disease or rule out illness.'),
  'sections',JSON_ARRAY(
    JSON_OBJECT('title','1. Define what you are measuring','table',JSON_OBJECT('headers',JSON_ARRAY('Signal','Useful context','Common limitation'),'rows',JSON_ARRAY(JSON_ARRAY('Activity or sleep','Walks, play, rest, pain, weather, schedule','Wearable fit and algorithm definitions'),JSON_ARRAY('Weight','Same scale, surface, and time relationship to meals','Movement, shared devices, and small normal fluctuations'),JSON_ARRAY('Litter visits','Urine/stool observation and cat identity','Shared boxes and visits without elimination'),JSON_ARRAY('Temperature or respiration','Measurement method and resting state','Consumer sensor location and motion artifacts'))),'paragraphs',JSON_ARRAY('Read how the device defines each metric. “Sleep,” “rest,” “calories,” or “visit” may be an algorithmic estimate rather than a direct clinical measurement.')),
    JSON_OBJECT('title','2. Stabilize the setup','checklist',JSON_ARRAY('Fit a wearable according to its instructions and recheck skin and comfort.','Place scales or litter monitors on a hard, level, unmoving surface.','Assign pets correctly and review ambiguous events.','Keep firmware, time zone, and profile details current.','Record medication, diet, travel, grooming, and major routine changes.','Confirm the pet can opt out or use an alternative resource if needed.')),
    JSON_OBJECT('title','3. Record an ordinary observation window','paragraphs',JSON_ARRAY('Begin when the pet is stable and the household routine is representative. Several days may show weekday and weekend variation; longer observation may be needed for infrequent events, but do not postpone care to finish a baseline.','Write a short daily note alongside the device data: appetite, water intake, urine and stool, vomiting, coughing, scratching, mobility, mood, and anything unusual. This context makes later charts more useful to a veterinarian.'),'bullets',JSON_ARRAY('Use the same weighing conditions where practical.','Mark travel, visitors, storms, heat, and unusual exercise.','Save representative screenshots with dates, units, and time ranges.','Avoid changing several device settings during the baseline.')),
    JSON_OBJECT('title','4. Interpret change as a prompt','paragraphs',JSON_ARRAY('Look for sustained shifts, repeated events, or several signals moving together rather than reacting to every isolated point. First check fit, battery, placement, identity assignment, and missing data, then compare with the pet you can see.','A return to the usual chart does not overrule concerning symptoms. Conversely, a software alert without symptoms still deserves a calm verification and appropriate follow-up, not an automated diagnosis.')),
    JSON_OBJECT('title','5. Prepare a useful veterinary summary','checklist',JSON_ARRAY('State the change and when it began.','Include the baseline range and recent trend, with units.','List symptoms and direct observations.','Note diet, medications, supplements, and recent changes.','Attach a few readable charts rather than an unfiltered data dump.','Ask what should trigger urgent, same-day, or routine follow-up.')),
    JSON_OBJECT('title','6. Do not wait on red flags','paragraphs',JSON_ARRAY('Seek veterinary advice promptly for sudden or marked changes, pain, repeated vomiting, breathing difficulty, collapse, inability to urinate, seizures, severe lethargy, or other concerning symptoms. Use local emergency services when the pet may be in immediate danger.','A missing alert or normal-looking dashboard cannot establish that a sick pet is safe. Direct examination and clinical tests answer questions a consumer sensor cannot.'))
  ),
  'faq',JSON_ARRAY(JSON_OBJECT('question','How long should a baseline be?','answer','Long enough to capture the pet’s normal daily and weekly variation under consistent conditions, often at least several representative days. Do not delay veterinary care to complete it.'),JSON_OBJECT('question','Should I use the population average in the app?','answer','It can provide context, but the individual pet’s verified history and veterinary assessment are more useful than a generic target.'),JSON_OBJECT('question','Can one litter monitor identify several cats perfectly?','answer','No system is perfect. Similar weights, two cats entering together, partial visits, and changes in placement can create attribution errors; review events and keep direct observations.')),
  'sourceNote','This guide is for organizing observations, not diagnosing or treating disease. Discuss meaningful or concerning changes with a veterinarian.',
  'sources',JSON_ARRAY(JSON_OBJECT('label','AAHA — preventive healthcare guidelines','url','https://www.aaha.org/resources/2024-aaha-community-care-guidelines-for-small-animal-practice/'),JSON_OBJECT('label','AVMA — pet owner resources','url','https://www.avma.org/resources-tools/pet-owners'))
) WHERE slug='pet-health-monitor-baseline';
