SET NAMES utf8mb4;

/* Cat-and-dog expansion: grooming, waste cleanup, and walking safety. */
INSERT INTO categories
  (slug,title,eyebrow,description,subtitle,product_count,comparison_count,price_range,top_pick,top_score,image_url,image_key,alt_text,updated_label,sort_order,is_published)
VALUES
  ('pet-grooming-tools','Pet Grooming Tools','Daily care','Clippers, deshedding tools, dryers, and nail grinders compared on pet comfort, control, noise, and upkeep.','Choose around coat type, tolerance for noise, hand control, and the replacement parts you can actually maintain.',2,'1','$19–$199','Oneisall Quiet Clippers',4.0,'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=900&h=600&fit=crop&auto=format','categories/pet-grooming-tools.webp','Dog being groomed with a brush','Sep 2026',8,TRUE),
  ('pet-waste-cleanup','Pet Waste Cleanup','Cleaner routines','Pads, litter mats, odor control, and waste-handling tools compared on containment, absorption, cleaning, and recurring cost.','The cheapest pack is not always the lowest-cost routine: compare leakage, odor, cleanup time, and replacement cadence.',2,'1','$12–$129','WEE WEE XXL Training Pads',4.0,'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&h=600&fit=crop&auto=format','categories/pet-waste-cleanup.webp','Dog beside a clean indoor pet area','Sep 2026',9,TRUE),
  ('pet-walking-safety','Pet Walking & Safety','Outdoors and travel','Harnesses, leashes, collars, car restraints, and reflective gear compared on escape resistance, fit, control, and visibility.','Fit and failure behavior matter more than a feature list: measure the pet, check adjustment range, and plan for the places you actually walk.',2,'1','$15–$149','Ruffwear Front Range Harness',4.1,'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=900&h=600&fit=crop&auto=format','categories/pet-walking-safety.webp','Dog wearing a walking harness outdoors','Sep 2026',10,TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title),eyebrow=VALUES(eyebrow),description=VALUES(description),subtitle=VALUES(subtitle),product_count=VALUES(product_count),comparison_count=VALUES(comparison_count),price_range=VALUES(price_range),top_pick=VALUES(top_pick),top_score=VALUES(top_score),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),updated_label=VALUES(updated_label),sort_order=VALUES(sort_order),is_published=TRUE;

INSERT INTO category_criteria (category_id,title,description,icon,sort_order)
SELECT c.id,v.title,v.description,NULL,v.sort_order FROM categories c JOIN (
SELECT 'pet-grooming-tools' slug,'Coat and pet fit' title,'Match blade range, coat thickness, hair texture, pet size, and whether the tool is intended for face or body work.' description,1 sort_order UNION ALL
SELECT 'pet-grooming-tools','Comfort and control','Compare noise, vibration, heat, grip, snagging behavior, and how easily a nervous pet can pause the session.',2 UNION ALL
SELECT 'pet-grooming-tools','Battery and maintenance','Check runtime, charging, washable parts, blade cleaning, oiling, and replacement-head availability.',3 UNION ALL
SELECT 'pet-grooming-tools','Finish quality','Look for guard options, trimming consistency, nail visibility, and the skill level needed for a safe result.',4 UNION ALL
SELECT 'pet-waste-cleanup','Containment and leakage','Compare absorbency, backing, tray fit, edge sealing, and performance when a pet moves or digs.',1 UNION ALL
SELECT 'pet-waste-cleanup','Odor and surface cleanup','Check odor claims, residue, washability, litter tracking, and how long the routine stays manageable.',2 UNION ALL
SELECT 'pet-waste-cleanup','Capacity and workflow','Measure roll, bag, pad, or bin capacity against the household schedule and number of pets.',3 UNION ALL
SELECT 'pet-waste-cleanup','Recurring cost','Include bags, filters, refills, replacement mats, and the cost of failed containment.',4 UNION ALL
SELECT 'pet-walking-safety','Fit and escape resistance','Measure neck, chest, and girth; compare adjustment range, closure security, and behavior when a pet backs out.',1 UNION ALL
SELECT 'pet-walking-safety','Control and comfort','Compare pressure distribution, handle feel, leash attachment points, padding, and freedom of movement.',2 UNION ALL
SELECT 'pet-walking-safety','Visibility and travel','Check reflective coverage, car restraint compatibility, identification points, and low-light visibility.',3 UNION ALL
SELECT 'pet-walking-safety','Durability and weather','Review stitching, hardware, washing, drying time, wet-weather behavior, and replacement availability.',4
) v ON v.slug=c.slug WHERE NOT EXISTS (SELECT 1 FROM category_criteria cc WHERE cc.category_id=c.id AND cc.title=v.title);

INSERT INTO products (external_id,category_id,slug,name,brand,price,price_display,subscription,score,verdict,best_for,image_url,image_key,alt_text,merchant_name,merchant_url,updated_label,rank_order,is_featured,is_published)
VALUES
('groom-oneisall',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'oneisall-quiet-dog-clippers','Oneisall Quiet Dog Clippers','oneisall',39.99,'$39.99','Replacement blades optional',4.0,'A quiet, approachable clipper for routine trims, with enough guard flexibility for first-time home grooming.','Nervous pets and routine body trims','https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=700&h=520&fit=crop&auto=format','products/oneisall-quiet-dog-clippers.webp','Oneisall quiet dog grooming clippers','oneisall','https://oneisall.com/','Sep 2026',1,TRUE,TRUE),
('groom-wahl',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'wahl-pro-series-animal','Wahl Professional Animal Bravura','Wahl',199.00,'$199','Replacement blades',4.1,'A more capable cordless professional-style clipper, but blade care and technique matter more than with entry tools.','Thick coats and owners who groom often','https://images.unsplash.com/photo-1552053831-71594a27632d?w=700&h=520&fit=crop&auto=format','products/wahl-bravura.webp','Wahl Professional Animal Bravura clipper','Wahl','https://www.wahlpro.com/','Sep 2026',2,TRUE,TRUE),
('waste-weewee',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'wee-wee-pads-xxl','WEE WEE XXL Training Pads','Four Paws',29.99,'$29.99 per pack','Recurring refill',4.0,'Large pads with a practical absorbent core; compare the real usable area and edge leakage for your floor.','Puppies, senior dogs, and larger indoor coverage','https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=700&h=520&fit=crop&auto=format','products/wee-wee-xxl-pads.webp','WEE WEE XXL dog training pads','Four Paws','https://fourpaws.com/','Sep 2026',1,TRUE,TRUE),
('waste-littermat',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'drymate-cat-litter-mat','Drymate Cat Litter Mat','Drymate',24.99,'$24.99','None',3.9,'A washable tracking mat that lowers floor cleanup, though it does not replace a sealed waste routine.','Cats and small spaces where litter tracking is the main issue','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format','products/drymate-litter-mat.webp','Drymate cat litter tracking mat','Drymate','https://drymate.com/','Sep 2026',2,FALSE,TRUE),
('walk-ruffwear',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'ruffwear-front-range-harness','Ruffwear Front Range Harness','Ruffwear',49.95,'$49.95','None',4.1,'A padded everyday harness with clear adjustment points and good walking comfort, but fit must be checked for escape-prone dogs.','Everyday dog walks and first harnesses','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=700&h=520&fit=crop&auto=format','products/ruffwear-front-range.webp','Ruffwear Front Range dog harness','Ruffwear','https://ruffwear.com/','Sep 2026',1,TRUE,TRUE),
('walk-julius',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'julius-k9-idc-powerharness','Julius-K9 IDC Powerharness','Julius-K9',39.99,'$39.99','None',3.9,'A sturdy back-handle harness with broad size coverage, though the design is less ideal for every pulling pattern.','Strong dogs needing a grab handle','https://images.unsplash.com/photo-1593134257782-e89567b79329?w=700&h=520&fit=crop&auto=format','products/julius-k9-idc.webp','Julius-K9 IDC Powerharness','Julius-K9','https://julius-k9.com/','Sep 2026',2,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),brand=VALUES(brand),price=VALUES(price),price_display=VALUES(price_display),subscription=VALUES(subscription),score=VALUES(score),verdict=VALUES(verdict),best_for=VALUES(best_for),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),merchant_name=VALUES(merchant_name),merchant_url=VALUES(merchant_url),updated_label=VALUES(updated_label),rank_order=VALUES(rank_order),is_featured=VALUES(is_featured),is_published=TRUE;

INSERT INTO product_specs (product_id,spec_key,label,value,sort_order)
SELECT p.id,v.spec_key,v.label,v.value,v.sort_order FROM products p JOIN (
SELECT 'oneisall-quiet-dog-clippers' slug,'power' spec_key,'Power' label,'Cordless battery clipper' value,1 sort_order UNION ALL SELECT 'oneisall-quiet-dog-clippers','noise','Noise','Quiet motor for home sessions',2 UNION ALL
SELECT 'wahl-pro-series-animal','power','Power','Cordless professional-style clipper',1 UNION ALL SELECT 'wahl-pro-series-animal','coat','Coat use','Thick and frequent grooming',2 UNION ALL
SELECT 'wee-wee-pads-xxl','routine','Routine','Disposable absorbent pad',1 UNION ALL SELECT 'wee-wee-pads-xxl','coverage','Coverage','XXL indoor dog coverage',2 UNION ALL
SELECT 'drymate-cat-litter-mat','routine','Routine','Washable litter tracking mat',1 UNION ALL SELECT 'drymate-cat-litter-mat','reusable','Replacement style','Reusable and washable',2 UNION ALL
SELECT 'ruffwear-front-range-harness','fit','Primary fit','Everyday adjustable harness',1 UNION ALL SELECT 'ruffwear-front-range-harness','visibility','Visibility','Reflective trim',2 UNION ALL
SELECT 'julius-k9-idc-powerharness','fit','Primary fit','Sturdy harness with back handle',1 UNION ALL SELECT 'julius-k9-idc-powerharness','control','Control','Grab handle for strong dogs',2
) v ON v.slug=p.slug WHERE NOT EXISTS (SELECT 1 FROM product_specs s WHERE s.product_id=p.id AND s.spec_key=v.spec_key);

/* Keep the commerce source explicit: these are Amazon US search/listing entry points and must be refreshed with ASIN/variant data before publication. */
UPDATE products SET merchant_name='Amazon', merchant_url=CASE slug
  WHEN 'oneisall-quiet-dog-clippers' THEN 'https://www.amazon.com/s?k=oneisall+quiet+dog+clippers'
  WHEN 'wahl-pro-series-animal' THEN 'https://www.amazon.com/s?k=Wahl+Professional+Animal+Bravura'
  WHEN 'wee-wee-pads-xxl' THEN 'https://www.amazon.com/s?k=WEE+WEE+XXL+training+pads'
  WHEN 'drymate-cat-litter-mat' THEN 'https://www.amazon.com/s?k=Drymate+cat+litter+mat'
  WHEN 'ruffwear-front-range-harness' THEN 'https://www.amazon.com/s?k=Ruffwear+Front+Range+Harness'
  WHEN 'julius-k9-idc-powerharness' THEN 'https://www.amazon.com/s?k=Julius-K9+IDC+Powerharness'
END WHERE slug IN ('oneisall-quiet-dog-clippers','wahl-pro-series-animal','wee-wee-pads-xxl','drymate-cat-litter-mat','ruffwear-front-range-harness','julius-k9-idc-powerharness');

INSERT INTO comparisons (slug,category_id,product_a_id,product_b_id,product_a_name,product_b_name,verdict,read_time,updated_label,content_json,sort_order,is_featured,is_published)
VALUES
('oneisall-vs-wahl-bravura',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),(SELECT id FROM products WHERE slug='oneisall-quiet-dog-clippers'),(SELECT id FROM products WHERE slug='wahl-pro-series-animal'),'Oneisall Quiet Dog Clippers','Wahl Professional Animal Bravura','Oneisall is easier to approach for routine home trims; Wahl offers more control and blade options for frequent grooming.','8 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Do you need an approachable home clipper or more capability for thick coats?'),40,TRUE,TRUE),
('weewee-pads-vs-drymate-mat',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),(SELECT id FROM products WHERE slug='wee-wee-pads-xxl'),(SELECT id FROM products WHERE slug='drymate-cat-litter-mat'),'WEE WEE XXL Training Pads','Drymate Cat Litter Mat','Pads contain liquid waste; Drymate catches tracked litter and surface debris. They solve different cleanup failures rather than replacing one another.','7 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Are you solving liquid containment or tracking at the exit of a litter area?'),41,TRUE,TRUE),
('ruffwear-vs-julius-k9',(SELECT id FROM categories WHERE slug='pet-walking-safety'),(SELECT id FROM products WHERE slug='ruffwear-front-range-harness'),(SELECT id FROM products WHERE slug='julius-k9-idc-powerharness'),'Ruffwear Front Range Harness','Julius-K9 IDC Powerharness','Ruffwear spreads everyday pressure with a padded shape; Julius-K9 prioritizes a sturdy handle and quick control.','8 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Do you prioritize walking comfort or a firm grab handle?'),42,TRUE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_a_id=VALUES(product_a_id),product_b_id=VALUES(product_b_id),verdict=VALUES(verdict),content_json=VALUES(content_json),updated_label=VALUES(updated_label),is_published=TRUE;

INSERT INTO comparison_criteria (comparison_id,label,product_a_value,product_b_value,winner,sort_order)
SELECT c.id,v.label,v.a_value,v.b_value,v.winner,v.sort_order FROM comparisons c JOIN (
SELECT 'oneisall-vs-wahl-bravura' slug,'Noise and approachability' label,'Quieter entry point' a_value,'More capable, technique-sensitive' b_value,'a' winner,1 sort_order UNION ALL
SELECT 'oneisall-vs-wahl-bravura','Best use','Routine home trims','Frequent or thick-coat grooming','tie',2 UNION ALL
SELECT 'weewee-pads-vs-drymate-mat','Primary job','Liquid containment','Litter tracking','tie',1 UNION ALL
SELECT 'weewee-pads-vs-drymate-mat','Reusable','Disposable refill','Washable mat','b',2 UNION ALL
SELECT 'ruffwear-vs-julius-k9','Control style','Padded walking comfort','Back handle and firm control','tie',1 UNION ALL
SELECT 'ruffwear-vs-julius-k9','Everyday fit','Adjustable everyday harness','Broad, sturdy harness','tie',2
) v ON v.slug=c.slug WHERE NOT EXISTS (SELECT 1 FROM comparison_criteria x WHERE x.comparison_id=c.id AND x.label=v.label);

INSERT INTO best_picks (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,content_json,sort_order,is_published)
VALUES
('best-quiet-grooming-clipper',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'Pet Grooming Tools','Best quiet grooming clipper',(SELECT id FROM products WHERE slug='oneisall-quiet-dog-clippers'),'Oneisall Quiet Dog Clippers','$39.99','Less suited to heavy professional workloads and advanced coat finishing.',JSON_OBJECT('why','A calmer entry point for routine home trims','notFor','Professional daily grooming'),40,TRUE),
('best-large-dog-training-pad',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'Pet Waste Cleanup','Best large-area training pad',(SELECT id FROM products WHERE slug='wee-wee-pads-xxl'),'WEE WEE XXL Training Pads','$29.99 per pack','Recurring refills add up and edge leakage still depends on placement.',JSON_OBJECT('why','More usable coverage for indoor dog routines','notFor','Homes trying to eliminate disposable waste entirely'),41,TRUE),
('best-everyday-dog-harness',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'Pet Walking & Safety','Best everyday dog harness',(SELECT id FROM products WHERE slug='ruffwear-front-range-harness'),'Ruffwear Front Range Harness','$49.95','Measure carefully; no harness is escape-proof for every body shape.',JSON_OBJECT('why','Comfortable everyday control with useful adjustment points','notFor','A substitute for training or supervision'),42,TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),content_json=VALUES(content_json),is_published=TRUE;

INSERT INTO guides (slug,category_id,category_label,title,description,read_time,updated_label,content_json,sort_order,is_published)
VALUES
('choose-a-pet-clipper-by-coat-and-temperament',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'Pet Grooming Tools','How to choose a pet clipper by coat and temperament','Match blade range, noise, heat, runtime, and your pet’s tolerance before you compare motor claims.','7 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Start with the coat','body','Thick, matted, curly, and fine coats need different blade and guard strategies.'),JSON_OBJECT('title','Plan short sessions','body','A quieter tool and breaks often matter more than maximum speed for anxious pets.'),JSON_OBJECT('title','Budget for care','body','Blade cleaning, oil, charging, and replacement parts are part of the ownership cost.'))),40,TRUE),
('build-a-lower-mess-pet-cleanup-routine',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'Pet Waste Cleanup','Build a lower-mess pet cleanup routine','Use containment, placement, disposal, and cleaning cadence together instead of relying on one “odor control” claim.','6 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Find the failure point','body','Separate liquid leakage, litter tracking, odor, and bin overflow before buying a solution.'),JSON_OBJECT('title','Measure the routine','body','Track pads, bags, filters, and cleaning time for a week.'),JSON_OBJECT('title','Make the easy action visible','body','Keep spare supplies and a washable backup where the mess actually occurs.'))),41,TRUE),
('measure-and-fit-a-dog-harness',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'Pet Walking & Safety','How to measure and fit a dog harness','A reliable fit starts with girth and adjustment range, then a supervised backing-out and walking check.','6 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Measure twice','body','Record neck, chest girth, and weight against the maker’s current size chart.'),JSON_OBJECT('title','Check movement','body','The harness should allow shoulder movement without rubbing behind the elbows.'),JSON_OBJECT('title','Test the failure mode','body','At home, supervise a gentle backing-out check and re-adjust before outdoor use.'))),42,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),category_label=VALUES(category_label),title=VALUES(title),description=VALUES(description),content_json=VALUES(content_json),updated_label=VALUES(updated_label),is_published=TRUE;

INSERT INTO troubleshooting_guides (slug,category_id,product_id,product_name,problem,title,description,difficulty,estimated_time,updated_label,content_json,sort_order,is_published)
VALUES
('pet-clipper-pulling-hair',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),(SELECT id FROM products WHERE slug='oneisall-quiet-dog-clippers'),'Oneisall Quiet Dog Clippers','Clipper pulls hair or stalls','Pet clipper pulling hair','Stop, clear the blade, check coat condition, and reduce the amount of hair taken in each pass.','Easy fix','15 min','Sep 2026',JSON_OBJECT('safety','Do not force a hot or jammed blade against the pet.'),40,TRUE),
('training-pad-leaking',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),(SELECT id FROM products WHERE slug='wee-wee-pads-xxl'),'WEE WEE XXL Training Pads','Pad leaks onto the floor','Training pad leaking','Check orientation, overlap, placement, saturation, and whether the pet is using the edge.','Easy fix','10 min','Sep 2026',JSON_OBJECT('safety','Clean urine promptly and keep pets away from wet cleaning products.'),41,TRUE),
('dog-harness-rubs-or-slips',(SELECT id FROM categories WHERE slug='pet-walking-safety'),(SELECT id FROM products WHERE slug='ruffwear-front-range-harness'),'Ruffwear Front Range Harness','Harness rubs or slips','Dog harness rubs or slips','Recheck girth and strap routing, then supervise movement before returning to outdoor walks.','Easy fix','15 min','Sep 2026',JSON_OBJECT('safety','Use a backup identification and control method while fit is uncertain.'),42,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_id=VALUES(product_id),description=VALUES(description),updated_label=VALUES(updated_label),content_json=VALUES(content_json),is_published=TRUE;

INSERT INTO troubleshooting_steps (guide_id,instruction,sort_order)
SELECT g.id,v.instruction,v.sort_order FROM troubleshooting_guides g JOIN (
SELECT 'pet-clipper-pulling-hair' slug,'Turn the clipper off and remove hair from the blade.' instruction,1 sort_order UNION ALL SELECT 'pet-clipper-pulling-hair','Check for mats and take shorter passes with a clean, lubricated blade.',2 UNION ALL SELECT 'pet-clipper-pulling-hair','Let the blade cool before a supervised test.',3 UNION ALL
SELECT 'training-pad-leaking','Confirm the absorbent side is facing up and the pad lies flat.',1 UNION ALL SELECT 'training-pad-leaking','Move the pad to the pet’s actual target area and add overlap if needed.',2 UNION ALL SELECT 'training-pad-leaking','Replace before saturation and clean the floor underneath.',3 UNION ALL
SELECT 'dog-harness-rubs-or-slips','Loosen or tighten each strap evenly against the current size chart.',1 UNION ALL SELECT 'dog-harness-rubs-or-slips','Check two-finger comfort and clear the elbows and throat.',2 UNION ALL SELECT 'dog-harness-rubs-or-slips','Supervise a gentle backing-out test indoors before walking outside.',3
) v ON v.slug=g.slug WHERE NOT EXISTS (SELECT 1 FROM troubleshooting_steps s WHERE s.guide_id=g.id AND s.instruction=v.instruction);
