SET NAMES utf8mb4;

/* Bring the three cat/dog categories to the same editorial baseline as the existing catalog. */
UPDATE categories SET product_count=4,comparison_count='3' WHERE slug IN ('pet-grooming-tools','pet-waste-cleanup','pet-walking-safety');

INSERT INTO category_criteria (category_id,title,description,sort_order)
SELECT c.id,v.title,v.description,v.sort_order FROM categories c JOIN (
SELECT 'pet-grooming-tools' slug,'Safety and learning curve' title,'Prefer guarded, controllable tools and a repeatable stop point over maximum speed or a close finish.' description,5 sort_order UNION ALL
SELECT 'pet-waste-cleanup','Pet and household fit','Account for pet size, number of pets, floor type, room placement, and whether the routine must work overnight.' description,5 UNION ALL
SELECT 'pet-walking-safety','Backup identification and failure plan','Keep identification current and know what happens if a buckle, clip, reflective element, or restraint fails.' description,5
) v ON v.slug=c.slug WHERE NOT EXISTS (SELECT 1 FROM category_criteria x WHERE x.category_id=c.id AND x.title=v.title);

INSERT INTO products (external_id,category_id,slug,name,brand,price,price_display,subscription,score,verdict,best_for,image_url,image_key,alt_text,merchant_name,merchant_url,updated_label,rank_order,is_featured,is_published)
VALUES
('groom-furminator',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'furminator-undercoat-deshedding-tool','FURminator Undercoat deShedding Tool','FURminator',29.99,'$29.99','None',3.9,'A focused undercoat tool that can reduce loose hair when used with the correct size and pressure, but it is not a detangler or clipper.','Short, medium, and long coats with seasonal shedding','https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=700&h=520&fit=crop&auto=format','products/furminator-undercoat.webp','FURminator undercoat deShedding tool for dogs and cats','FURminator','https://www.amazon.com/s?k=FURminator+Undercoat+deShedding+Tool','Sep 2026',3,FALSE,TRUE),
('groom-dremel',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'dremel-pawcontrol-nail-grinder','Dremel PawControl Nail Grinder','Dremel',49.99,'$49.99','Replacement sanding bands',3.8,'A guarded nail grinder that offers gradual control, with sound acclimation and short sessions still required.','Dogs and cats that tolerate gradual nail care','https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=700&h=520&fit=crop&auto=format','products/dremel-pawcontrol.webp','Dremel PawControl pet nail grinder','Dremel','https://www.amazon.com/s?k=Dremel+PawControl+nail+grinder','Sep 2026',4,FALSE,TRUE),
('waste-glad',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'glad-for-pets-waste-bags','Glad for Pets Dog Waste Bags','Glad',14.99,'$14.99','Recurring refill',3.8,'A straightforward refill option where bag thickness, roll compatibility, and dispenser access matter more than scent claims.','Daily dog walks and predictable refill routines','https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=700&h=520&fit=crop&auto=format','products/glad-pets-waste-bags.webp','Glad for Pets dog waste bags','Glad','https://www.amazon.com/s?k=Glad+for+Pets+waste+bags','Sep 2026',3,FALSE,TRUE),
('waste-littergenie',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'litter-genie-plus','Litter Genie Plus Pail','Litter Genie',29.99,'$29.99','Refill bags required',3.7,'A dedicated litter-waste pail can reduce trips to the outside bin, but refill film is an ongoing cost and odor depends on sealing behavior.','Multi-cat homes managing daily scooping','https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format','products/litter-genie-plus.webp','Litter Genie Plus cat waste pail','Litter Genie','https://www.amazon.com/s?k=Litter+Genie+Plus+Pail','Sep 2026',4,FALSE,TRUE),
('walk-wonder',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'wonder-dog-ultimate-leash','WONDERDOG Ultimate Leash','WONDERDOG',34.99,'$34.99','None',3.8,'A multi-use leash with useful configuration options, but each mode adds hardware and adjustment steps to learn.','Owners wanting one leash for walks and hands-free use','https://images.unsplash.com/photo-1558788353-f76d92427f16?w=700&h=520&fit=crop&auto=format','products/wonderdog-ultimate-leash.webp','WONDERDOG Ultimate dog leash','WONDERDOG','https://www.amazon.com/s?k=WONDERDOG+Ultimate+Leash','Sep 2026',3,FALSE,TRUE),
('walk-kurgo',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'kurgo-enhanced-strength-tru-fit','Kurgo Enhanced Strength Tru-Fit Smart Harness','Kurgo',39.95,'$39.95','None',3.8,'A walking harness with a broad adjustment range and vehicle-use context, but the correct size and attachment point are essential.','Dogs that split walking and car-travel routines','https://images.unsplash.com/photo-1593134257782-e89567b79329?w=700&h=520&fit=crop&auto=format','products/kurgo-tru-fit.webp','Kurgo Tru-Fit dog harness','Kurgo','https://www.amazon.com/s?k=Kurgo+Tru-Fit+Harness','Sep 2026',4,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),name=VALUES(name),brand=VALUES(brand),price=VALUES(price),price_display=VALUES(price_display),subscription=VALUES(subscription),score=VALUES(score),verdict=VALUES(verdict),best_for=VALUES(best_for),image_url=VALUES(image_url),image_key=VALUES(image_key),alt_text=VALUES(alt_text),merchant_name='Amazon',merchant_url=VALUES(merchant_url),updated_label=VALUES(updated_label),rank_order=VALUES(rank_order),is_published=TRUE;

INSERT INTO product_specs (product_id,spec_key,label,value,sort_order)
SELECT p.id,v.spec_key,v.label,v.value,v.sort_order FROM products p JOIN (
SELECT 'furminator-undercoat-deshedding-tool' slug,'use' spec_key,'Primary use' label,'Undercoat de-shedding' value,1 sort_order UNION ALL SELECT 'furminator-undercoat-deshedding-tool','pet','Pet fit','Cats and dogs by size',2 UNION ALL
SELECT 'dremel-pawcontrol-nail-grinder','use','Primary use','Guarded nail grinding',1 UNION ALL SELECT 'dremel-pawcontrol-nail-grinder','power','Power','Cordless rechargeable',2 UNION ALL
SELECT 'glad-for-pets-waste-bags','use','Primary use','Daily dog-walk disposal',1 UNION ALL SELECT 'glad-for-pets-waste-bags','reusable','Replacement style','Disposable refill rolls',2 UNION ALL
SELECT 'litter-genie-plus','use','Primary use','Sealed litter-waste pail',1 UNION ALL SELECT 'litter-genie-plus','reusable','Replacement style','Refill film required',2 UNION ALL
SELECT 'wonder-dog-ultimate-leash','use','Primary use','Multi-configuration leash',1 UNION ALL SELECT 'wonder-dog-ultimate-leash','control','Control','Hands-free and standard modes',2 UNION ALL
SELECT 'kurgo-enhanced-strength-tru-fit','use','Primary use','Walking and vehicle harness',1 UNION ALL SELECT 'kurgo-enhanced-strength-tru-fit','fit','Fit','Broad adjustment range',2
) v ON v.slug=p.slug WHERE NOT EXISTS (SELECT 1 FROM product_specs s WHERE s.product_id=p.id AND s.spec_key=v.spec_key);

INSERT INTO product_reviews (product_id,summary,quick_specs_json,strengths_json,limitations_json,research_date,price_checked_date,next_review_label,source_count,is_published)
SELECT p.id,v.summary,v.quick_specs,v.strengths,v.limitations,'2026-09-11','2026-09-11','Recheck Amazon price, variant, and availability on the next review cycle',3,TRUE FROM products p JOIN (
SELECT 'oneisall-quiet-dog-clippers' slug,'A calm, accessible clipper for routine home grooming.' summary,JSON_OBJECT('Best for','Nervous pets and routine trims') quick_specs,JSON_ARRAY('Approachable noise level','Useful guard range') strengths,JSON_ARRAY('Not a professional daily-workload tool') limitations UNION ALL
SELECT 'wahl-pro-series-animal','A more capable clipper for owners willing to maintain blades and technique.',JSON_OBJECT('Best for','Thick coats and frequent grooming'),JSON_ARRAY('Cordless control','Replaceable blade ecosystem'),JSON_ARRAY('Higher cost and learning curve') UNION ALL
SELECT 'furminator-undercoat-deshedding-tool','A targeted shedding tool, not a replacement for brushing, detangling, or clipping.',JSON_OBJECT('Best for','Seasonal shedding'),JSON_ARRAY('Focused undercoat removal','Multiple size options'),JSON_ARRAY('Pressure and coat fit matter') UNION ALL
SELECT 'dremel-pawcontrol-nail-grinder','A gradual nail-care tool for pets that can be acclimated to sound and vibration.',JSON_OBJECT('Best for','Owners wanting incremental nail control'),JSON_ARRAY('Guarded contact','Replaceable sanding bands'),JSON_ARRAY('Needs short acclimation sessions') UNION ALL
SELECT 'wee-wee-pads-xxl','Large disposable pads for indoor dog routines where coverage matters.',JSON_OBJECT('Best for','Puppies and senior dogs'),JSON_ARRAY('Large usable area','Simple workflow'),JSON_ARRAY('Recurring waste and refill cost') UNION ALL
SELECT 'drymate-cat-litter-mat','A washable mat for litter tracking and surface debris.',JSON_OBJECT('Best for','Cats and compact litter areas'),JSON_ARRAY('Reusable','Easy to shake and wash'),JSON_ARRAY('Does not contain liquid waste') UNION ALL
SELECT 'glad-for-pets-waste-bags','A practical daily refill where thickness and dispenser compatibility should be checked.',JSON_OBJECT('Best for','Daily walks'),JSON_ARRAY('Easy to stock','Simple disposal'),JSON_ARRAY('Ongoing refill cost') UNION ALL
SELECT 'litter-genie-plus','A dedicated pail for containing scooped litter between bin trips.',JSON_OBJECT('Best for','Multi-cat homes'),JSON_ARRAY('Convenient indoor workflow','Sealed disposal routine'),JSON_ARRAY('Refill film dependency') UNION ALL
SELECT 'ruffwear-front-range-harness','A padded everyday harness with clear adjustments and comfortable control.',JSON_OBJECT('Best for','Everyday dog walks'),JSON_ARRAY('Comfortable padding','Reflective trim'),JSON_ARRAY('Fit is not escape-proof for every dog') UNION ALL
SELECT 'julius-k9-idc-powerharness','A sturdy harness that prioritizes a back handle and quick control.',JSON_OBJECT('Best for','Strong dogs needing a grab handle'),JSON_ARRAY('Sturdy hardware','Broad size range'),JSON_ARRAY('Less ideal for every pulling pattern') UNION ALL
SELECT 'wonder-dog-ultimate-leash','A configurable leash for owners who value flexibility and can learn each mode.',JSON_OBJECT('Best for','Walks with changing handling needs'),JSON_ARRAY('Multiple configurations','Useful hands-free option'),JSON_ARRAY('More hardware to inspect') UNION ALL
SELECT 'kurgo-enhanced-strength-tru-fit','A broadly adjustable harness that can bridge walking and car routines.',JSON_OBJECT('Best for','Walking plus travel'),JSON_ARRAY('Adjustable fit','Vehicle-use context'),JSON_ARRAY('Attachment and size must be verified')
) v ON v.slug=p.slug ON DUPLICATE KEY UPDATE summary=VALUES(summary),quick_specs_json=VALUES(quick_specs_json),strengths_json=VALUES(strengths_json),limitations_json=VALUES(limitations_json),research_date=VALUES(research_date),price_checked_date=VALUES(price_checked_date),next_review_label=VALUES(next_review_label),source_count=VALUES(source_count),is_published=TRUE;

INSERT INTO comparisons (slug,category_id,product_a_id,product_b_id,product_a_name,product_b_name,verdict,read_time,updated_label,content_json,sort_order,is_featured,is_published)
VALUES
('furminator-vs-dremel-pawcare',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),(SELECT id FROM products WHERE slug='furminator-undercoat-deshedding-tool'),(SELECT id FROM products WHERE slug='dremel-pawcontrol-nail-grinder'),'FURminator Undercoat deShedding Tool','Dremel PawControl Nail Grinder','These solve different grooming jobs: FURminator manages loose undercoat; Dremel manages nail length.','7 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Are you solving shedding or nail-care control?'),43,FALSE,TRUE),
('litter-genie-vs-waste-bags',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),(SELECT id FROM products WHERE slug='litter-genie-plus'),(SELECT id FROM products WHERE slug='glad-for-pets-waste-bags'),'Litter Genie Plus Pail','Glad for Pets Dog Waste Bags','The pail improves indoor litter workflow; bags are the simpler, portable choice for dog walks.','6 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Do you need indoor litter containment or portable daily disposal?'),44,FALSE,TRUE),
('kurgo-vs-wonderdog-walk-setup',(SELECT id FROM categories WHERE slug='pet-walking-safety'),(SELECT id FROM products WHERE slug='kurgo-enhanced-strength-tru-fit'),(SELECT id FROM products WHERE slug='wonder-dog-ultimate-leash'),'Kurgo Enhanced Strength Tru-Fit Smart Harness','WONDERDOG Ultimate Leash','Kurgo changes how the pet is fitted and restrained; WONDERDOG changes how the handler configures the leash.','7 min read','Sep 2026',JSON_OBJECT('decisionQuestion','Is the limiting factor fit and vehicle use, or leash flexibility?'),45,FALSE,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_a_id=VALUES(product_a_id),product_b_id=VALUES(product_b_id),verdict=VALUES(verdict),content_json=VALUES(content_json),updated_label=VALUES(updated_label),is_published=TRUE;

INSERT INTO comparison_best_for (comparison_id,pick_name,audience,sort_order)
SELECT c.id,v.pick_name,v.audience,v.sort_order FROM comparisons c JOIN (
SELECT 'furminator-vs-dremel-pawcare' slug,'FURminator Undercoat deShedding Tool' pick_name,'Owners solving loose hair and seasonal shedding.' audience,1 sort_order UNION ALL SELECT 'furminator-vs-dremel-pawcare','Dremel PawControl Nail Grinder','Owners building gradual nail-care sessions.',2 UNION ALL
SELECT 'litter-genie-vs-waste-bags','Litter Genie Plus Pail','Multi-cat homes scooping indoors every day.',1 UNION ALL SELECT 'litter-genie-vs-waste-bags','Glad for Pets Dog Waste Bags','Dog owners needing portable disposal.',2 UNION ALL
SELECT 'kurgo-vs-wonderdog-walk-setup','Kurgo Enhanced Strength Tru-Fit Smart Harness','Homes combining walks and car travel.',1 UNION ALL SELECT 'kurgo-vs-wonderdog-walk-setup','WONDERDOG Ultimate Leash','Handlers wanting configurable leash modes.',2
) v ON v.slug=c.slug WHERE NOT EXISTS (SELECT 1 FROM comparison_best_for x WHERE x.comparison_id=c.id AND x.pick_name=v.pick_name);

INSERT INTO comparison_criteria (comparison_id,label,product_a_value,product_b_value,winner,sort_order)
SELECT c.id,v.label,v.a_value,v.b_value,v.winner,v.sort_order FROM comparisons c JOIN (
SELECT 'furminator-vs-dremel-pawcare' slug,'Primary job' label,'Undercoat shedding' a_value,'Nail grinding' b_value,'tie' winner,1 sort_order UNION ALL SELECT 'furminator-vs-dremel-pawcare','Acclimation','Pressure and coat fit','Sound and vibration','tie',2 UNION ALL
SELECT 'litter-genie-vs-waste-bags','Best location','Indoor litter station','Portable outdoor walks','tie',1 sort_order UNION ALL SELECT 'litter-genie-vs-waste-bags','Ongoing supplies','Refill film','Bag rolls','tie',2 UNION ALL
SELECT 'kurgo-vs-wonderdog-walk-setup','What changes','Pet fit and restraint','Handler configuration','tie',1 sort_order UNION ALL SELECT 'kurgo-vs-wonderdog-walk-setup','Travel context','Harness and vehicle use','Leash-only setup','a',2
) v ON v.slug=c.slug WHERE NOT EXISTS (SELECT 1 FROM comparison_criteria x WHERE x.comparison_id=c.id AND x.label=v.label);

INSERT INTO best_picks (slug,category_id,category_label,title,pick_product_id,pick_name,budget,tradeoff,content_json,sort_order,is_published)
VALUES
('best-de-shedding-tool',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'Pet Grooming Tools','Best de-shedding tool',(SELECT id FROM products WHERE slug='furminator-undercoat-deshedding-tool'),'FURminator Undercoat deShedding Tool','$29.99','Use the correct size and light pressure; it is not a detangler or clipper.',JSON_OBJECT('why','Focused tool for seasonal loose undercoat','notFor','Matted coats or close trimming'),43,TRUE),
('best-indoor-litter-waste-pail',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'Pet Waste Cleanup','Best indoor litter-waste pail',(SELECT id FROM products WHERE slug='litter-genie-plus'),'Litter Genie Plus Pail','$29.99 plus refill film','The refill system adds ongoing cost and capacity depends on scooping frequency.',JSON_OBJECT('why','Keeps daily scooping contained between bin trips','notFor','Owners who do not want proprietary refills'),44,TRUE),
('best-walk-and-travel-harness',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'Pet Walking & Safety','Best walk-and-travel harness',(SELECT id FROM products WHERE slug='kurgo-enhanced-strength-tru-fit'),'Kurgo Enhanced Strength Tru-Fit Smart Harness','$39.95','Verify the current size and vehicle-use instructions for the exact variant.',JSON_OBJECT('why','Connects everyday walking and travel decisions','notFor','Unsupervised restraint or a substitute for a secured crate'),45,TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title),pick_product_id=VALUES(pick_product_id),pick_name=VALUES(pick_name),budget=VALUES(budget),tradeoff=VALUES(tradeoff),content_json=VALUES(content_json),is_published=TRUE;

INSERT INTO guides (slug,category_id,category_label,title,description,read_time,updated_label,content_json,sort_order,is_published)
VALUES
('pet-grooming-session-safety-checklist',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),'Pet Grooming Tools','Pet grooming session safety checklist','Prepare the coat, tool, room, breaks, and stop conditions before a home grooming session.','6 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Prepare first','body','Brush out loose debris, charge the tool, and gather a cool-down surface.'),JSON_OBJECT('title','Use short passes','body','Stop to check skin, blade temperature, noise tolerance, and pet posture.'),JSON_OBJECT('title','Know when to stop','body','Mats near skin, distress, heat, or a damaged tool are reasons to stop and seek help.'))),43,TRUE),
('pet-waste-cost-and-capacity-planner',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),'Pet Waste Cleanup','Plan pet-waste capacity and recurring cost','Estimate pads, bags, refill film, bins, and cleaning time across the actual number of pets and daily events.','6 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Count events','body','Use a normal week rather than a package headline to estimate usage.'),JSON_OBJECT('title','Add failure cost','body','Include leaks, extra bags, floor cleaner, and emergency replacement purchases.'),JSON_OBJECT('title','Set a refill trigger','body','Keep enough supplies for a delayed delivery or a travel week.'))),44,TRUE),
('dog-walk-safety-preflight',(SELECT id FROM categories WHERE slug='pet-walking-safety'),'Pet Walking & Safety','Dog-walk safety preflight','A two-minute preflight catches loose clips, poor fit, low visibility, missing ID, and travel mistakes before leaving home.','5 min read','Sep 2026',JSON_OBJECT('sections',JSON_ARRAY(JSON_OBJECT('title','Check the pet','body','Confirm fit, breathing comfort, paws, and current identification.'),JSON_OBJECT('title','Check the equipment','body','Inspect stitching, clips, leash attachment, reflective areas, and backup contact details.'),JSON_OBJECT('title','Check the route','body','Carry light, water, and a plan for traffic, weather, and unexpected separation.'))),45,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),category_label=VALUES(category_label),title=VALUES(title),description=VALUES(description),content_json=VALUES(content_json),updated_label=VALUES(updated_label),is_published=TRUE;

INSERT INTO troubleshooting_guides (slug,category_id,product_id,product_name,problem,title,description,difficulty,estimated_time,updated_label,content_json,sort_order,is_published)
VALUES
('dremel-pawcontrol-vibration-too-high',(SELECT id FROM categories WHERE slug='pet-grooming-tools'),(SELECT id FROM products WHERE slug='dremel-pawcontrol-nail-grinder'),'Dremel PawControl Nail Grinder','Pet reacts strongly to vibration','Dremel PawControl vibration too high','Start with sound-only acclimation, check the guard and band, and use very short contact rather than pressing harder.','Moderate','20 min','Sep 2026',JSON_OBJECT('safety','Stop at distress or bleeding and do not continue through a damaged nail.'),43,TRUE),
('litter-genie-odor-escaping',(SELECT id FROM categories WHERE slug='pet-waste-cleanup'),(SELECT id FROM products WHERE slug='litter-genie-plus'),'Litter Genie Plus Pail','Odor escapes the pail','Litter Genie odor escaping','Check the refill seal, waste drop, fill level, and cleaning cadence before replacing the whole pail.','Easy fix','15 min','Sep 2026',JSON_OBJECT('safety','Wash hands after handling waste and keep the pail inaccessible to pets.'),44,TRUE),
('kurgo-harness-car-clip-twists',(SELECT id FROM categories WHERE slug='pet-walking-safety'),(SELECT id FROM products WHERE slug='kurgo-enhanced-strength-tru-fit'),'Kurgo Enhanced Strength Tru-Fit Smart Harness','Vehicle clip twists or sits incorrectly','Kurgo harness car clip setup','Confirm the exact attachment path and vehicle instructions for the current harness variant before driving.','Moderate','15 min','Sep 2026',JSON_OBJECT('safety','Do not use an unfamiliar restraint on a moving vehicle until it is correctly installed and tested.'),45,TRUE)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),product_id=VALUES(product_id),description=VALUES(description),updated_label=VALUES(updated_label),content_json=VALUES(content_json),is_published=TRUE;

INSERT INTO troubleshooting_steps (guide_id,instruction,sort_order)
SELECT g.id,v.instruction,v.sort_order FROM troubleshooting_guides g JOIN (
SELECT 'dremel-pawcontrol-vibration-too-high' slug,'Run the grinder near the pet without touching the nail.' instruction,1 sort_order UNION ALL SELECT 'dremel-pawcontrol-vibration-too-high','Check the sanding band and guard for damage or buildup.',2 UNION ALL SELECT 'dremel-pawcontrol-vibration-too-high','Touch one nail for one second, then stop and reward.',3 UNION ALL
SELECT 'litter-genie-odor-escaping','Confirm the refill film is seated and the cutter area closes fully.',1 UNION ALL SELECT 'litter-genie-odor-escaping','Push waste below the seal and avoid overfilling the pail.',2 UNION ALL SELECT 'litter-genie-odor-escaping','Wipe the rim and set a shorter emptying cadence.',3 UNION ALL
SELECT 'kurgo-harness-car-clip-twists','Park the vehicle before inspecting or changing the restraint.',1 UNION ALL SELECT 'kurgo-harness-car-clip-twists','Confirm the clip is attached to the designated vehicle-use point.',2 UNION ALL SELECT 'kurgo-harness-car-clip-twists','Check fit and movement while stationary before driving.',3
) v ON v.slug=g.slug WHERE NOT EXISTS (SELECT 1 FROM troubleshooting_steps s WHERE s.guide_id=g.id AND s.instruction=v.instruction);
