SET NAMES utf8mb4;

/* Product-detail editorial layer: verified commerce facts are merged with these scenario-specific notes. */
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A low-noise cordless grooming kit with six guide combs and a removable, rinsable blade. Use it for routine trims and introduce the motor gradually to nervous pets.',
quick_specs_json=JSON_OBJECT('Listing identity','B01HRSZRXM','Power','Rechargeable cordless','Included','6 guide combs','Cleaning','Removable and rinsable blade'),
strengths_json=JSON_ARRAY('Cordless setup and beginner-oriented guide combs','Rinsable blade simplifies cleanup'),
limitations_json=JSON_ARRAY('Exact runtime and noise level should be confirmed on the live listing','Not a substitute for professional handling of matted coats'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked listing identifies a rechargeable cordless clipper with six guide combs and a removable, rinsable blade.'),JSON_OBJECT('title','Where owner fit matters','body','Noise tolerance, coat condition, blade heat, and the handler’s technique matter more than the product title. Stop if the blade heats or pulls.'),JSON_OBJECT('title','First-use checklist','body','Charge fully, fit a guard, run the tool away from the pet, then make short supervised passes on a brushed coat.'))
WHERE p.slug='oneisall-quiet-dog-clippers';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A professional-style cordless clipper with a 5-in-1 adjustable blade for cats and small to medium dogs. It offers more control, but requires blade care and a steadier technique.',
quick_specs_json=JSON_OBJECT('Listing identity','B00EVBXI5S','Power','Lithium-ion cordless','Blade','5-in-1 adjustable blade','Fit','Cats and small to medium dogs'),
strengths_json=JSON_ARRAY('Adjustable blade supports several trim lengths','Professional-style cordless handling'),
limitations_json=JSON_ARRAY('Listing variant is purple 41870-0423','Confirm replacement blade and charger compatibility'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The selected listing is the purple 41870-0423 Bravura variant with a 5-in-1 fine adjustable blade.'),JSON_OBJECT('title','Why it is not a universal pick','body','The listing names cats and small to medium dogs; large, dense, or matted coats may need a different tool and professional handling.'),JSON_OBJECT('title','Ownership checks','body','Confirm charger, blade oil, replacement blade availability, and cooling breaks before a full grooming session.'))
WHERE p.slug='wahl-pro-series-animal';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A large-dog undercoat tool for reducing loose hair from shedding. The listing specifies weekly use and an ergonomic handle, not detangling or coat clipping.',
quick_specs_json=JSON_OBJECT('Listing identity','B07MZDTG76','Fit','Large dogs over 50 lb','Coat','Long hair undercoat','Use','Weekly de-shedding'),
strengths_json=JSON_ARRAY('Clear size and weight target','Designed for loose-hair removal'),
limitations_json=JSON_ARRAY('Wrong size or pressure can irritate skin','Not a clipper or mat-removal tool'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked variant is for large dogs over 50 lb with long hair and is described for weekly undercoat de-shedding.'),JSON_OBJECT('title','How to use the evidence','body','Treat the size and coat description as a fit boundary. Brush a clean, dry coat with light pressure and stop when the skin becomes irritated.'),JSON_OBJECT('title','Do not overread the claim','body','Reducing loose hair does not guarantee less shedding in every home and does not resolve mats close to skin.'))
WHERE p.slug='furminator-undercoat-deshedding-tool';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A cordless PawControl 7760-PET grinder and trimmer for dogs, cats, and small animals. Its guarded, gradual approach is useful only when the pet accepts sound and vibration.',
quick_specs_json=JSON_OBJECT('Listing identity','B0DJ3JR93D','Power','Cordless and rechargeable','Use','Nail grinder and trimmer','Pet fit','Dogs, cats, and small animals'),
strengths_json=JSON_ARRAY('Guarded contact supports gradual sessions','Cordless format is easy to position'),
limitations_json=JSON_ARRAY('Acclimation is still required','Stop immediately at distress or bleeding'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The PawControl listing identifies a cordless rechargeable grooming kit for dogs, cats, and small animals.'),JSON_OBJECT('title','Acclimation is part of the product','body','Run the motor near the pet before touching a nail. One-second contacts with rewards are safer than trying to finish every nail in one session.'),JSON_OBJECT('title','Safety boundary','body','Use the guard and correct bit, keep hair clear, and stop if the nail cracks, bleeds, or the pet cannot remain calm.'))
WHERE p.slug='dremel-pawcontrol-nail-grinder';

UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='Four Paws Wee-Wee Superior Performance pads with a runoff barrier edge and a 27.5 by 44 inch format. Verify the pack count and variant before checkout.',
quick_specs_json=JSON_OBJECT('Listing identity','B004GWSIJ8','Format','27.5 x 44 in','Feature','Runoff barrier edge','Use','Puppy and dog potty training'),
strengths_json=JSON_ARRAY('Large floor coverage','Runoff barrier is explicitly described'),
limitations_json=JSON_ARRAY('Disposable refill cost depends on usage','Placement still determines edge leakage'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked listing identifies a 27.5 by 44 inch pad with a runoff barrier edge. Confirm pack count because listings can combine variants.'),JSON_OBJECT('title','Placement is a performance variable','body','Lay the pad flat with the absorbent side up and keep the target area away from corners where urine can miss the backing.'),JSON_OBJECT('title','Cost reality','body','Measure weekly usage before comparing pack prices. Add floor cleaner and replacement cadence to the routine cost.'))
WHERE p.slug='wee-wee-pads-xxl';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Drymate 28 by 36 inch XL cat litter mat described as waterproof, urine-proof, absorbent, machine washable, and soft on paws.',
quick_specs_json=JSON_OBJECT('Listing identity','B099HBMZ67','Size','28 x 36 in XL','Cleaning','Machine washable','Use','Litter trapping and floor protection'),
strengths_json=JSON_ARRAY('Large washable surface','Listing explicitly describes urine-proof and absorbent construction'),
limitations_json=JSON_ARRAY('A mat does not replace a sealed waste pail','Confirm the exact color and size variant'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked listing is the dark gray 28 by 36 inch XL mat, with machine-washable and litter-trapping claims.'),JSON_OBJECT('title','What it solves','body','Use it to catch tracking and protect the floor at a litter-box exit. It does not handle scooped waste or replace routine cleaning.'),JSON_OBJECT('title','Maintenance check','body','Shake or vacuum the mat regularly and follow the current washing instructions; inspect the backing for wear before reusing it.'))
WHERE p.slug='drymate-cat-litter-mat';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='Glad for Pets extra-large scented waste bags with easy-tie handles, intended for walking, camping, and travel. Confirm the count and scent variant on Amazon.',
quick_specs_json=JSON_OBJECT('Listing identity','B01LZDV5X3','Format','Extra-large bags','Feature','Easy-tie handles','Use','Walking, camping, and travel'),
strengths_json=JSON_ARRAY('Easy-tie handle format','Portable daily-walk use'),
limitations_json=JSON_ARRAY('Scent is not suitable for every household','Leak and tear resistance should be checked in the selected variant'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked listing describes extra-large scented bags with easy-tie handles for walking, camping, and travel.'),JSON_OBJECT('title','Fit to the dispenser','body','Check roll width and core compatibility before buying in bulk. Carry a spare roll when walking in areas without bins.'),JSON_OBJECT('title','Scent and disposal','body','Choose unscented alternatives if a pet or household member is scent-sensitive and follow local waste rules.'))
WHERE p.slug='glad-for-pets-waste-bags';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Litter Genie standard disposal pail with a 14 ft standard refill. The listing says it can hold up to 14 days of one cat’s litter, depending on use.',
quick_specs_json=JSON_OBJECT('Listing identity','B019W0OH48','Refill','14 ft standard refill included','Claimed capacity','Up to 14 days for one cat','Use','Indoor litter disposal'),
strengths_json=JSON_ARRAY('Dedicated indoor scooping workflow','Refill system is clearly identified'),
limitations_json=JSON_ARRAY('Refill film is an ongoing cost','Capacity varies with cat count and scooping frequency'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The checked listing identifies the standard pail and standard refill, with a stated up-to-14-day capacity for one cat.'),JSON_OBJECT('title','Do not treat capacity as a guarantee','body','Multiple cats, larger clumps, and delayed emptying shorten the interval. Set an emptying reminder rather than waiting for the pail to fill.'),JSON_OBJECT('title','Odor workflow','body','Push waste below the seal, close the chute fully, and clean the rim when odor escapes.'))
WHERE p.slug='litter-genie-plus';

UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Ruffwear Front Range dog chest harness in the checked Basalt Gray X-Small variant, with four adjustment points, foam padding, two leash attachment points, an ID pocket, and reflective trim.',
quick_specs_json=JSON_OBJECT('Listing identity','B0CLB3VFB8','Variant','Basalt Gray, X-Small','Adjustment','Four points','Attachments','Two leash attachment points','Visibility','Reflective trim'),
strengths_json=JSON_ARRAY('Four adjustment points are explicitly listed','Two leash points and reflective trim support everyday use'),
limitations_json=JSON_ARRAY('The checked ASIN is X-Small; do not generalize its fit to larger dogs','No harness is escape-proof for every body shape'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','Variant matters','body','The verified Amazon listing is Basalt Gray, X-Small. Use the current size chart and exact variant, not a generic Front Range name.'),JSON_OBJECT('title','Fit check','body','Two fingers should fit under the straps without rubbing behind the elbows or restricting shoulder movement.'),JSON_OBJECT('title','Visibility and control','body','Reflective trim helps in low light, while the two attachment points should be checked for the walking style and leash being used.'))
WHERE p.slug='ruffwear-front-range-harness';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Julius-K9 IDC Powerharness in the checked Size 0 neon green variant. Confirm chest range and current color/size before ordering.',
quick_specs_json=JSON_OBJECT('Listing identity','B004IQ6EZ2','Variant','Size 0, Neon Green','Type','IDC Powerharness','Use','Dog walking harness'),
strengths_json=JSON_ARRAY('Exact size and color variant are identifiable','Sturdy harness format for controlled walks'),
limitations_json=JSON_ARRAY('Size 0 is not a universal fit','Back-handle control does not replace leash and behavior training'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','Variant matters','body','The verified listing is Size 0 in Neon Green. Match chest measurement and weight guidance to the actual dog before purchase.'),JSON_OBJECT('title','Fit check','body','Inspect the chest strap, throat clearance, buckle closure, and whether the dog can back out under gentle supervised pressure.'),JSON_OBJECT('title','Walking context','body','Use the handle only for brief control; select the leash attachment and walking setup that distribute pressure safely.'))
WHERE p.slug='julius-k9-idc-powerharness';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Voyager 5 ft nylon dog leash in the checked Medium variant, with reflective material, a soft neoprene handle, and heavy-duty metal clips.',
quick_specs_json=JSON_OBJECT('Listing identity','B0B1F73ZTS','Length','5 ft','Variant','Medium, black','Visibility','Reflective','Handle','Soft neoprene'),
strengths_json=JSON_ARRAY('Length and size variant are clearly identified','Reflective material and padded handle support routine walks'),
limitations_json=JSON_ARRAY('Leash strength depends on dog size and pulling behavior','Inspect metal clips and stitching regularly'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The verified listing is a 5 ft black Medium Voyager nylon leash with reflective material, a soft neoprene handle, and heavy-duty metal clips.'),JSON_OBJECT('title','Control check','body','A leash is only as secure as the harness or collar attachment. Inspect the clip gate and stitching before each walk.'),JSON_OBJECT('title','Use context','body','Choose a shorter traffic handle or backup connection when walking near roads, crowds, or escape-prone dogs.'))
WHERE p.slug='voyager-nylon-dog-leash';
UPDATE product_reviews r JOIN products p ON p.id=r.product_id SET
summary='A Kurgo Enhanced Strength Tru-Fit Smart Harness in the checked black Large variant, described for dogs up to 75 lb with a seatbelt tether, steel carabiner, all-steel buckles, and padded chest.',
quick_specs_json=JSON_OBJECT('Listing identity','B0064ACNLO','Variant','Black, Large','Vehicle context','Crash-tested car harness listing','Hardware','Steel carabiner and all-steel buckles','Fit claim','Dogs up to 75 lb'),
strengths_json=JSON_ARRAY('Vehicle-use context is explicit in the listing','Exact Large variant and hardware are identifiable'),
limitations_json=JSON_ARRAY('Do not generalize the Large variant to every dog','Follow current vehicle-restraint instructions; a harness is not a substitute for safe travel setup'),
sections_json=JSON_ARRAY(JSON_OBJECT('title','What the listing supports','body','The verified listing is the black Large variant and describes a seatbelt tether, steel carabiner, all-steel buckles, padded chest, and a dog weight claim up to 75 lb.'),JSON_OBJECT('title','Walk versus travel','body','Check the exact attachment point for walking and vehicle use. Do not improvise a restraint path from a generic leash attachment.'),JSON_OBJECT('title','Pre-drive check','body','Inspect buckles, tether, fit, and movement while parked before relying on the setup in a moving vehicle.'))
WHERE p.slug='kurgo-enhanced-strength-tru-fit';
