<script setup lang="ts">
useSeoMeta({ title: 'PetMetricus — Pet product research you can actually verify.', description: 'Independent research on cat and dog products across smart home, feeding, hydration, litter, grooming, waste cleanup, walking, and safety with documented methods and practical buying guidance.' })

const { data: homeData } = await usePetMetricApi('home-content', '/home', {
  categories: [],
  comparisons: [],
  bestPicks: [],
  troubleshooting: [],
  stats: { productsResearched: '—', productCategories: '—', comparisonsPublished: '—', guidesPublished: '—' }
})
const homeCategories = computed(() => homeData.value.categories || [])
const homeHero = computed(() => homeData.value.hero || {})
const homeStats = computed(() => homeData.value.stats || { productsResearched: '—', productCategories: '—', comparisonsPublished: '—', guidesPublished: '—' })
const homeMethodology = computed(() => homeData.value.methodology?.length ? homeData.value.methodology : [{ icon:'source', title:'Documented methods', body:'Every research decision is recorded: which specs were compared, which sources were consulted, and on what date.' },{ icon:'clock', title:'Dated and updated', body:'Pages show a last-checked date and are flagged for review when price, spec, or availability changes.' },{ icon:'refresh', title:'Error correction', body:'Readers can submit corrections. Verified changes are applied and noted on the page with a changelog entry.' },{ icon:'target', title:'Practical conclusions', body:'Every verdict explains who a product suits, the trade-offs that matter, and what to check before buying.' }])
// Keep the homepage decision modules intentionally scannable. The library
// pages remain the complete source; the homepage is only a short entry point.
const homeComparisons = computed(() => (homeData.value.comparisons || []).slice(0, 3).map((item: any) => ({ ...item, verdict: item.homeVerdict || item.verdict })))
const homeBestPicks = computed(() => (homeData.value.bestPicks || []).slice(0, 8))
const homeTroubles = computed(() => (homeData.value.troubleshooting || []).slice(0, 3))
</script>

<template>
  <div>
    <section class="home-hero"><div class="container home-hero-grid"><div><p class="design-eyebrow"><i />{{ homeHero.eyebrow || 'Independent research' }}</p><h1 class="display">{{ homeHero.title || 'Pet tech research you can actually verify.' }}</h1><p class="home-hero-copy">{{ homeHero.description || 'We turn product specifications, documented evidence, and ownership trade-offs into practical guidance for choosing pet technology that fits your pet and daily routine.' }}</p><div class="hero-actions"><NuxtLink class="btn btn--accent" to="/products/">Browse All Products <AppIcon name="arrow" :size="16" /></NuxtLink><NuxtLink class="btn btn--outline" to="/comparisons/">Compare Products</NuxtLink></div></div><aside class="research-glance"><p class="design-section-label">Research at a glance</p><div class="glance-grid"><div><strong>{{ homeStats.productsResearched }}</strong><span>products researched</span></div><div><strong>{{ homeStats.productCategories }}</strong><span>product categories</span></div><div><strong>{{ homeStats.comparisonsPublished }}</strong><span>product comparisons</span></div><div><strong>{{ homeStats.guidesPublished }}</strong><span>buying guides</span></div></div><p class="glance-note">Every product page shows the research date, sources used, practical trade-offs, and the next scheduled review.</p><NuxtLink class="light-link" to="/editorial-standards/">Read our editorial standards <AppIcon name="external" :size="11" /></NuxtLink></aside></div></section>

    <section class="home-section"><div class="container"><div class="home-section-intro"><p class="design-section-label">Product database</p><h2 class="display">Explore pet tech by category.</h2><p>Browse independent research, practical buying criteria, product comparisons, and troubleshooting guides for every category.</p></div><div class="home-category-grid"><NuxtLink v-for="category in homeCategories" :key="category.slug" class="home-category-card" :to="`/products/${category.slug}/`"><div class="home-category-image"><R2Image :image-key="category.imageKey" :fallback="category.img" :alt="category.alt" /></div><div class="home-category-body"><h3>{{ category.title }}</h3><p>{{ category.description }}</p><div><span>{{ category.count }} products</span><AppIcon name="arrow" :size="15" /></div></div></NuxtLink></div><div v-if="!homeCategories.length" class="empty-state">Product research is temporarily unavailable. Please try again shortly.</div><div class="home-section-actions"><NuxtLink class="btn btn--dark" to="/products/">Browse all products <AppIcon name="arrow" :size="14" /></NuxtLink></div></div></section>

    <section class="home-section home-section--muted"><div class="container home-split-section"><div class="home-section-copy"><p class="design-section-label">Comparison library</p><h2 class="display">Which one should you actually buy?</h2><p>Head-to-head comparisons use identical criteria: one-time cost, subscription cost, reliability data, and which type of owner each product suits.</p><NuxtLink class="home-inline-link" to="/comparisons/">All comparisons <AppIcon name="arrow" :size="14" /></NuxtLink></div><div class="home-list"><NuxtLink v-for="item in homeComparisons" :key="item.href" class="home-list-card" :to="item.href"><div><div class="home-versus"><strong>{{ item.a }}</strong><span>vs</span><strong>{{ item.b }}</strong></div><p>{{ item.verdict }}</p></div><div class="home-list-side"><span v-if="item.views && item.views !== '0'">{{ item.views }} views</span><AppIcon name="arrow" :size="14" /></div></NuxtLink><div v-if="!homeComparisons.length" class="empty-state">Comparisons are temporarily unavailable.</div></div></div></section>

    <section class="home-section home-best-section"><div class="container"><div class="home-section-intro"><p class="design-section-label">Scene-based buying guides</p><h2 class="display">Best picks for your situation.</h2><p>Each guide states budget, trade-offs, and who it does and doesn't suit — not just a ranked list.</p></div><div class="home-best-grid"><NuxtLink v-for="pick in homeBestPicks" :key="pick.href" class="home-best-card" :to="pick.href"><span>{{ pick.title }}</span><AppIcon name="arrow" :size="14" /></NuxtLink></div><div class="home-section-actions"><NuxtLink class="btn btn--dark" to="/best-picks/">Browse all best picks <AppIcon name="arrow" :size="14" /></NuxtLink></div></div></section>

    <section class="home-section home-section--dark"><div class="container home-split-section"><div class="home-section-copy"><p class="design-section-label">Troubleshooting library</p><h2 class="display">Product not working right?</h2><p>Step-by-step fixes organized by symptom: confirm the problem, common causes, and when to contact support or replace the unit.</p><NuxtLink class="home-inline-link" to="/troubleshooting/">All troubleshooting guides <AppIcon name="arrow" :size="14" /></NuxtLink></div><div class="home-list home-list--dark"><NuxtLink v-for="item in homeTroubles" :key="item.href" class="home-list-card" :to="item.href"><div><span class="home-list-product">{{ item.product }}</span><strong>{{ item.problem }}</strong></div><div class="home-list-side"><span class="difficulty-text" :class="{ moderate: item.difficulty === 'Moderate' }">{{ item.difficulty }}</span><AppIcon name="arrow" :size="14" /></div></NuxtLink></div></div></section>

    <section class="home-section home-method"><div class="container"><div class="home-section-intro"><p class="design-section-label">How we work</p><h2 class="display">Research you can verify, not just trust.</h2></div><div class="method-grid"><div v-for="item in homeMethodology" :key="item.title" class="method-card"><span class="method-icon" aria-hidden="true"><AppIcon :name="(item.icon === '🔬' ? 'source' : item.icon === '📅' ? 'clock' : item.icon === '💬' ? 'refresh' : item.icon === '🔗' ? 'shield' : item.icon) as any" :size="26" /></span><h3>{{ item.title }}</h3><p>{{ item.body }}</p></div></div><div class="correction-cta"><div><h3>Found an error or outdated information?</h3><p>Submit a correction and we'll verify and update within 5 business days.</p></div><NuxtLink class="btn btn--accent" to="/contact/">Submit a correction <AppIcon name="arrow" :size="15" /></NuxtLink></div></div></section>
  </div>
</template>
